### ISSUE TITLE
Sublime Text theme/language changes to support PhET-related highlighting

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/phet-info#1]
Let me know if anyone else would like to use this and I can check it into public version control.

I hated how hard my comment/assertion/log-heavy code was to read (all of those help produce bug-free code), so I made modifications to the color syntax highlighting and syntax parsing that makes the important code more visible:
![sublime-phet-1](https://cloud.githubusercontent.com/assets/480878/3505908/142324d6-0669-11e4-8565-908432168693.png)

It properly handles branches where logging or assertions are isolated:
![sublime-phet-2](https://cloud.githubusercontent.com/assets/480878/3505911/273c405c-0669-11e4-8719-591c1b2af2f8.png)

And also makes require statements a bit easier to read:
![sublime-phet-3](https://cloud.githubusercontent.com/assets/480878/3505915/344093fc-0669-11e4-9ca7-f67d2b09f6ec.png)

**Comment by ariel-phet** [comment]
@andrewadare does this seem like something you or @jessegreenberg would want? If so maybe mark for dev meeting?

**Comment by andrewadare** [comment]
Sure, I'd be interested to try this out. Will need to make sure it's compatible with the latest ST3 build (3114) and all my other tooling/customization around ST3.

**Comment by jessegreenberg** [comment]
This looks like a really cool tool, but I don't think its something I would want to use.  I don't write a lot of log heavy code, so I don't want my assertions and logs to be hidden relative to my other code.  Module statements should also now be blocked at the top of each file like

```js
// modules

// constants

// images

// strings
```
By preference, I somewhat prefer not color coding module/plugin/file and I can read this information quickly.

**Comment by pixelzoom** [comment]
5/19/16 dev meeting:
Anyone who is interested in this can check it out under phet-info/ide/sublime-text-2/ (2 files).

**Comment by pixelzoom** [comment]
Looks like this was checked in and anyone who was interested has presumably had a look (since they were instructed to do so on 5/19/16).  Closing.
