### ISSUE TITLE
Update deployment guidelines for ph-scale and ph-scale-basics

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/phet-info#10]
Since they have a chipper SHA between https://github.com/phetsims/chipper/commit/a9df10232f2ec48fe9578278f87f5d471c573445 (Nov 6th, 2015) and https://github.com/phetsims/chipper/commit/dfa45c1613a09c16d71afc9a896e8a246adc41da (Nov 10th, 2015), ```grunt deploy-production --locales=*``` will fail out after reporting that it was deployed:
```
deployed: http://www.colorado.edu/physics/phet/dev/html/ph-scale-basics/1.2.1/ph-scale-basics_en.html
Fatal error: Should not specify locales for production deployment
```

It will NOT have been deployed, and ```--locales=*``` should be omitted. I'll update the guidelines, and hopefully this will be helpful to @pixelzoom for future maintenance releases.

Related to maintenance releases in https://github.com/phetsims/yotta/issues/17.

**Comment by jonathanolson** [comment]
Done.

**Comment by pixelzoom** [comment]
@jonathanolson wrote:
> hopefully this will be helpful to @pixelzoom for future maintenance releases.

Thanks @jonathanolson, this was indeed useful when I had to publish maintenance releases for https://github.com/phetsims/ph-scale/issues/69.
