### ISSUE TITLE
add "PhET-iO" and "A11y" columns to responsible_dev.md ?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#100]
Proposal to add "PhET-iO" and "A11y" columns to [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md), that indicate whether a sim has been instrumented.  It would help me to keep track of the state of sims that I'm responsible for.

**Comment by jessegreenberg** [comment]
Sounds good, and should they include name of the developer who did the instrumentation?

**Comment by samreid** [comment]
Once complete, how will this spreadsheet differ in substance from the one proposed in https://github.com/phetsims/tasks/issues/980#issuecomment-490996388.  Should they be combined or at least inform each other structurally?

**Comment by pixelzoom** [comment]
Sounds like a good idea to fold responsible_dev.md into phetsims/tasks#980 spreadsheet.

**Comment by zepumph** [comment]
Now we don't want a spreadsheet in https://github.com/phetsims/tasks/issues/980. We discussed briefly in dev meeting today, but decided to wait for @ariel-phet for more discussion.

@jonathanolson mentioned that perhaps package.json could be a nice way to keep track of this stuff, and it could be then easily added to built files like the README, or phetmarks, or even binder's offshoot child.

>that indicate whether a sim has been instrumented.

MK: At least for a11y, it may not be enough to just have a boolean, or even a single author. There are many features that a sim could be outfitted with, and different devs may implement different features.

**Comment by samreid** [comment]
During today's meeting, we also discussed that using package.json is a good fit for repos, but will not scale to a file-by-file basis (say, for reporting who is responsible for AccordionBox).  But if we standardize a machine-readable syntax for this in package.json, we could also reuse it in header jsdoc on a file-by-file basis.

**Comment by ariel-phet** [comment]
We need a more maintainable process (preferably automated) that accomplishes this goal.
