### ISSUE TITLE
add code-review items related to type expressions

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#102]
From 5/23/19 dev meeting...  I will add these items to [code_review_checklist.md](https://github.com/phetsims/phet-info/blob/master/checklists/code_review_checklist.md):

- [ ] Use most restrictive type expression when documenting params

- [ ] For type-specific Property subclasses, verify that type expressions are actually appropriate.   For example `@param {BooleanProperty} property` does not support `DerivedProperty` and `DynamicProperty` instances that have boolean values.

**Comment by chrisklus** [comment]
From 05/23/19 dev meeting:

The dev team decided that all type docs (obvious or not) should be included in common code. In sim-specific code, it's up to the developer whether to include obvious type docs.

**Comment by pixelzoom** [comment]
@chrisklus I'll review your if you review mine. Deal?

**Comment by pixelzoom** [comment]
@chrisklus Since all of this deals with type expressions... How about handle this entire issue, and you review?

**Comment by pixelzoom** [comment]
@chrisklus Since all of this deals with type expressions... How about if I handle this entire issue, and you review?

**Comment by chrisklus** [comment]
>@chrisklus Since all of this deals with type expressions... How about if I handle this entire issue, and you review?

Sounds great

**Comment by pixelzoom** [comment]
@chrisklus ready for review. I added the [Type Expressions](https://github.com/phetsims/phet-info/blob/master/checklists/code_review_checklist.md#type-expressions) section.

**Comment by chrisklus** [comment]
@pixelzoom looks really nice and covers everything relevant that was discussed at dev meeting. Back to you.
