### ISSUE TITLE
add a table of contents to code_review_checklist.md

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#103]
[code_review_checklist.md](https://github.com/phetsims/phet-info/blob/master/checklists/code_review_checklist.md) has gotten long enough that  having a table of contents at the top would make my life easier.   I sometimes remember the section I want to find, but not the string to search for.

**Comment by pixelzoom** [comment]
Done. @chrisklus would you mind taking a peek, since you're also looking at the checklist for #102?  Closing if all looks OK.

**Comment by chrisklus** [comment]
Looks good, all links work as expected. Closing.

**Comment by pixelzoom** [comment]
Reopening.

Oops.  I forgot that this checklist is intended to be copied to a code-review issue.  When that happens, the TOC links are not correct for that issue. And there's really no way to edit them to make them correct - section heading links work for .md file, not for comments in GitHub issue. 

So I'm considering either:

(1) Deleting the TOC from code_review_checklist.md 

(2) Adding a note that the TOC should be deleted from code_review_checklist.md  when copying it to an issue.  

I'm leaning slightly towards (2), since having the TOC makes it easy to get to a specific section when reviewing the template.

@chrisklus @ariel-phet thoughts?

**Comment by chrisklus** [comment]
>When that happens, the TOC links are not correct for that issue.

@pixelzoom I noticed that as well when setting up https://github.com/phetsims/phet-io/issues/1471, so I just deleted them. I like to reference this doc when not nessarily doing a specific review, so option (2) would be my preference as well.

**Comment by pixelzoom** [comment]
Thanks @chrisklus.  I changed the "NOTE" at the top of the template to:

> _NOTE! Prior to doing a code review, copy this checklist to a GitHub issue for the repository being reviewed. Delete the Table of Contents sections, since the links will be incorrect._

Does that seem clear/reasonable?

**Comment by chrisklus** [comment]
Looks great, thanks for doing that. Back to you to close.
