### ISSUE TITLE
Convert examples in code_review_checklist.md to ES6

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#104]
Convert examples in [code_review_checklist.md](https://github.com/phetsims/phet-info/blob/master/checklists/code_review_checklist.md) to ES6, unless the example is specific to pre-ES6 code.

**Comment by pixelzoom** [comment]
Done. @chrisklus mind taking a peek, since you recently reviewed a couple of similar issues?

**Comment by chrisklus** [comment]
Looks good, @pixelzoom. I made a couple small edits. Ready to close if those look good to you.

**Comment by pixelzoom** [comment]
👍 Closing.
