### ISSUE TITLE
failure in new-repo-add-labels.sh

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#105]
I created new sim repo `diffusion`, then did the following, as instructed in [new_repo_checklist.md](https://github.com/phetsims/phet-info/blob/master/checklists/new_repo_checklist.md): 

```
% cd phet-info/github-labels
% ./new-repo-add-labels.sh phetsims/diffusion
```

Most of the commands appeared to succeed, but here's the last bit:

```
% ./new-repo-add-labels.sh phetsims/diffusion
...
Path: https://api.github.com/repos/phetsims/diffusion/labels
Data: {"name":"type:user-feedback","color":"EDE162"}
Result (201 expected):
HTTP/1.1 201 Created
Path: https://api.github.com/repos/phetsims/diffusion/labels
Data: {"name":"type:wontfix","color":"ffffff"}
Result (201 expected):
HTTP/1.1 422 Unprocessable Entity
Path: https://api.github.com/repos/phetsims/diffusion/labels
Data: {"name":"{"name":"status:ready-for-qa"","color":""color":"00cc00"}"}
Result (201 expected):
HTTP/1.1 400 Bad Request
Complete.
%
```

Problem here?

**Comment by pixelzoom** [comment]
Identical problem when I did this for new repo `gases-intro` today.

```
% ./new-repo-add-labels.sh phetsims/gases-intro
...
Path: https://api.github.com/repos/phetsims/gases-intro/labels
Data: {"name":"type:wontfix","color":"ffffff"}
Result (201 expected):
HTTP/1.1 422 Unprocessable Entity
Path: https://api.github.com/repos/phetsims/gases-intro/labels
Data: {"name":"{"name":"status:ready-for-qa"","color":""color":"00cc00"}"}
Result (201 expected):
HTTP/1.1 400 Bad Request
Complete.
```

**Comment by pixelzoom** [comment]
Looking at the labels for diffusion and gases-intro, they are both missing "type:wontfix" and "status:ready-for-qa".

**Comment by mattpen** [comment]
I introduced a bug in the automatic updating of the `github-labels` file.  I was adding new labels as a json object instead of a comma separated list. 

This was fixed in df977d764cb74f4d22923bfc650e890fe543ff90

This bug affected the automatic add of "status:ready-for-qa".  I reran the script after the above fix and confirmed this added the label to diffusion, gases-intro, and vector-addition.

**Comment by pixelzoom** [comment]
Thanks @mattpen.  I now see both "status:ready-for-qa" and "type:wontfix" as labels for those repos. 

If there's nothing else to do here, feel free to close.

**Comment by mattpen** [comment]
@pixelzoom - The `422 Unprocessable Entity` status code usually means that this is a duplicate entry.  I'm not sure if there are other reasons for this error, but in this case it appears to be so as both diffusion and gases-intro have the `type:wontfix` label.  This label is already in the standard github label set so this is expected, but the script attempts to add it anyway in case github changes this set in the future.

Can you please confirm? 

I added a note about this status in the documentation in 153a6e574b32d519137913a1c4c55e2009f949dd

**Comment by pixelzoom** [comment]
Confirmed.
