### ISSUE TITLE
steps to create a new sim repo fail

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#106]
[new_repo_checklist.md](https://github.com/phetsims/phet-info/blob/master/checklists/new_repo_checklist.md) has problems.  I was following the steps to create a new sim repo (`diffusion`) and things failed as soon as I attempted to `git push`:

```
% cd diffusion
% git init
Initialized empty Git repository in /Users/cmalley/PhET/GitHub/diffusion/.git/
cmalley@b7[59]: git add .gitignore
cmalley@b7[60]: git commit -m "Initial commit"
[master (root-commit) 5c8620f] Initial commit
 1 file changed, 9 insertions(+)
 create mode 100644 .gitignore
% git remote add origin https://github.com/phetsims/diffusion.git
% git push -u origin master
To https://github.com/phetsims/diffusion.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/phetsims/diffusion.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
%
```

I don't know if these instructions ever worked, since this is the first time I've used them.  I suspect that there are missing steps (like pulling the created repo to your working copy).  I don't have time to debug.   I was able improvise and create the repo, but that could be difficult for newer developers.

Assigning to @ariel-phet to prioritize and assign.  These instructions were written by @jonathanolson.

**Comment by jonathanolson** [comment]
It looks like the repo was initialized in the first step, based on the initial commit https://github.com/phetsims/diffusion/commit/9af96d6f63a964ba947ef36bbc986ad1d25431c7. Maybe the interface has changed on new repo creation, but it's important for the steps to NOT create a readme/license/etc. initially.

Step 1 of the checklist is:

>  Create the repo: Go to https://github.com/phetsims, hit the "New" button). Copy (with modifications) the description from another sim, keep "Public" for visibility and DO NOT INITIALIZE the repo (we'll do that later).

Let me know if I should clarify the documentation. If GitHub now doesn't have "not initializing" as an option, we'll need to rework the steps.

**Comment by pixelzoom** [comment]
GitHHub has a checkbox labeled "Initialize this repository with a README".  I had no idea that that was what you meant by "DO NOT INITIALIZE the repo".   Recommended to change to something like 'Do not check the "Initialize this repository with a README' because...'.

**Comment by pixelzoom** [comment]
Creating .gitignore or LICENSE would presumably have teshe same effect of initializing the repo, since it involves creating files.  And the instructions say nothing about those items.  I believe I choose to create a GPL3 License, so perhaps that's what messed things up.   

I've modified the first step to read as follow, @jonathanolson please correct as needed:

> Create the repo: Go to https://github.com/phetsims, hit the "New" button. Copy (with modifications) the description from another sim. Set visibility to "Public". DO NOT check the "Initialize this repository with a README" checkbox. Leave "Add .gitignore" and "Add a license" set to "None". (We don't want to create any files, because that will initialize the repo, which we need to defer to a later step.)

**Comment by pixelzoom** [comment]
I did a full "polish" of [new_repo_checklist.md](https://github.com/phetsims/phet-info/blob/master/checklists/new_repo_checklist.md), @jonathanolson please review.

**Comment by jonathanolson** [comment]
Those changes are great, thanks!
