### ISSUE TITLE
Prefer "field" to "lowercase property"

### ISSUE THREAD

**Issue by zepumph** [phetsims/phet-info#109]
There is a lot of emphasis on making sure that "javascript property" or "lowercase property" or "_property_" is different from `AXON/Property`. Why don't we instead just say "field" instead?

This would look like:

* lots of simpler conversations. (@chrisklus really likes the idea of this one)
* using `@field` instead of `@property` in JSDoc.
* Updating the code review checklist appropriately.
* Not going back to change old usages, just using this moving forward

Marking for dev meeting

**Comment by samreid** [comment]
The term "property" is fundamental to JavaScript object nomenclature, please see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Working_with_Objects and search for the term `property`.  This also shows in methods like `Object.hasOwnProperty` and `Object.getOwnPropertyNames`, `Object.defineProperty`.  As well as Proxy's `handler.deleteProperty()` and similar.  It seems nice to be able to use such a pervasive term properly within our team.

I think we are getting better at distinguishing between property and AXON Property in spoken and written text.  But if we want to discuss another way to address this problem:  the name Property came from Java where there was no name collision (or at least not as severe).  We kept the name when porting from Java to HTML5.  But we could rename Property to something else.  Imagine calling it an "Axon" or a "ValueContainer" or "Linkable" or "ObservableProperty" or "Observable" or "Datum" or your idea here.  But even if we come up with a better name, it would take a lot of effort to switch to it.  Looking forward to discussing it!

**Comment by zepumph** [comment]
Discussed in developer meeting today. 

* The team agreed with @samreid that `property` is foundational to javascript, and that we shouldn't replace that with `field`.
* That said, everyone will understand you if you say "field" instead of "property" in a github issue or something.
* No one is that interested in renaming AXON/Property. This would be a large change to the PhET-iO api. We do not think it is a problem for the PhET-iO api that it is named `PropertyIO`.

Closing
