### ISSUE TITLE
redundant stringTest in code-review checklist

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#112]
These 2 code-review items seem redundant. Collapse to one?

> - [ ] Are there any strings that are not being internationalized? (run with query parameter stringTest=x, you should see nothing but 'x' strings)
> 
> - [ ] Does the sim layout gracefully handle internationalized strings that are shorter than the English strings? (run with query parameter stringTest=X)

**Comment by ariel-phet** [comment]
@pixelzoom I actually think these could be removed. Such string tests are often done by the designer, and really this testing should be the responsibility of QA. These tests definitely get done during RC testing, but really we should move them to be done during the dev testing phase. (I have asked @KatieWoe to make this change in the dev testing template)

Generally our process has been a thorough dev test before code review so we are handing the reviewing developer a fairly "clean" and bug free sim to review. So I think this is not a responsibility that should be on the reviewing developer's plate.

Thanks for continuing to keep an eye out for where the code-review checklist can be streamlined!

**Comment by pixelzoom** [comment]
While I agree, I want to point out that as recently as 3 days ago, I did a code review and discovered string that had not been instrumented, see https://github.com/phetsims/wave-interference/issues/414#issuecomment-516079304.   So unfortunately I think that `stringTest` should be checked by the reviewer.  I'm going to combine the 'x' and 'X' tests and call it good for now.

**Comment by pixelzoom** [comment]
Done, closing.
