### ISSUE TITLE
revise phet-code-style.xml for WebStorm 2019.2 ?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#113]
On 7/26/19 in Slack dev-public, @samreid said:
> New WebStorm had an issue with whitespace in array brackets, I had to check that option in the formatter.

Are you referring to WebStorm 2019.2 ?

Does phet-code-style.xml need to be updated?

**Comment by pixelzoom** [comment]
I just updated to WebStorm 2019.2 and I'm seeing this problem, so I'm guessing that the answers are "yes" and "yes".

**Comment by pixelzoom** [comment]
In case anyone else needs to go hunting for this, "check that option in the formatter" refers to this checkbox in Preferences > Editor > Code Style > JavaScript:

![prefs](https://user-images.githubusercontent.com/3046552/62807492-c2ffcd80-bab2-11e9-8a68-fa9f1ccc3fa0.jpg)

**Comment by pixelzoom** [comment]
After checking the "Array brackets" checkbox and exporting phet-code-style.xml, here's the patch.  I did not push because there are changes that look suspect, or at least unfamiliar to me.
```
Index: ide/idea/phet-idea-codestyle.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- ide/idea/phet-idea-codestyle.xml	(revision 7c644fd3b5931f820aecf4640ebb7e86d0d94139)
+++ ide/idea/phet-idea-codestyle.xml	(date 1565382906925)
@@ -49,8 +49,8 @@
   <HTMLCodeStyleSettings>
     <option name="HTML_DO_NOT_ALIGN_CHILDREN_OF_MIN_LINES" value="200000" />
   </HTMLCodeStyleSettings>
-  <JSCodeStyleSettings>
-    <option name="SPACE_WITHIN_ARRAY_INITIALIZER_BRACKETS" value="true"/>
+  <JSCodeStyleSettings version="0">
+    <option name="SPACE_WITHIN_ARRAY_INITIALIZER_BRACKETS" value="true" />
     <option name="SPACE_BEFORE_FUNCTION_LEFT_PARENTH" value="false" />
     <option name="SPACES_WITHIN_OBJECT_LITERAL_BRACES" value="true" />
   </JSCodeStyleSettings>
```

**Comment by samreid** [comment]
I'm using IDEA 2019.2 and had to toggle the checkbox you mentioned.  I did not check in my changed style xml.

**Comment by samreid** [comment]
That is an odd diff, it seems it just adds `version=0` and a whitespace.

**Comment by pixelzoom** [comment]
Yes, I thought it was odd too.  I'm wondering if there's something weird about their HTML parser that requires a space before "/>".

**Comment by pixelzoom** [comment]
Labeling with meeting:developer for a PSA, and to see if we should change phet-code-style.xml.

**Comment by samreid** [comment]
+1 to change.  Only reason not to change is if it breaks things for 2019.1 or earlier users.  But in that case we should just ask them kindly if they can upgrade.

**Comment by pixelzoom** [comment]
Updated in above commit.  Announcement in Slack dev-public channel:

> PSA: phet-idea-code-style.xml has been updated for WebStorm 2019.2.  See https://github.com/phetsims/phet-info/issues/113

Closing.
