### ISSUE TITLE
How should required config fields be initialized?

### ISSUE THREAD

**Issue by Denz1994** [phetsims/phet-info#115]
During the discussion of the phet-software pattern on 09/30/19, it was brought up that default values for the required fields in a `config` object should be standardized. Currently, we have cases that opt into using ```null``` as a default value. See wave-interference [Scene.js](https://github.com/phetsims/wave-interference/blob/master/js/common/model/Scene.js)  as an example.

CM: Mentioned that ```null``` shouldn't be a default value because it may be a valid value in some cases. 
MK: Suggested using ```-1``` as a default.

We could also consider using  ```undefined``` as a default value.
The purpose of this issue is to settle on what the default value should be for these fields.

**Comment by pixelzoom** [comment]
To elaborate a bit more... The question is how (or whether) required `config` fields should be initialized.   There is currently no convention, and below are some examples in production code.  None of these examples meets PhET code standards.

(1) `AreaScreenView` provides a default value, but fails to verify that the client provided it.
```js
  function AreaScreenView( model, config ) {
    config = _.extend( {
      // {number} (required) - How many decimal places should be shown
      decimalPlaces: 0,
      ....
    }, config );
    assert && assert( typeof config.decimalPlaces === 'number' );
```

(2) `WaveInterferenceTiimerNode`  leaves initial value as `undefined`, and uses an assertion to implicitly document the existence of required fields.  The assertion expressions are incorrect, and documentation of the required fields in missing.

```js
      config = _.extend( {
        maxValue: 999.99,
        timerReadoutNodeOptions: {
          unitsNode: unitsNode
        }
      }, config );
      assert && assert( !!config.end, 'end is a required argument' );
      assert && assert( !!config.visibleBoundsProperty, 'visibleBoundsProperty is a required argument' );
```

(3) `WAVE_INTERFERENCE_SCENE/Scene` sets initial values to `null` to mean "required and not provided". This is not generally applicable, since `null` is often a valid field value.  Does not explicitly document which fields are required vs optional, so the reader has to somehow conclude that `null` means "required" and that `null` is not a valid value for any of the fields.

```js
 config = _.extend( {

        // Wave type
        numberOfSources: null, // {number} - 1 or 2
        waveSpatialType: null, // {WaveSpatialType}
        // etc...
      }, config );

      // @public (read-only) {WaveSpatialType}
      this.waveSpatialType = validate( config.waveSpatialType, { validValues: Scene.WaveSpatialType.VALUES } );

      // @public (read-only) {string} - units for this scene
      this.translatedPositionUnits = validate( config.translatedPositionUnits, VALID_STRING );

      // etc...
```

**Comment by pixelzoom** [comment]
More examples:

(4) `PROPORTION_PLAYGROUND/SceneNode` invents annotation `@required` to indicate which fields are required.  It uses `null` as the default value, which is not generally appropriate.  It tests for truthy, to identify value that have not been provided by the client. 

```js
  function SceneNode( scene, layoutBounds, config ) {
    config = _.extend( {
      sceneIcon: null, // {Node}, @required - shown in the SceneSelectionControls
      leftControl: null, // {SceneRatioControl}, @required
      rightControl: null, // {SceneRatioControl}, @required
      leftSwitchIcon: null, // {Node}, @required - Left side of the showBoth ABSwitch
      rightSwitchIcon: null, // {Node}, @required - Right side of the showBoth ABSwitch
      controlLocation: 'right', // 'right' or 'bottom', direction from the pickerContainer
      canCenterControlButton: true // Whether the control button can be centered when both left/right are shown
    }, config );

    assert && assert( config.sceneIcon );
    assert && assert( config.leftControl );
    assert && assert( config.rightControl );
    assert && assert( config.leftSwitchIcon );
    assert && assert( config.rightSwitchIcon );
```

**Comment by pixelzoom** [comment]
10/17/19 dev meeting:  To be discussed during continuation of options/config pattern at 10/28/19 core hours.

**Comment by Denz1994** [comment]
As discussed from design-patterns meeting 11/04/19:

The initialized value should be handled via a  function called `required( entry )`. The purpose is to ensure that an initial value is supplied into the required config field. The function should look something like this and would exist in `PhET-Core/required`:

```
// Validates that the passed in entry exists and returns that value.
required ( entry ){
      assert && assert( entry !== undefined);
      return entry;
}
```

Here is a typical use case:

```
  /**
   * @param {AreaModelCommonModel} model
   * @param {Object} config
   */
 class AreaScreenView extends ScreenView {
  constructor( model, config ) {
    config = merge( {

      // {number} How many decimal places should be shown
      decimalPlaces: required( config.decimalPlaces ),

      // {boolean} Whether we show options that let the user select the partial product style
      showProductsSelection: true,
     ...
    }, config );

    // Any further check should be handled after the config object
    assert && assert( config.decimalPlaces.additionalValidator( ) );
```

Please note that further validation should happen after the config option. Assigning myself to implement in PhET-Core.

**Comment by Denz1994** [comment]
`PhET-CORE/required.js` has been added. `Area-model-common/AreaScreenView.js` has been updated to include `required()` in the config object for the `decimalPlaces` field. This also means an additional assertion was removed for this field and a use case in `ProportionalAreaScreenView.js` needed to be corrected.

I'm sure there are plenty of other instances like this where adding `required()` will cause assertion failures.

**Comment by pixelzoom** [comment]
Thanks for doing this @Denz1994.

Re AreaScreenView.js...  I'm surprised that adding `required` for `decimalPlaces` is not failing CT. In yesterday's meeting, we identified 3 instances of subclass `ProportionalAreaScreenView` that were not providing `decimaliances`.  So the conclusion was that `config` should be changed to `options` for `AreaScreenView` constructor.    Recommended to create an issue and assign to @jonathanolson (responsible dev).

**Comment by pixelzoom** [comment]
Ah... I see that you did fix the assertion for ProportionalAreaScreenView.js.  But `AreaScreenView` constructor should be changed from `config` to `options`, and the `required` should be removed.

**Comment by Denz1994** [comment]
An issue referencing https://github.com/phetsims/phet-info/issues/115#issuecomment-549892958 has been created for AreaScreenView  and assigned to @jonathanolson. Closing this issue.
