### ISSUE TITLE
How should required config fields be documented?

### ISSUE THREAD

**Issue by Denz1994** [phetsims/phet-info#116]
As part of the discussion on the phet-software patterns on 09/30/19, we should standardize documentation for the required fields in a config object. Looking at the config object in [WaveInterferenceTimerNode.js](https://github.com/phetsims/wave-interference/blob/master/js/common/view/WaveInterferenceTimerNode.js), it was suggested by @pixelzoom, documentation for required fields may look something like this: 

```js 
config = _.extend( {

        // Required parameters
        // {function} end - end description
        // {function} visibleBoundsProperty - visibleBoundsProperty description

        maxValue: 999.99,
        timerReadoutNodeOptions: {
          unitsNode: unitsNode
        }
      }, config );
```

The following assertions would then read:

```js
assert && assert( config.end !== undefined, 'end is a required argument' );
assert && assert( config.visibleBoundsProperty !== undefined, 'visibleBoundsProperty is a required argument' );
```

Also, this pattern can be compared with the required field documentation in these examples:

- wave-interference [Scene.js](https://github.com/phetsims/wave-interference/blob/master/js/common/model/Scene.js) 
- area-model-common [AreaScreenView.js](https://github.com/phetsims/area-model-common/blob/master/js/common/view/AreaScreenView.js)
- Inverse-square-law-common [ISLCObjectNode.js](https://github.com/phetsims/inverse-square-law-common/blob/master/js/view/ISLCObjectNode.js)

**Comment by Denz1994** [comment]
Also, keep in mind we have a pattern for documenting required arguments in JSDoc. 

```js
@param {ISLCObject} object - the associated object's model within the sim
```

Can we adopt this style if we substitute ```@param``` for ```@required```?

**Comment by pixelzoom** [comment]
See https://github.com/phetsims/phet-info/issues/115#issuecomment-537092579 for examples of how config fields are documented in production code.

**Comment by pixelzoom** [comment]
Another point that was discussed in this meeting...  

* Should we indicate which fields are required, which fields are optional, or (unlikely) both?   This will probably be dictated by whether there are typically more required or optional fields in a `config`.   

* I was surprised to hear other developers say that they typically have more optional fields in a `config`, which leads me to wonder gif `config` is being appropriately.  For example, if there is only 1 required field and a config, and it is not tightly related to the optional fields, then  that required field should be a required constructor parameter.

**Comment by pixelzoom** [comment]
10/17/19 dev meeting:  To be discussed during continuation of options/config pattern at 10/28/19 core hours.

**Comment by Denz1994** [comment]
Following up from https://github.com/phetsims/phet-info/issues/115#issuecomment-549524381.

The documentation pattern will follow the below example:
```
// {number} How many decimal places should be shown
decimalPlaces: required( config.decimalPlaces )
```
Note that documentation is above the required config field and within the config object. The `required()` function is enough indication that this is a required field in the config object and no further distinction is required in the documentation.

**Comment by pixelzoom** [comment]
The conclusion in https://github.com/phetsims/phet-info/issues/116#issuecomment-549535230 should be rolled into the patterns doc, if it hasn't been already.

**Comment by Denz1994** [comment]
Documentation has been added in the above [commit](https://github.com/phetsims/phet-info/commit/799b13a56573cde57c91b022d1ad54478bf575bf). Closing this issue.
