### ISSUE TITLE
Guidelines for when to use config vs constructor parameters

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#117]
Related to #115 and #116.  From 9/30/19 core hours meeting, and in https://github.com/phetsims/phet-info/issues/116#issuecomment-537100926, I said:
> * I was surprised to hear other developers say that they typically have more optional fields in a `config`, which leads me to wonder if `config` is being appropriately.  For example, if there is only 1 required value, and it is not tightly related to the optional fields, then  that required field should be a required constructor parameter, not a `config` field.  

I also mentioned that the advantage of using required constructor parameters is that the `@param` annotation works nicely, and there is no issue of how to initialize the parameter.

So perhaps we need to revisit the guidelines on when to use `config` versus required constructor parameters.

**Comment by pixelzoom** [comment]
In 9/30/19 meeting, I also mentioned that I have yet to use the `config` pattern, and I suspect that it's being overused (or possibly abused) in order to avoid constructor parameters.

Below are the general forms of using `@param` vs config for required parameters. I see no advantage to using `config`, and would appreciate it if proponents of this pattern pointed out the advantage here.  The big disadvantage is that we need to invent a convention for specifying the initial value, type, and documentation for `config` fields -- something that is already provided (nicely) for constructor params. And we will like end up with a convention that is different for config and constructor params.

```js
/**
 * @param {type1} require1 - documentation1
 * @param {type2} require2 - documentation2
 ...
 * @param {type3} requireN - documentationN
 * @param {Object} [options]
 */
constructor( required1, required2, ..., requiredN, options ) {

  options = merge( {
    option1: defaultValue1, // {type1} documentation1
    option2: defaultValue2, // {type2} documentation2
    ...
    optionN: defaultValueN  // {typeN} documentationN
  }, options );
  
  ...
}

/**
 * @param {Object} config
 */
constructor( config ) {
  
  config = merge( {
    
    // required1 initial value, type, and documentation
    // required2 initial value, type, and documentation
    ...
    // requiredN initial value, type, and documentation
    
    option1: defaultValue1, // {type1} documentation1
    option2: defaultValue2, // {type2} documentation2
    ...
    optionN: defaultValueN  // {typeN} documentationN
     
  }, config );
  
  // required1 verification that a value was provided by caller
  // required2 verification that a value was provided by caller
  ...
  // requiredN verification that a value was provided by caller
}
```

I do think that a "config" object has a place.  But I think that its place is as a data structure for grouping tightly related information (not as a way to avoid constructor or method parameters), and should be used sparingly.  For example:

```
constructor( personalData,  startingSalary,  ... ) {

  personalData = merge( {
     // firstName
     // lastName
     // date of birth
     // address
  }, personalData );

  validate( personalData );

   ...
}
```

**Comment by pixelzoom** [comment]
10/17/19 dev meeting:  To be discussed during continuation of options/config pattern at 10/28/19 core hours.

**Comment by pixelzoom** [comment]
11/4/19 core hours discussion summary:
* config is useful. Use it judiciously and appropriately (area-model-common/Orientation is a good example)
* If your API requires a large number of parameters (regardless of whether they are required parameters or config fields) review your design to see verify that many parameters are necessary.
* I'll add something to the CRC related to the previous 2 points.

**Comment by pixelzoom** [comment]
I adde the following to [Best Practices](https://github.com/phetsims/phet-info/blob/master/doc/phet-software-design-patterns.md#best-practices):

> (5) Use `config` judiciously and appropriately. If your API has too many parameters, don't immediately reach for `config` as the solution. Review your API to understand why it has too many parameters, and possibly redesign.

@Denz1994 please review.  If this looks sufficient, feel free too close. If not, please suggest additional steps and assign back to me.

**Comment by pixelzoom** [comment]
Btw... I didn't add anything to the CRC, because all of the "best practices" should be followed, and the CRC already has:

> Are appropriate design patterns used? See phet-software-design-patterns.md. If new or inappropriate patterns are identified, create an issue.

So presumably PhET developers should be familiar with the options/config pattern.

**Comment by samreid** [comment]
@pixelzoom and @Denz1994 do we also want to schedule someone (or a chip-away issue) to look through the ~70 occurrences of `config ) {` and see which need attention?

**Comment by pixelzoom** [comment]
Not as a separate task. But good to do as part of the task of adding `required` function calls for required fields.

**Comment by Denz1994** [comment]
I fixed one instance in Area-model-common which was pretty straight forward (explained [here](https://github.com/phetsims/phet-info/issues/115#issuecomment-549863948)). However, instances such as this [example](https://github.com/phetsims/axon/issues/202) referring to Scene.js should be left to the responsible dev of the repo.

**Comment by pixelzoom** [comment]
👍 closing.
