### ISSUE TITLE
bad link to QA Book in sim_new_checklist.md

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#118]
[sim_new_checklist.md](https://github.com/phetsims/phet-info/edit/master/checklists/sim_new_checklist.md) contains this item:

> - [ ] Main screenshot (read [this](https://github.com/phetsims/QA/blob/master/doc/qa-book.md#screenshots))

The link goes to `qa-book.md#screenshots`, which (as far as I can tell) does not exist.

Not sure who the appropriate person to assign this to is, so I'll start with @KatieWoe, since it involves the QA Book.

**Comment by KatieWoe** [comment]
I just clicked the link and it works fine for me.

**Comment by pixelzoom** [comment]
@KatieWoe what browser are you using?

On Safari 13.0.1, I see "Screenshots" section (if I don't blink) and then it immediately scrolls to the section shown below.  Then I have to scroll down half-page to see the "Screenshots" section.

<img width="1084" alt="screenshot_1574" src="https://user-images.githubusercontent.com/3046552/66420635-79086a80-e9c3-11e9-99c1-e44ed5f2da26.png">

**Comment by pixelzoom** [comment]
Works fine for me on macOS + Chrome, and macOS + Firefox.

**Comment by KatieWoe** [comment]
Win 10 Chrome

**Comment by KatieWoe** [comment]
It sounds like a github problem to me, but I can look a bit more in depth when the repo is less full.  Doesn't seem to be more than an inconvenience right now.

**Comment by pixelzoom** [comment]
All of the links in [code_review_checklist.md](https://github.com/phetsims/phet-info/blob/master/checklists/code_review_checklist.md) function correctly, as do most of the links in the QA book.  So it's not a general problem with links.    

The links that are broken in the QA book appear to be the 3 links that start with "Screenshot":

**Screenshots* https://github.com/phetsims/QA/blob/master/doc/qa-book.md#screenshots
**Screenshots on Chrome** https://github.com/phetsims/QA/blob/master/doc/qa-book.md#screenshots-on-chrome
**Screenshots on Firefox** https://github.com/phetsims/QA/blob/master/doc/qa-book.md#screenshots-on-firefox

Anyway...  I don't think this is worth any more time.  Just beware of .md links on Safari.

Closing.
