### ISSUE TITLE
New standard "design:interviews" label

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/phet-info#12]
@mattpen can you make a new standard label across repos

"design:interviews" color #D4A0FB

**Comment by ariel-phet** [comment]
@mattpen from @arouinfar 

> I noticed the new label has been added, thanks! It looks like there’s a problem with the colon, though. It’s being represented by %3A, which is the URL encoding for a colon.

Probably should fix that :)

**Comment by mattpen** [comment]
@ariel-phet - The new label should be pushed to all repos in the correct state now.

**Comment by ariel-phet** [comment]
@mattpen looks good, closing, thanks!
