### ISSUE TITLE
Clean up references to the PhET Development Overview google doc

### ISSUE THREAD

**Issue by samreid** [phetsims/phet-info#120]
In https://github.com/phetsims/phet-info/issues/94 we converted the PhET Development Overview from a google doc to a MD file.  In order to complete this transition, we should take steps like the following:

* Change the content of the google doc to basically be a pointer to the MD file, http://bit.ly/phet-html5-development-overview and http://bit.ly/phet-development-overview, I'm not sure if there are others
* Remove references to the google doc such as this line in the MD file.  I'm not sure if there are other references.  `This document is also available at http://bit.ly/phet-html5-development-overview. `
* Do we "own" those bit.ly references, and can change their targets to point to the MD file instead of the Google Doc?

Labeling for developer meeting to see if there are any other steps to complete, and to prioritize/assign.

**Comment by pixelzoom** [comment]
FYI, just about every implementation-notes.md that I've written contains a link to the Google doc. For example, see https://github.com/phetsims/gas-properties/blob/master/doc/implementation-notes.md.

**Comment by samreid** [comment]
I'll work on these steps.  We decided we do not update the bit.ly references, but we will update the contents of those pages.

Also a reminder to double check on the following:
* simula rasa
* the google group, make sure the description on the google group is updated.

**Comment by oliver-phet** [comment]
Oops, looks like I can't update that link. @chrisklus or @mattpen can you update the 'PhET Development Overview' to link to https://github.com/phetsims/phet-info/blob/master/doc/phet-development-overview.md

**Comment by mattpen** [comment]
This was fixed on the website in cd0f1b948df3c3e1929ab53a0871515f3c3c9b14.  This will be deployed within the next week or so.

**Comment by samreid** [comment]
I updated all references to the bit.ly link to point to the MD file.  The last step is to replace the contents of http://bit.ly/phet-development-overview with contents that match http://bit.ly/phet-html5-development-overview.  However, I do not have write permission for http://bit.ly/phet-development-overview.  @oliver-phet or others, do you know who can edit this google doc?  I also sent an edit request, but I'm not sure who it went to.

**Comment by oliver-phet** [comment]
http://bit.ly/phet-development-overview has been updated.

**Comment by pixelzoom** [comment]
@samreid please edit your first post in the "Welcome to the Developing Interactive Simulations in HTML5 Google Group!" thread, https://groups.google.com/forum/#!topic/developing-interactive-simulations-in-html5/O1cJem3VW18.

**Comment by samreid** [comment]
@pixelzoom and I discussed this on slack today.  I replied with the new URL, locked replies and “topic”, and deleted the original post.

Anything else for this issue?

**Comment by pixelzoom** [comment]
Looks good, I can't think of anything else that needs to be updated.  Thanks for handling this. Closing.
