### ISSUE TITLE
When should we use default/named/destructured parameters?

### ISSUE THREAD

**Issue by samreid** [phetsims/phet-info#122]
As an extension of https://github.com/phetsims/phet-info/issues/117, it would be good to identify when it is appropriate to use default, named or destructured parameters.  For instance, see the example at the bottom of this page: https://examples.dev/articles/javascript-named-parameters/

```js
const formatDate = ({day = 0, month = 0, year = 2018} = {}) => {
  return `${day}/${month}/${year}`;
};

// Just pass the parameters you need.
formatDate({day: 1, month: 2, year: 2018});
formatDate({month: 2, year: 2018});
formatDate({year: 2018});
formatDate({});
formatDate();
```

This strategy has the desirable behavior that the defaults are not invoked unless necessary (this is a flaw with our current options scheme).

```js
// current scheme: invokes `new Person('alice')` even though it is never used
options = merge({person: new Person('alice')},person: bob);

// using destructuring to simulate named/default parameters. Doesn't invoke `new Person('alice')`
const myFunction = ({person = new Person('alice')} = {}) => {...};
myFunction({person=bob};
```

Assigning to @Denz1994 for initial review and discussion.

UPDATE: Also labeling for developer meeting while the topic is fresh in our minds.

**Comment by Denz1994** [comment]
>This strategy has the desirable behavior that the defaults are not invoked unless necessary 

If this behaves like a safeguard to ensure option parameters are invoked only if they're used, then it would be useful. I’ve never used this approach before and would want other devs' opinions on this.

**Comment by pixelzoom** [comment]
I haven't had a need/desire to use this feature of JS, so I don't have input on when it's appropriate. 
I don't think it's a replacement for `merge` and PhET's options/config pattern.  

The `myFunction` example in https://github.com/phetsims/phet-info/issues/122#issue-517987270 is buggy.  The usage should be:

`myFunction( { person: bob } );`

**Comment by samreid** [comment]
@zepumph pointed out this pattern makes it difficult to pass through options to a supertype.  It could be done by passing `{day:day,month:month,year:year}`.

@pixelzoom said he is not opposed to developers using this pattern where it is appropriate.

We decided to close and not investigate this as a replacement for our options pattern.
