### ISSUE TITLE
How to annotate "future/potential improvements" to code other than TODO

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/phet-info#123]
@jonathanolson noted that many of his TODO comments are in the category of "notes to self that might be future improvements to consider"

We should come up with a different convention for such comments in code to disambiguate them from TODOs which seem to carry the weight of "this should be done"

**Comment by jonathanolson** [comment]
Some examples of old TODOs or categories:

There are a number of places where simplicity for design/implementation was chosen over performance, but there are notes on essentially "if this is ever a performance hot spot, it can probably be improved by doing X". The implicit assumption is "if it's not a problem, don't do anything", and I don't think they're worth an issue:

CanvasBlock's setSizeFitBounds:
```js
//OHTWO TODO PERFORMANCE: see if we can get a speedup by putting the backing scale in our transform instead of with CSS?
```

or notes that things could be investigated/tuned (toggling the flag based on platform could increase performance in this case):
```js
  // TODO: change this based on memory and performance characteristics of the platform
  const keepSVGImageElements = true; // whether we should pool SVG elements for the SVG rendering states, or whether we should free them when possible for memory
```

Then there are the true "potential better ways to do things in incredibly complicated code", which have a high likelihood of never being used:

```js
//OHTWO TODO: only strip out invisible Canvas drawables, while leaving SVG (since we can more efficiently hide
// SVG trees, memory-wise)

//OHTWO TODO: we are probably missing syncTree for shared trees properly with pruning. investigate!!

//OHTWO TODO: actually create the proper shared cache drawable depending on the specified renderer
// (update it if necessary)
```

It seems a LOT of the TODOs fall into the "they can be handled/removed/changed to remove it", so a single pass could quickly remove a lot of them, e.g.:

```js
// TODO: replace with a 'remove' function call
this.relativeTransformListeners.splice( _.indexOf( this.relativeTransformListeners, listener ), 1 );
```
(where we have PHET_CORE/arrayRemove).

**Comment by jessegreenberg** [comment]
What if we use TODOs to signify things that need to be done and NOTEs to annotate special docs and flag non-critical inprovements.

**Comment by ariel-phet** [comment]
MK comments that he uses NOTE for "potential pitfall" and others seem to also follow this general paradigm

However, team is generally comfortable with expanding the use/meaning of NOTE to include potential incremental improvements.
