### ISSUE TITLE
create a "delete repo" checklist

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#124]
Slack dev-public channel on 12/10/19:

John Blanco 4:08 PM
I just archived the phet-io-wrapper-sonification repo.  For details, see https://github.com/phetsims/phet-io-wrapper-sonification/issues/93.  Please delete your local copy. Also, does anyone know whether I need to do anything to let CT and/or build-server know that this repo is no longer needed?  Keeping it around shouldn't hurt anything for those processes, so it's more just a matter of cleanliness.

Chris Malley 4:45 PM
Sorry, no idea. We have a "new repo" checklist, https://github.com/phetsims/phet-info/blob/master/checklists/new_repo_checklist.md.  It might be nice to also have a "delete repo" checklist.
👍 1

**Comment by jonathanolson** [comment]
- Don't remove repos that are listed as dependencies of any published simulation. Ideally don't remove repos which would prevent us checking out old versions of sims (don't mess with the bisection). If not confident about this, bring it to a dev meeting
- Don't remove repos where we've recorded otherwise useful information that is linked to
- The repo should be removed from active-repos, ideally a few minutes before archiving/deleting (so automated processes don't try to pull it)
- In general, it shouldn't break much otherwise
- If people worry about empty rows in CT, just restart CT

**Comment by jbphet** [comment]
+ We should be clear about whether a repo is being deleted or archived.  There should be advice at the beginning as to which one to do.  It can probably be the same checklist to cover either, with portions that say something like, "if this is being deleted do x, but if archived do y".
+ Let the other developers know that they should delete their local copy and let you (the person doing the deletion) know if any related issues crop up.
+ We should explicitly state whether something needs to be done to delete the directory from aqua, build-server, and phettest, or whether these directories get automatically deleted, or just hang around forever with no consequences
+ Update the README file if archiving (doesn't matter if deleting)

**Comment by jbphet** [comment]
@ariel-phet assigned this to @jonathanolson and me to input our initial thoughts on what this checklist should contain.  We've done that, so I'm sending it back to him for prioritization and assignment to do the actual work.

**Comment by pixelzoom** [comment]
Since this is assigned to @ariel-phet "for prioritization and assignment to do the actual work", and it's not clear what further input is needed at developer meeting, I'm going to remove the developer meeting label.

**Comment by pixelzoom** [comment]
On second thought... Keeping this labeled for developer meeting so we can wrap it up.

**Comment by mattpen** [comment]
Dev Meeting 1/2:  This would be easier to evaluate in final form as an .md file.  No one brought up additional points for the checklist.

@ariel-phet will compile the .md file.

**Comment by ariel-phet** [comment]
I did my best to use the above to start a draft checklist, but it needs some fleshing out. Remarking for dev meeting 

https://github.com/phetsims/phet-info/blob/master/checklists/delete_repo_checklist.md

**Comment by samreid** [comment]
We reviewed it and made changes, closing.
