### ISSUE TITLE
Code style question: can line comments break up conditionals?

### ISSUE THREAD

**Issue by zepumph** [phetsims/phet-info#125]
I slacked this message, but it is late on a Friday, and may be better as an issue:

I have had this discussion with @samreid before, but is there a developer consensus over if we allow comments in between conditional lines. For example would the following pass code review or does it need to have the line comments inside each else if? https://github.com/phetsims/molarity/blob/067a4d908fa9a06fddc1d131a5140ff3035bdfcf/js/molarity/view/molarityAlertManager.js#L91

>```js
>    alertSolutionQuantityChanged( describer ) {
>
>      // A special alert is read out if the solution is at max concentration without any precipitate.
 >     if ( !this.solution.isSaturated() && this.solution.atMaxConcentration() ) {
>        this.alertMaxConcentrationNotSaturated();
 >     }
>
>      // alert when the solution has just become saturated, or has just become unsaturated.
 >     else if ( this.concentrationDescriber.saturationValueChanged ) {
 >       this.alertNewlySaturated();
>      }
>
>      // alert when there is no solute in the solution (so the solution is just water)
>      else if ( !this.solution.hasSolute() ) {
>        this.alertNoSolute( this.useQuantitativeDescriptionsProperty );
>      }
>
>      // quantitative alerts (when the 'solution values' checkbox is checked)
 >     else if ( this.useQuantitativeDescriptionsProperty.value ) {
  >      this.alertSliderQuantitative();
 >     }
>
>      // qualitative alerts (when the 'solution values' checkbox is unchecked)
>      else {
 >       this.alertSliderQualitative( describer.getStringsFromSliderChange(), describer.getRegionChanged() );
>      }
 >   }
>```

I personally like this, but potentially it is not allowed. I'd like to know if this line commenting strategy is against coding conventions, or developer discretion.

**Comment by pixelzoom** [comment]
We've discussed before (not that we shouldn't do it again). Consensus that I recall was:

```js
// comment
if ( expression ) {
  // comment
  ...
}
else if ( expression ) {
  // comment
  ...
}
else {
  // comment
  ...
}
```

I'm not wild about:

```js
if ( expression ) {
  ...
}
// comment
else {
  ...
}
```

... because it feels disjointed, and too easy to accidentally stick something after if (...) {...}.   And not to sound like an old curmudgeon, but I've never seen that in practice, or even proposed, outside of PhET.

In Slack, @samreid mentioned this example (which seems to have a syntax error):

```js
if (something){
  something();
} else if (something else) {
//some explanation about the else
else body()
}
```

Not related to where comments go.  But I don't think we should allow `} else` on the same line, because it  violates phet-idea-codestyle.xml and will be reformatted by WebStorm/IntelliJ.

**Comment by samreid** [comment]
In my example, I didn't intend `else body()` to mean the `else` keyword, I should have put it as `elsebody()` and likewise I didn't mean to ascribe meaning to the formatting.  Sorry for the miscommunication!  Basically the consensus I recall is the same as @pixelzoom described at the top of https://github.com/phetsims/phet-info/issues/125#issuecomment-565667262

**Comment by zepumph** [comment]
From dev meeting today, we decided to go with the following, I will add to the style guidelines:


1. Comments above the first `if` in a conditional should be about the entire conditional, not just the if statement
2. Comments should not break up sections of the conditional.
3. If a comment is needed to describe a single block of the conditional, then add that comment just inside the block (no space between the `if`/`else if`/`else` and the comment), with a space below it as to not be confused with a comment about logic below.

Here is an example (with numbered comments relating to the guidelines above):

```js

// (1) Comment about the reason to split on peppers were pickled.
if( peterPiperPickedAJarOfPickledPeppers ){
  // (3) if we want to explain what this `if` statement is about
  
  peterAlsoHasBrine();
}
else {
  
  // documentation about why we have no peppers. This is about the next line of code, and not the "else as a whole block."
  peterHasNoPeppers();
}
```

**Comment by zepumph** [comment]
Done. Closing
