### ISSUE TITLE
location vs position

### ISSUE THREAD

**Issue by samreid** [phetsims/phet-info#126]
When do we use position vs location?  Some cases seem haphazard

Jesse Greenberg 3:14 PM
> Good question, ive wondered the same and seen both used throughout. Hopefully sims are consistent in which one they use.

Chris Malley 3:46 PM
> Vector Addition had an interesting spin on "location" vs "position" that I had not encountered in other sims (and which I am not advocating). Rather than change it, I chose to document it in implementation-notes.md:
>  "for vectors, _position_ or _point_ refers to model coordinates, while _location_ refers to view coordinates"
> I believe that I've (consistently?) used "location" in my sims (e.g. locationProperty), regardless of whether it's model or view.  My thinking is that "location" means "where something is located", while "position" can sometimes mean both location and orientation, i.e. "a particular way in which someone or something is placed or arranged." (edited) 
As for consistency...  Searching for Property definitions, case insensitive.... PhET code has 55 occurrences of "locationProperty =",  146 occurrences of "positionProperty ="

This came up during https://github.com/phetsims/gas-properties/issues/170 when I noticed that some stopwatches used `locationProperty` and some used `positionProperty`.

**Comment by pixelzoom** [comment]
> Some cases seem haphazard ...

> I noticed that some stopwatches used `locationProperty` and some used `positionProperty`. ...

Please identify.

**Comment by samreid** [comment]
For example, https://github.com/phetsims/energy-skate-park/blob/d1a734a7021646104afc2af1f95e7de97625db8f/js/energy-skate-park/common/view/EnergySkateParkTimerNode.js refers to `timerPositionProperty` but https://github.com/phetsims/gas-properties/blob/dc8cbc064dcbf5089ecfddb758e45fa9524e834b/js/common/model/Stopwatch.js

By the way, I'm in progress working through https://github.com/phetsims/gas-properties/issues/170 and we'll have opportunities to fine tune the naming after initial commits.

**Comment by jonathanolson** [comment]
Most notably, DragListener has `locationProperty` right now.

**Comment by pixelzoom** [comment]
Personally, I don't care if we standardize on this. I'd be happy to leave it up to developer discretion as to whether to use 'location' or 'position'.   I realize that creates a bit of inconsistency in the PhET-iO API, but I think the cost to clients will be significantly less that the cost for PhET to standardize.  My 2 cents...

What I do care about is arbitrary changes to existing code based on personal preference, like this one in StopwatchNode:

```js
   this.positionProperty = new Vector2Property( options.location, {
```

This was originally `locationProperty`. Now we have both `positionProperty` and `options.location` because the option didn't get renamed.  There was no need to change it, certainly not until this issue was discussed.

**Comment by pixelzoom** [comment]
12/19/19 dev meeting:

* Consensus is to use "position" uniformly. 
* First priority is to change "location" to "position" as its exposed in the PhET-iO API.
* Developers at their discretion can eagerly change sims that they are responsible for.
* @samreid will add assertion to PhET-iO to prohibit "locationproperty"  (case insensitive), assertion case be removed in the future if we have a legitimate need for "location".

Assigning to @samreid to review existing cases and decide on whether we need an assertion.

**Comment by samreid** [comment]
The renaming for balloons and static was more invasive than I expected it to be, so I consulted with @jessegreenberg about a few aspects.

(1) cases like `BASEDescriber` where the positions are not cartesian, but more qualitative, like:

```js
  const POSITION_DESCRIPTION_MAP = {
    AT_LEFT_EDGE: {
      UPPER_PLAY_AREA: landmarkLeftEdgeString,
      CENTER_PLAY_AREA: landmarkLeftEdgeString,
      LOWER_PLAY_AREA: landmarkLeftEdgeString
    },
```
And @jessegreenberg confirmed that our decision to use position instead of location did not just apply to cartesian coordinates, but should also apply to cases like this.  

(2) we confirmed that even though a11y key and string placeholder names were changed, no a11y text values were changed, so this shouldn't change anything for the end user.

Fuzzing and linting was clear, so I'll commit this part.

**Comment by pixelzoom** [comment]
Hmmm... I hadn't thought about translated strings (or their keys).  Searching for case-insensitive occurrences of "location", I find 233 in *strings*.json, 75 in *A11yString.js.  What do you propose to do about these?

**Comment by jbphet** [comment]
I was going to respond to @pixelzoom and request that string keys not be changed, but I looked at this a bit and all occurrences of "location" seem to be in translations with no corresponding string in the English file.  I'm not quite sure what's going on here.  There's a commit - https://github.com/phetsims/energy-skate-park-basics/commit/3e689653b2a2b2299d0ec933ff3427a593079040 - where the strings with "location" in their keys were removed from the strings file, but how did they end up getting translated?  Rosetta is specifically designed to only present to the user strings that are used in the sim.

Perhaps the bottom line is this - if @samreid or @jessegreenberg can confirm that these strings are not used in the currently live version of the sim, nor in the master version, the string keys in question in the translated string files can be changed, left alone, or removed from the translations files, since they will have no effect on the translated sim.

**Comment by pixelzoom** [comment]
I attempted to change "location" to "position" in Natural Selection.  It's a new sim, so I figured it would be appropriate to address immediate.  I ended up introducing a bug in DataProbeDragListener, reverted in the commit above. DataProbeDragListener is a subclass of DragListener, which has option `locationProperty`.   So until this is addressed for common code, I'm stuck with either continuing to use `locationProperty` in some Natural Selection code, or having something ugly like this in DataProbeDragListener:

```js
class DataProbeDragListener extends DragListener {

  constructor( positionProperty, ..., options ) {
    ....
    options.locationProperty = positionProperty;
    super( options );
    ....
  }
```

I'm not wild about either of these alternatives.

Assigning to @ariel-phet and putting this back on the developer meeting schedule to discuss when common code will be converted.  It's been 19 days since we decided to make this change, and nothing has been done. What's the plan?

**Comment by pixelzoom** [comment]
Here's what needs to be touched.  Common-code classes should be done first and (imo) asap. (See my DragListener experience in https://github.com/phetsims/phet-info/issues/126#issuecomment-571789198.). Common-code changes will result in sim changes when "location" is part of the API (option name, method name, etc.)

Common-code classes:
- [ ] scenery/DragListener
- [ ] scenery/DragListenerTests
- [ ] scenery/KeyboardDragListener
- [ ] scenery-phet/ConductivityTesterNode
- [ ] scenery-phet/StopwatchNode
- [ ] scenery-phet/MovementDescriber
- [ ] scenery-phet/ComponentsScreenView
- [ ] scenery-phet/MovableDragHandler

Sim repositories
- [ ] acid-base-solutions @pixelzoom 
- [ ] area-model-common @jonathanolson 
- [ ] balancing-act @jbphet 
- [ ] beers-law-lab @pixelzoom 
- [ ] bending-light @samreid 
- [ ] build-a-molecule @jonathanolson 
- [ ] capacitor-lab-basics @denz1994
- [ ] charges-and-fields @jonathanolson
- [ ] collision-lab @veillette 
- [ ] energy-skate-park @jessegreenberg
- [ ] equality-explorer @pixelzoom 
- [ ] example-sim @pixelzoom 
- [ ] fractions-common @jonathanolson
- [ ] friction @zepumph
- [ ] function-builder @pixelzoom 
- [ ] gas-properties @pixelzoom 
- [ ] graphing-quadratics @pixelzoom 
- [ ] inverse-square-law-common ??
- [ ] models-of-the-hydrogen-atom @pixelzoom 
- [ ] molecule-polarity @pixelzoom 
- [ ] molecules-and-light
- [ ] natural-selection @pixelzoom 
- [ ] number-play @chrisklus
- [ ] pendulum-lab @jonathanolson
- [ ] ph-scale @pixelzoom 
- [ ] projectile-motion @jbphet
- [ ] unit-rates @pixelzoom
- [ ] vector-addition @pixelzoom 
- [ ] wave-interference @samreid

**Comment by pixelzoom** [comment]
More common-code, these have non-Property occurrences of "location".

- [ ] DOT/Bounds2
- [ ] PHETCOMMON/SphereBucket
- [ ] SCENERY_PHET/BracketNode
- [ ] SCENERY_PHET/Drawer 
- [ ] SCENERY_PHET/FaceWithPointsNode
- [ ] SCENERY_PHET/MeasuringTapeNode
- [ ] SCENERY_PHET/StopwatchReadoutNode
- [ ] SCENERY_PHET/BorderAlertsDescriber
- [ ] SCENERY_PHET/PlateChargeNode
- [ ] SCENERY/AnimatedPanZoomListener
- [ ] SUN/DemoScreenView

**Comment by pixelzoom** [comment]
@ariel-phet My work here is done. With the exception of `locationProperty` option passed to `DragListener`, all of my sims have been fully converted to "position".   I also handled a big chunk of the common code changes.  

It would be nice if `DragListener` were revised soon, so that we don't keep creating more `locationProperty` occurrences.

**Comment by pixelzoom** [comment]
I've taken care of `DragListener`, got @jonathanolson's blessing on Slack.

**Comment by pixelzoom** [comment]
I've taken care of `DragListener`, got @jonathanolson's blessing on Slack.

**Comment by jessegreenberg** [comment]
Reviewed during dev meeting 1/9/20: We are going to address the common code cases quickly, responsible devs have been assigned. The can chip away the sim cases with less urgency.

**Comment by pixelzoom** [comment]
1/16/20 dev meeting:

Re common code: @Denz1994 will look at SphereBucket soon.  @jessegreenberg and @zepumph are unlikely to get to their assignments until after a11y conference.

Re sim code: Developers are free to chip away at their sims at any time.

**Comment by Denz1994** [comment]
I addressed phetCommon/SphereBucket. This seemed like a straight forward change because all of the ```location``` instances were private to ```SphereBucket.js``` or in docs. This was as tested in BAM and BAA, but I'll keep an eye on ct.

**Comment by zepumph** [comment]
- [ ] When all of this is said and done, it would be nice to add some bad text to this, perhaps "locationProperty" will be an easy one.

**Comment by pixelzoom** [comment]
As noted in https://github.com/phetsims/phet-info/issues/126#issuecomment-571794940, this change is not limited to Property names.  So "locationProperty" (even case insensitive) is not sufficient for bad-text.js.

**Comment by zepumph** [comment]
No certainly not complete, but it would be good to try to get as much of this covered automatically as possible, and it seems  like the most common "api leaking" elements are Property instances.

**Comment by jessegreenberg** [comment]
SCENERY/AnimatedPanZoomListener done in above commit. That completes the common code list in https://github.com/phetsims/phet-info/issues/126#issuecomment-571794940

**Comment by pixelzoom** [comment]
Thanks @jessegreenberg. Removing high-priority label, since all common code is done.  This is now "chip away" for sims.

**Comment by zepumph** [comment]
I will investigate two potential lint rules to see how they feel:
1. "locationProperty" as bad text
2. "location" as bad text when part of code (not comments).

**Comment by ariel-phet** [comment]
@SaurabhTotey is going to try to finish these off

**Comment by pixelzoom** [comment]
@ariel-phet asked me give @SaurabhTotey a quick walkthrough of what I did, so he can follow the pattern and finish off the remaining chip aways.  We're going to discuss 1/28/20 on Zoom.  

Here's an overview of the process I used:

Look for occurrences of "location" that refer to the position of something in 2D or 3D space.  These should be changed to "position".  There may be other occurrences (like the "location" of a file) that you should not change.  Also don't change anything that is part of some non-PhET API, for example `window.location`. 

Here's the process for each repo:

* Do a case-insensitive string search for "location".  
* Inspect and change occurrences, using string replace.
* Test the sim in phetmarks as you go.
* Before committing... If the sim appears in perennial/data/phet-io/ then run `grunt update` and test in Studio, in case there were any changes to the PhET-iO API.

**Comment by pixelzoom** [comment]
@SaurabhTotey we discussed this, but I'll note here...   If you want to check whether a repository is used by other sims, then search for its name in *-config.js.  For example, search for "fractions-common" indicates that it's used by build-a-fraction, fraction-matcher, fractions-equality, fractions-intro, fractions-mixed-numbers, and number-play.  And you'll need to hit all of those repos at the same time.

**Comment by Denz1994** [comment]
As discussed in dev-meeting on 02/20/20:
@SaurabhTotey will be taking care of the remaining sim related repos.

**Comment by SaurabhTotey** [comment]
I believe the remaining sims have had their relevant usages of 'location' replaced with 'position'. Please let me know if there is anything else I should do. In the meantime, I will unassign myself from this issue.

**Comment by pixelzoom** [comment]
Looking good @SaurabhTotey, thanks for taking this on.

I fixed a bunch more that were in comments, see above commits. 

It also looks like there has been new code created using "location".  For example @jbphet in `NumberLineOperationNode` used `operationStartLocation` and `operationEndLocation` (I fixed these in the above commits).  Should we do anything to prevent this? 

Assigning back to @samreid, who seemed to feel strongly about this issue. My opinion is that this issue has had a high cost:benefit ratio, and is almost impossible to enforce via automation.

**Comment by zepumph** [comment]
An easy one may be to add `locationProperty` to the bad-text lint rule. Otherwise I agree with you.

**Comment by pixelzoom** [comment]
Yes, adding `locationproperty` (case insensitive) to bad-text.js would probably address 99% of the PhET-iO naming consistency concerns.

**Comment by samreid** [comment]
I added a bad-text rule and a checkbox to the code review checklist.  Thanks for all your work here @SaurabhTotey and @pixelzoom and everyone else that helped.  It seems ready to close, but please reopen if there's anything else.
