### ISSUE TITLE
Should boolean attributes typically have an "is" or "has"-style prefix?

### ISSUE THREAD

**Issue by samreid** [phetsims/phet-info#127]
From https://github.com/phetsims/gas-properties/issues/170#issuecomment-566735033:

@pixelzoom said:

> (2) I see that visibleProperty has been changed to isVisibleProperty. I get it that the "is" prefix is a reasonable convention for boolean Properties. But scenery uses visibleProperty, and it's used everywhere, so I'm very much in the habit of reaching for visibleProperty. Another example is enabledProperty, also used everywhere. So there's a trade-off here, and I don't think that changing to isVisibleProperty comes down on the "net gain" side of that trade-off. Unless you're going to change visibleProperty everywhere, I think it's better to stick to what is used (almost?) everywhere.

I replied:

> It seemed odd to have visibleProperty adjacent to isRunningProperty in Stopwatch.js. I also recalled a more recent consensus that boolean attributes and properties should typically begin with is, but I do not know where to find a paper trail on this, or whether we have cited an exception for visibleProperty. Let's discuss further.

Our discussion of this should also cover naming of phet-io tandems.  Consensus should be noted in the appropriate place (not sure if it should be the code review document or patterns document, or elsewhere).

**Comment by pixelzoom** [comment]
This only makes sense as a "convention" if we're going to do it everywhere.  Are you prepared to locate and rename boolean Properties and their associated boolean options everywhere? What are you going to do about singular vs plural ("is" vs "are")? 

I've heard zero complaints about `visibleProperty`, `pickableProperty`, and `enabledProperty` (the most common 3) in PhET-iO design meeting.   No one seems to have had a problem understanding what they mean. So I'm wondering what the payoff of this convention is here, other than adhering to convention.

Imo, I think that "is" and "has" are only truly useful (necessary?)  if the meaning of the variable is ambiguous.  So I would leave that up to developer discretion, and encourage sticking to conventional names (like `visibleProperty`) whenever possible.

Specific to what I've been working on lately... Natural Selection has numerous boolean Properties that are already very verbose, and I've been following the scenery/sun convention for `visibleProperty` and `enabledProperty`:

```
brownFurVisibleProperty
whiteFurVisibleProperty
straightEarsVisibleProperty
floppyEarsVisibleProperty
shortTeethVisbileProperty
longTeethVisibleProperty
wolves.enabledProperty
limitedFood.enabledProperty
```

I really don't want to make these more verbose.

And I really don't want to have to decide which of these to use for `straightEarsVisibleProperty`:

```
straightEarsIsVisibleProperty
straightEarsAreVisibleProperty
isStraightEarsVisibleProperty
areStraightEarsVisibleProperty
```

These two are also difficult:

``js
wolves.enabledProperty
limitedFood.enabledProperty
```

`enabledProperty` is defined in (and instrumented by) the superclass `EnvironmentalFactor`. Is `wolves.isEnabledProperty` OK?  Or do I need to jump through hoops to make it `wolves.areEnabledProperty`.

**Comment by mattpen** [comment]
`is` and `are` aren't the only verbs that could be used with a boolean variable.  `should` is valid in some cases too, although maybe not specifically for properties.  This is used in React and iOS code.  I would argue that there shouldn't be a convention because sometimes these verbs are helpful and sometimes they aren't.

**Comment by pixelzoom** [comment]
12/19/19 dev meeting:

* use "is", "has",..., prefix when the meaning is ambiguous, or at developer discretion
* for common properties like "visible", "pickable", "enabled" that have a convention, stick to the convention
* @samreid pointed out that there are ~190 cases of "isVisible".  Let's hit these (and similar cases) as they need to be adjusted for PhET-iO

**Comment by samreid** [comment]
@pixelzoom what should `Node.isVisible()` be named?  Should it be left as `Node.isVisible()`?

**Comment by pixelzoom** [comment]
I'd probably leave is `Node.isVisible()`.  But I defer to @jonathanolson.

**Comment by samreid** [comment]
In my opinion, `Node.isVisible` is a clear and great name.  @pixelzoom already said he would probably keep that as it is.  So I suspect this issue can be closed.  @jonathanolson feel free to reopen if you feel differently.
