### ISSUE TITLE
When should an option not be overrideable?

### ISSUE THREAD

**Issue by samreid** [phetsims/phet-info#128]
From https://github.com/phetsims/gas-properties/issues/170#issuecomment-566840809

@pixelzoom said:

> - [ ] This `merge` call in `Stopwatch` allows the caller to override `tandem`.  Do we really want to allow that?  It will be awkward to make timeProperty’s `tandem` appear like its a sub-element of `options.tandem`.  And is there really a need, or is standardization better here?  Recommended to forbid overriding `tandem` by adding `assert && assert( !options.timePropertyOptions.tandem, ... )` before this `merge` call.

We have run into this question a number of times before, but I do not recall the consensus or rule of thumb for when options in general should not be overridable.

Here's a regular expression I used to search for examples of where an options value is set directly: `options\..*\=\s`, and here is one straightforward example we can use for purposes of discussion:

```js
  // VERSION 1
  class EraseParticlesButton extends EraserButton {

    /**
     * @param {ParticleSystem} particleSystem
     * @param {Object} [options]
     */
    constructor( particleSystem, options ) {
      assert && assert( particleSystem instanceof ParticleSystem, `invalid particleSystem: ${particleSystem}` );

      options = merge( {

        // superclass options
        baseColor: GasPropertiesColorProfile.eraserButtonColorProperty
      }, options );

      // Deletes all particles when the button fires.
      assert && assert( !options.listener, 'EraseParticlesButton sets listener' );
      options.listener = () => {
        particleSystem.removeAllParticles();
      };

      super( options );

      // Disables the button when the container is empty.
      particleSystem.numberOfParticlesProperty.link( numberOfParticles => {
        this.enabled = ( numberOfParticles !== 0 );
      } );
    }
  }
```

I would have been inclined to accomplish the same behavior by declaring the listener in the options declaration like so:

```js
  // VERSION 2
  class EraseParticlesButton extends EraserButton {

    /**
     * @param {ParticleSystem} particleSystem
     * @param {Object} [options]
     */
    constructor( particleSystem, options ) {
      assert && assert( particleSystem instanceof ParticleSystem, `invalid particleSystem: ${particleSystem}` );

      options = merge( {

        // superclass options
        baseColor: GasPropertiesColorProfile.eraserButtonColorProperty,

        // Deletes all particles when the button fires. 
        listener: ()=>particleSystem.removeAllParticles()
      }, options );

      super( options );

      // Disables the button when the container is empty.
      particleSystem.numberOfParticlesProperty.link( numberOfParticles => {
        this.enabled = ( numberOfParticles !== 0 );
      } );
    }
  }
```

Here's the diff for ease of readability:

```diff
Index: js/common/view/EraseParticlesButton.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/view/EraseParticlesButton.js	(revision 3b5f9fe668f810168ed4061ca98aed068c6a9f51)
+++ js/common/view/EraseParticlesButton.js	(date 1576686909931)
@@ -27,14 +27,11 @@
       options = merge( {
 
         // superclass options
-        baseColor: GasPropertiesColorProfile.eraserButtonColorProperty
-      }, options );
+        baseColor: GasPropertiesColorProfile.eraserButtonColorProperty,
 
-      // Deletes all particles when the button fires.
-      assert && assert( !options.listener, 'EraseParticlesButton sets listener' );
-      options.listener = () => {
-        particleSystem.removeAllParticles();
-      };
+        // Deletes all particles when the button fires.
+        listener: ()=>particleSystem.removeAllParticles()
+      }, options );
 
       super( options );
 ```

Here are the tradeoffs as I understand them:
* VERSION 1 is hardcoded to supply the listener and cannot inadvertently be assigned a different listener
* VERSION 2 is simpler
* VERSION 2 has the flexibility to override with a different listener

In my opinion, the VERSION 1 hardcoded strategy is akin to defining methods in a class as `final` so they cannot be overriden.  In my opinion, that pattern should be used sparingly, if at all.

**Comment by pixelzoom** [comment]
> I do not recall the consensus or rule of thumb for when options in general should not be overridable.

What?!?!  We just had hours of discussion about options and config, and this was most definitely discussed.  And option or config value should not be overridable if overriding it would cause a problem, or if the API designer decides that it should not be overridable.  

In this specific case, it's the API designer's call. @samreid do you want to be able to override the default tandem name for Stopwatch's `timeProperty`?  And if so, why?

**Comment by samreid** [comment]
> In this specific case, it's the API designer's call. @samreid do you want to be able to override the default tandem name for Stopwatch's timeProperty? And if so, why?

I don't have an immediate use case for overriding this tandem name, but I don't think "having an immediate use case for overriding an option" should be the threshold for determining whether something should be hardcoded rather than defined as a standard option.

**Comment by pixelzoom** [comment]
For Stopwatch `timeProperty` specifically... If tandems of subcomponents are generally overridable, or if there's a need to override this specific tandem, then I have no problem with making this tandem overridable.  If that's not the case, then what's the reason for not preventing it from being (silently!) overridden?

**Comment by samreid** [comment]
To clarify, are you proposing that:

```js
// @public (read-only) time displayed on the stopwatch
this.timeProperty = new NumberProperty( 0, merge( {
  units: 's',
  isValidValue: value => ( value >= 0 ),
  tandem: options.tandem.createTandem( 'timeProperty' ),
  phetioReadOnly: true,
  phetioHighFrequency: true
}, options.timePropertyOptions ) );
```
would become 

```js
// STRATEGY A
// @public (read-only) time displayed on the stopwatch
assert && assert( !options.timePropertyOptions.hasOwnProperty( 'tandem' ), 'Time property provides its own tandem' );
this.timeProperty = new NumberProperty( 0, merge( {
  units: 's',
  isValidValue: value => ( value >= 0 ),
  tandem: options.tandem.createTandem( 'timeProperty' ),
  phetioReadOnly: true,
  phetioHighFrequency: true
}, options.timePropertyOptions ) );
```

or 
```js
// STRATEGY B
// @public (read-only) time displayed on the stopwatch
assert && assert( !options.timePropertyOptions.hasOwnProperty( 'tandem' ), 'Time property provides its own tandem' );
const timePropertyOptions = merge( {
  units: 's',
  isValidValue: value => ( value >= 0 ),
  phetioReadOnly: true,
  phetioHighFrequency: true
}, options.timePropertyOptions );
timePropertyOptions.tandem = options.tandem.createTandem( 'timeProperty' );
this.timeProperty = new NumberProperty( 0, timePropertyOptions );
```
Based on prior conversations I thought you were proposing STRATEGY B, which seems to me like it has a code smell due to the `options.tandem = ...` part.  If instead you are proposing STRATEGY A or if you think STRATEGY A is acceptable, it seems good to me too.

**Comment by pixelzoom** [comment]
Strategy A and B both have the same end result, and both prevent overwriting  `timePropertyOptions.tandem`.    

I'm not sure what "the options.tandem = ... part" refers to in Strategy B, I don't see that anywhere, so can't comment on "code smell".   But it's not necessary to do the assignment to `timePropertyOptions.tandem` after the merge call, because you've already verified via `assert` that it wasn't include in `options.timePropertyOptions`.   So I wouldn't use Strategy B in this case.

Strategy A is preferred. All defaults in one `{...}` object literal, no additional/unneccessary assignment.

**Comment by samreid** [comment]
Perfect, thanks!  I noticed AddAMateButton.js has this declaration:

```js
  class AddAMateButton extends RectangularPushButton {

    /**
     * @param {Object} [options]
     */
    constructor( options ) {

      options = merge( {}, NaturalSelectionConstants.RECTANGULAR_PUSH_BUTTON_OPTIONS, {
        baseColor: NaturalSelectionColors.ADD_A_MATE_BUTTON,
        xMargin: 12,
        yMargin: 8
      }, options );

      assert && assert( !options.content, 'AddAMateButton sets content' );
      options.content = new Text( addAMateString, {
        font: NaturalSelectionConstants.PUSH_BUTTON_FONT,
        maxWidth: 150 // determined empirically
      } );

      super( options );
    }
```

Would it be better to write it using Strategy A?

```js
  class AddAMateButton extends RectangularPushButton {

    /**
     * @param {Object} [options]
     */
    constructor( options ) {

      assert && options && assert( !options.content, 'AddAMateButton sets content' );
      options = merge( {}, NaturalSelectionConstants.RECTANGULAR_PUSH_BUTTON_OPTIONS, {
        baseColor: NaturalSelectionColors.ADD_A_MATE_BUTTON,
        xMargin: 12,
        yMargin: 8,
        content: new Text( addAMateString, {
          font: NaturalSelectionConstants.PUSH_BUTTON_FONT,
          maxWidth: 150 // determined empirically
        } )
      }, options );

      super( options );
    }
```

Should we look around for other occurrences that are using Strategy B? Should we make a note in the phet-software-design-patterns.md?

**Comment by pixelzoom** [comment]
>  I noticed AddAMateButton.js has this declaration: ... Would it be better to write it using Strategy A?

I don't have a problem with how `AddAMateButton` is currently implemented.  Definition of its content is verbose enough that I prefer not to nest it inside the `merge` call.   

> Should we look around for other occurrences that are using Strategy B? Should we make a note in the phet-software-design-patterns.md?

It sounds like perhaps you think Strategy B is undesirable because it wasn't ideal for https://github.com/phetsims/phet-info/issues/128#issuecomment-568114042.  That's not the case.

**Comment by pixelzoom** [comment]
> Should we make a note in the phet-software-design-patterns.md?

It seems like this is already addressed by phet-software-design-patterns.md:

> (2) Before setting a value in an options object (with either assignment or merge), verify that the client did not provide a value. Use an assertion to verify. Don't silently override what the client provided.

Maybe this should be clarified to say something like "Don't allow the client to set an option that is the responsibility of the constructor or method being called."

**Comment by samreid** [comment]
> It sounds like perhaps you think Strategy B is undesirable because it wasn't ideal for #128 (comment).

I like how it is phrased here:

> Strategy A is preferred. All defaults in one `{...}` object literal, no additional/unneccessary assignment, no `timePropertyOptions` local variable.

I understand what you are saying about the `AddAMateButton` content declaration content being more verbose.  But what about cases like `DataProbeDragListener`, which are non-verbose and could be improved by putting all defaults in one object literal, and no additional/unnecessary assignment?  I'm trying to find out where you draw the line for this pattern, or if matters very much.  To me, I prefer putting defaults in one object literal with no additional/unnecessary assignment, even when there is a more verbose declaration like in `AddAMateButton`.  I'm fine if we settle on "developer preference" for this, but you and I both prefer Strategy A, so I'm trying to see where it would be applicable.

I revised the documentation in phet-software-design-patterns.md based on your recommendation.  Let's continue to improve it.

**Comment by pixelzoom** [comment]
> ... but you and I both prefer Strategy A, so I'm trying to see where it would be applicable.

I don't prefer Strategy A.  I prefer Strategy A in the example we discussed here, https://github.com/phetsims/phet-info/issues/128#issuecomment-568114042.    There are other situations where I prefer Strategy B. Off the top of my head, I prefer Strategy B when (a) there's something that I don't want to nest inside the `merge` call (like in `AddAMateButton`), or (b) there's something that I can't (or can't without a great deal of code gymnastics) nest inside the `merge` call (`options.children` is a ubiquitous example).

**Comment by samreid** [comment]
What case does `DataProbeDragListener` fall into, and why?

**Comment by pixelzoom** [comment]
I'm not sure what you mean...  Somehow we seem to have gone from "maybe Stopwatch shouldn't be allowing the client to overwrite tandem" to an assumption that there are a couple of strategies for doing that, and that one strategy should be preferred over the other.  That's not the way I think about this, and that's certainly not what I had in mind with `DataProbeDragListener`.   I'm thinking best practices:

(1) Don't assign to an options object that you don't own.
(2) Don't overwrite options provided by the client. 
(3) Don't allow the client to overwrite options that you're responsible for.

`DataProbeDragListener` satisfies all of those.  `Stopwatch` seems to be violating (3).

**Comment by samreid** [comment]
> Stopwatch seems to be violating (3).

That was corrected in https://github.com/phetsims/scenery-phet/commit/45c1d29f61cf6fc2198a5dff041bb61228e1110d, right?

> Somehow we seem to have gone from "maybe Stopwatch shouldn't be allowing the client to overwrite tandem" to an assumption that there are a couple of strategies for doing that, and that one strategy should be preferred over the other. 

That describes my trajectory precisely!  Before this issue, I (incorrectly) thought "tacking on options" after the `merge` call was the only way to accomplish this.  Now I understand we can achieve (1)-(3) above without having to "tack on" options after the `merge` call, and it seems significantly better to me.  For example, I believe that:

```js
assert && assert( !options || !options.dragBoundsProperty, 'DataProbeDragListener sets dragBoundsProperty' );
assert && assert( !options || !options.locationProperty, 'DataProbeDragListener sets locationProperty' );
options = merge( {
  dragBoundsProperty: new Property( new Bounds2( xRange.min, 0, xRange.max, 0 ) ),
  locationProperty: locationProperty
}, options );
```

would be better than
```js
options = merge( {}, options );

assert && assert( !options.dragBoundsProperty, 'DataProbeDragListener sets dragBoundsProperty' );
options.dragBoundsProperty = new Property( new Bounds2( xRange.min, 0, xRange.max, 0 ) );

assert && assert( !options.locationProperty, 'DataProbeDragListener sets locationProperty' );
options.locationProperty = locationProperty;
```

For the same reasons that we preferred Strategy A in https://github.com/phetsims/phet-info/issues/128#issuecomment-568114042.  For me, it is easier to read and understand options being described in the `merge` call rather than "tacked on" later.

I'm happy for you to agree or disagree.  If you agree that most options should be defined in the `merge` call, should we (a) describe this as a convention in the patterns document and (b) come up with a plan for cleaning up usages that "tack on" things later unnecessarily?  If you think it's equally acceptable to "tack on" options after the merge call vs defining them in the merge call, let's create a new "dev meeting" issue to discuss that further as a group, because to me that seems like an avoidable code smell.

Can this issue be closed?

**Comment by pixelzoom** [comment]
When extrapolating this example to a general pattern:

```js
assert && assert( !options || !options.dragBoundsProperty, 'DataProbeDragListener sets dragBoundsProperty' );
assert && assert( !options || !options.locationProperty, 'DataProbeDragListener sets locationProperty' );
options = merge( {
  dragBoundsProperty: new Property( new Bounds2( xRange.min, 0, xRange.max, 0 ) ),
  locationProperty: locationProperty
}, options );
```

... there are a 3 things that I don't like:

(1) Having to test `!options` repeatedly in assertion expressions.

(2) Separating the assertion from the option value, possibly by many lines in the general case. I think it can sometimes be more valuable to co-locate them, especially when the assertion expression serves as (implicit?) documentation about the value. 

(3) The tendency to nest complicated things inside the `merge` call. In cases where the value is complicated, requires biggish comments, or the code is clearer if the value is computed after the `merge` call (options.children being the most common example), I'd rather see the value assigned after the `merge` call.

That said...  I'm also not wild about `options = merge( {}, options )` in DataProbeDragListener.  I'm willing to live with it because I consider that a lesser of evils.  Perhaps `options = options || {}` would be preferable, but I'm not going to waste cycles on that.

So no, I don't agree that one pattern is generally preferable over the other.  And I think it's way down in the noise, in terms of any benefit to be gained from standardizing.  `merge` is deceptively complex, and there are multiple legitimate ways to accomplish the same result.  Imo, we should be focusing on the result, i.e. the best practices, and not trying to get everyone to use identical "styles".

**Comment by samreid** [comment]
Thanks for taking the time to help me understand, I really appreciate it.  I'm still learning to distinguish between "styles" and "best practices".

I added a commit to phet-software-design-patterns.md with this sentence:

> Please see https://github.com/phetsims/phet-info/issues/128 for a discussion of acceptable approaches for checking that a client did not provide an option, and how the option can be specified.

I still feel a bit of cognitive dissonance around aspects of this problem.  I agree that these issues may be down in the noise and may not warrant effort or debate, but I think I should write down some thoughts for completeness.

1. In https://github.com/phetsims/axon/issues/202#issuecomment-563358118 we wrote "we decided that it is best for readability that the options should be combined in a single object instead of splitting into different statements." But maybe it's not important for the "non-overrideable" options to be listed there, since they are not really options for that constructor/method?  Even so, in some cases it may be more readable for non-overrideable options to be listed together with the other options.
2. There is a team consensus to use a `required()` pattern which looks like so:

```js
function Person( name, config ) {
  config = merge( {
  
    // {number} height in centimeters
    height: required(config.height), 
    
    // {number} age in years
    age: required(config.age), 

    favoriteColor: null, // {Color|null} favorite Color, if any
    favoriteCar: null // {Car|null} favorite Car, if any
  }, config );
```

It seems asymmetrical to have one strategy for when an option is "required to be passed in" and a completely different pattern for when an option is "required to not be passed in".  What if we invent something like `antirequired()`?  Brainstorming sample usage:

```js
// Strategy 1
options = merge( {}, options );

assert && assert( !options.dragBoundsProperty, 'DataProbeDragListener sets dragBoundsProperty' );
options.dragBoundsProperty = new Property( new Bounds2( xRange.min, 0, xRange.max, 0 ) );

assert && assert( !options.locationProperty, 'DataProbeDragListener sets locationProperty' );
options.locationProperty = locationProperty;

// Strategy 2
options = merge( {
  dragBoundsProperty: antirequired( options, 'dragBoundsProperty' ),
  locationProperty: antirequired( options, 'locationProperty' )
}, options );

options.dragBoundsProperty = new Property( new Bounds2( xRange.min, 0, xRange.max, 0 ) );
options.locationProperty = locationProperty;

// Strategy 3
options = merge( {
  dragBoundsProperty: antirequired( options, 'dragBoundsProperty', new Property( new Bounds2( xRange.min, 0, xRange.max, 0 ) ) ),
  locationProperty: antirequired( options, 'locationProperty', locationProperty )
}, options );
```

Strategy 2 and 3 have the disadvantage that the key name is repeated, but this is also a disadvantage with the `required()` strategy.   Strategy 2 suffers from problem (2) identified in https://github.com/phetsims/phet-info/issues/128#issuecomment-569457299.  Strategy (3) suffers from problem (3).  I'm not saying `required()` is the perfect pattern, but there was a team consensus about its usefulness, so that's why I wanted to see if we should add something like `antirequired()` to go along with it (could have a better name though).

**Comment by pixelzoom** [comment]
> But maybe it's not important for the "non-overrideable" options to be listed there, since they are not really options for that constructor/method?

I don't feel a need for non-overridable options to be nested in the `merge` call.  They are not part of the API. 

>  What if we invent something like `antirequired()`?

I'm not wild about this suggestion because I feel like the current patterns that I'm using are sufficient, clear, and readable.  And `antirequired` will be another runtime function call (a startup cost), whereas `assert && assert` is short circuited.   That said, you should probably solicit feedback from other developers.  Based on code reviews, I suspect that some of the other developers are still a bit unclear on the best practices, and I don't know if something like `antirequired` would make that better or worse.

**Comment by pixelzoom** [comment]
3/12/2020 dev meeting:

@jonathanolson pointed out that `antirequired` has a flaw: Having `field: undefined` is different than not have `field` at all in options.  And that will cause problems when passed to `super`, it all overwrite the default with `undefined`.

I suggested that you could create a blacklist of options using `_.pick`, like this:

```js
constructor( ..., options ) {

  // options that should not be specified by the caller
  assert && assert( _.pick( options, [ 'spacing', 'align', 'children' ] ), ... );
  
 options = merge( {
    spacing: 5,
    align: 'right'
  }, options );

  // create some Nodes, then:
  options.children = [ ... ];
```

The disadvantage of this over individual `assert` statements is that you don't know which blacklisted option(s) cause the assertion failure.

**Comment by samreid** [comment]
It sound like individual `assert` statements are warranted so we can know which option caused the failure.  Can this issue be closed?

**Comment by pixelzoom** [comment]
I don't mind if someone uses an approach like `_.pick` -- it's better than doing nothing, which I've encountered often.   But yes, my preference would be to use `assert`. 

Closing.
