### ISSUE TITLE
GitHub basic authentication deprecation

### ISSUE THREAD

**Issue by samreid** [phetsims/phet-info#131]
While working on https://github.com/phetsims/phet-io-wrappers/issues/292 I used the script to create labels.  But I shortly thereafter received an email from GitHub saying:

Hi @samreid,

You recently used a password to access an endpoint through the GitHub API using curl/7.64.1. We will deprecate basic authentication using password to this endpoint soon:

https://api.github.com/organizations/3045815/repos

We recommend using a personal access token (PAT) with the appropriate scope to access this endpoint instead. Visit https://github.com/settings/tokens for more information.

Thanks,
The GitHub Team

Assigning to @ariel-phet to evaluate and assign accordingly.

**Comment by ariel-phet** [comment]
Marking for dev meeting as this might also affect things like Babel and a few other things we do with GitHub

**Comment by mattpen** [comment]
I'll check the inbox for phetadmin@gmail.com to see if this is affecting babel.  @jonathanolson mentioned there is already some code that is using PAT's that we may potentially be able to reuse.  

I'll address this soon as it could be potentially affecting babel.

**Comment by mattpen** [comment]
It looks like this is affecting babel:

> ---------- Forwarded message ---------
> From: GitHub <noreply@github.com>
> Date: Wed, Jan 15, 2020 at 12:52 PM
> Subject: [GitHub] Deprecation Notice
> To: phet-dev <phetadmin@gmail.com>
> 
> 
> Hi @phet-dev,
> 
> You recently used a password to access an endpoint through the GitHub API using octonode/0.3 (https://github.com/pksunkara/octonode) terminal/0.0. We will deprecate basic authentication using password to this endpoint soon:
> 
> https://api.github.com/repositories/28885266/contents/gravity-force-lab/gravity-force-lab-strings_hr.json?ref=master
> 
> We recommend using a personal access token (PAT) with the appropriate scope to access this endpoint instead. Visit https://github.com/settings/tokens for more information.
> 
> Thanks,
> The GitHub Team

**Comment by mattpen** [comment]
@jonathanolson - can you point me to the phet files that are using github access tokens?

**Comment by mattpen** [comment]
https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/

There isn't an official timeline for deprecation that has been announced yet.  Lowering to priority 3.

**Comment by jonathanolson** [comment]
I know githubCreateIssue.js uses octokit, and grabs the access token from buildLocal.js (which has code to grab the token from build-local.json).

**Comment by mattpen** [comment]
From Slack, @pixelzoom said The email that I received after running github-labels says "On July 1st, 2020, basic authentication using password to this endpoint will no longer work"

**Comment by mattpen** [comment]
I believe that the github labels scripts are now fixed.  Developers will now need to create a personal access token and store it in build-local.json along with their username in order to use these scripts.  This is documented in https://github.com/phetsims/phet-info/blob/master/github-labels/README.md.

Instructions for creating a personal access token: https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line#creating-a-token.

**Comment by mattpen** [comment]
Adding to developer meeting as a general PSA.

**Comment by zepumph** [comment]
Thanks for the PSA! We are ready to close. 

@mattpen says it will be obvious the next time someone runs it because it will fail to find the needed key.
