### ISSUE TITLE
Checklists should indicate to set correct permissions before committing to perennial

### ISSUE THREAD

**Issue by samreid** [phetsims/phet-info#132]
From slack:

@KatieWoe said
> I'm seeing a blank CT page. Anyone know what's going on?

@jonathanolson replied:
> Looks like CT hit an error (spawn git ENOENT) and restarted
> Actually it's looping that

@samreid said:
> Related to the new repo creation?

@jonathanolson said:
> Possibly? Was the repo created and had the team permissions before being added to active-repos?
> I manually did a clone-missing-repos and that added studio on CT, not sure why it didn't happen before

@samreid said
> Unfortunately, I committed to perennial before setting the team permissions
> Should we change the checklist to reverse that order?

@jonathanolson said:
> If the checklist has team permissions after adding to active-repos, yes it should change

Assigning to @ariel-phet to prioritize and delegate.

**Comment by jonathanolson** [comment]
I'm honestly not sure what happened. My last commit to the checklist had the active-repos step after the permissions step (https://github.com/phetsims/phet-info/blob/70a5953e9ab5180ff1b4bfca11ae93380149fa9a/checklists/new_repo_checklist.md), it must have been reversed in the checklist at a later point.
