### ISSUE TITLE
Update the "Module" section of the software design patterns doc

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/phet-info#134]
[phet-software-design-patterns.md](https://github.com/phetsims/phet-info/blob/master/doc/phet-software-design-patterns.md) was written to describe PhET's usage of RequireJS. We recently switched to ES6 modules and so this section needs to be updated. Assigning to @Denz1994 since he was the original author of this section.

**Comment by pixelzoom** [comment]
Related to https://github.com/phetsims/chipper/issues/854.

**Comment by pixelzoom** [comment]
I'll take this one over, low priority.

**Comment by pixelzoom** [comment]
I was happy to discover that @jonathanolson already handled this in https://github.com/phetsims/phet-info/commit/1a1b80fc6cf9c62a2bf90af81fa82dd720342bfa#diff-a633fe0bc1c3bf0252772f5bdeb4d8eb0a910e98d456e3cb6f1c61dbeb6eaef3 for phetsims/chipper#905. 

Closing.
