### ISSUE TITLE
Revise CRC regarding imports

### ISSUE THREAD

**Issue by samreid** [phetsims/phet-info#135]
Discovered during https://github.com/phetsims/energy-skate-park/issues/202.  The CRC currently says:

> - [ ] Require statements should be organized into blocks, with the code modules first, followed by plugins (strings, images, sound, ifphetio - any order ok for plugins).  For modules, the variable name should match the file name. Example below.
  
  ```js
  // modules
  const inherit = require( 'PHET_CORE/inherit' );
  const Line = require( 'SCENERY/nodes/Line' );
  const Rectangle = require( 'SCENERY/nodes/Rectangle' );
  
  // strings
  const kineticString = require( 'string!ENERGY/energy.kinetic' );
  const potentialString = require( 'string!ENERGY/energy.potential' );
  const thermalString = require( 'string!ENERGY/energy.thermal' );
  
  // images
  const energyImage = require( 'image!ENERGY/energy.png' );
  
  // sound
  const kineticAudio = require( 'sound!ENERGY/energy' );
  ```

For ES6 modules, we agreed to combine all JS into one section and drop the // modules.  I'm not sure what should be done about strings.

**Comment by samreid** [comment]
@pixelzoom can you please recommend how the CRC should look for this part?

**Comment by pixelzoom** [comment]
All imports grouped together, no differentiation between code or resources (strings, images, mipmaps, sound).  The CRC will be updated in https://github.com/phetsims/chipper/issues/854.

**Comment by samreid** [comment]
Thanks, I removed the hold from https://github.com/phetsims/chipper/issues/854.  @pixelzoom can this issue be closed?  Do you want any information from this moved to https://github.com/phetsims/chipper/issues/854?

**Comment by pixelzoom** [comment]
I updated this specific section of the CRC in https://github.com/phetsims/phet-info/commit/0001f49c87f3279edeef379055b74e2b5abc2354.   Feel free to review here, or wait until we've established best practices in https://github.com/phetsims/chipper/issues/873, and revised the CRC in https://github.com/phetsims/chipper/issues/854.

**Comment by samreid** [comment]
The changes look reasonable, thanks! I have one question about this part:

> immediately following the copyright comment and file overview comment.

For files that only emit one function, I've found it useful to omit the file overview comment and provide that information in the function JSDoc instead.  One example is https://github.com/phetsims/wave-interference/blob/bfe9e0df55ea1405244a89253d75a6db2eaed3dd/js/common/view/toOutputLevel.js

Does this seem reasonable to you?  How should this be described in the CRC?

**Comment by pixelzoom** [comment]
> ... Does this seem reasonable to you? How should this be described in the CRC?

@samreid Imo, precisely describing where import groups need to appear for various scenarios is detail that doesn't need to be in the CRC.   So my response to your question is to make the CRC item more vague, that is:

> All `import` statements should be grouped together towards the top of the .js file. If `import` appears elsewhere, documention should indicate why. Imports for code and resources (images, sounds,...) are all treated the same. Imports should be sorted according to PhET code style, as done by WebStorm "Organize Imports". Example: ...

If you think something more specific is really needed, feel free to modify.

**Comment by samreid** [comment]
Excellent, thanks!  Closing.
