### ISSUE TITLE
Update the "Singleton" section of the software design patterns doc

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#136]
Related to https://github.com/phetsims/chipper/issues/854.

The "Singleton" section of the software design patterns doc needs to be updated to reflect PhET's change from requirejs to ES6.  Assign to @chrisklus, the author of that section.

**Comment by chrisklus** [comment]
Thanks @pixelzoom  - should be all set. Please review if you'd like and/or close if all looks good.

**Comment by pixelzoom** [comment]
👍 closing.
