### ISSUE TITLE
Update the "Namespace" section of the software design patterns doc 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#137]
https://github.com/phetsims/chipper/issues/854

The "Namespace" section of the software design patterns doc needs to be updated to reflect PhET's change from requirejs to ES6. Assign to @jonathanolson, the author of that section.

**Comment by jonathanolson** [comment]
I updated that section and a few others (although I'm sure it could be filled out more). Does that look good, or anything that feels insufficient?

**Comment by pixelzoom** [comment]
Other people were assigned to update their sections, but thanks for taking a stab at it.

Namespace section looks good, closing.
