### ISSUE TITLE
After an update the sims stop working

### ISSUE THREAD

**Issue by sebastianduran** [phetsims/phet-info#141]
After an `npm update` the sim doesn't load, it stay freeze on the splash page even the example-sim_en.html sim

node version: v12.16.1
os: win10

**Comment by pixelzoom** [comment]
Assigning to @ariel-phet (development manager) to prioritize and assign this issue.

**Comment by ariel-phet** [comment]
@sebastianduran this repo is generally for internal PhET business and documentation.

For a question such as this one please join the Developing Interactive Simulations in HTML5 Google Group

https://groups.google.com/g/developing-interactive-simulations-in-html5/c/O1cJem3VW18?pli=1

Closing
