### ISSUE TITLE
Location of function visibility annotations

### ISSUE THREAD

**Issue by chrisklus** [phetsims/phet-info#142]
I'm bringing this up because I noticed that most phet-io code follows this convention (1):

```js
/**
 * Comment here.
 * @param {number} number
 * @param {string} string
 * @returns {boolean}
 * @private
 */
```

But then PhetioStateEngine has a lot of them flipped like this (2):

```js
/**
 * Comment here.
 * @private
 * 
 * @param {number} number
 * @param {string} string
 * @returns {boolean}
 */
```

or like this (3):

```js
/**
 * Comment here.
 *
 * @private
 * @param {number} number
 * @param {string} string
 * @returns {boolean}
 */
```

I thought the first example was pretty standard at PhET (and that's how I've always done it), but after looking around, it looks like plenty of places use the second example, too. It seems a little odd that the visibility annotation generally seems like the only one that varies in position in the JSDoc (and therefore can take a quick second longer for me to find if it's not where I was expecting). Do we want to have a convention, or is developer discretion sufficient?

@pixelzoom edit: I numbered the 3 examples, to make it easier to refer to them.

**Comment by jessegreenberg** [comment]
I always do the second one. I find it easier to read the param docs if there is some space between them and the visibility annotation. But don't care too much and would be OK not having a rule for this.

**Comment by pixelzoom** [comment]
I don't see anything in JSdoc that recommends an order. If we generated JSdoc, the order wouldn't matter.  And I personally don't care where they are located.  So I don't think it's worth the cost/aggravation to standardize.

**Comment by pixelzoom** [comment]
I have generally done (1). That said... I don't see anything in JSdoc that recommends an order. If we generated JSdoc, the order wouldn't matter.  And I personally don't care where they are located.  So I don't think it's worth the cost/aggravation to standardize, and would prefer to leave this up to individual developers.

**Comment by jessegreenberg** [comment]
Discussed 5/21/20 - 

All were OK to leave this up to developer discretion.
