### ISSUE TITLE
How to override a function that is called in the constructor of the superclass

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/phet-info#144]
Ive run into this a few times and I am curious how people get around this in general. Lets say I have a superclass that calls a method in its constructor:
```js
class MyClass {
  constructor() {
    this.doSomething();
  }

  doSomething() {
    //...
  }
}
```

And a subclass that overrides that function with subclass specific work, using fields of the subclass:

```js
class AnotherClass extends MyClass {
  constructor() {
    super();

    // @private - used in doSomething
    this.subclassThing = ...;
  }

  /**
   * @override
   */
  doSomething() {
    super.doSomething();

    // do something with this.subclassThing here
   }
}
```

```this.subclassThing``` will be undefined in `AnotherClass.doSomething` because `doSomething` was called during construction of superclass, before this.subclassThing is defined. Have people used a general pattern to get around this?

**Comment by jessegreenberg** [comment]
The problem also comes from the fact that we cannot assign things to `this` until after calling `super`

**Comment by brandonLi8** [comment]
I've also ran into this problem on occasion. What I normally do (not saying that this is correct) is to call `this.doSomething` in the sub-class's constructor, after `this.subclassThing` is defined. It has worked for me in the cases where I've ran into this, but it might be possible that this might not work for all scenarios.

**Comment by zepumph** [comment]
I have had success in refactoring subclassThing to be an option to the constructor, instead of setting it in the child. This works best if multiple subclasses use this sort of pattern.

In adding to @brandonLi8's suggestion, perhaps the subtype `doSomething` can check to see if `this.subclassThing` exists yet, and if it doesn't, then it can no-op. Then it won't be run twice in the constructor, but only from the subtype callsite. This still wouldn't work if `doSomething` had to be called before logic at the end of the parent constructor though. 

Good luck!

**Comment by samreid** [comment]
The standard solution is that constructors should not call overrideable methods, this is described in https://stackoverflow.com/a/3404369 which quotes Effective Java 2nd Edition (emphasis mine):

> There are a few more restrictions that a class must obey to allow inheritance. **Constructors must not invoke overridable methods**, directly or indirectly. If you violate this rule, program failure will result. The superclass constructor runs before the subclass constructor, so the overriding method in the subclass will be invoked before the subclass constructor has run. If the overriding method depends on any initialization performed by the subclass constructor, the method will not behave as expected.

But I have seen many examples in our codebase where we use the solutions described in the prior 2 comments.

**Comment by pixelzoom** [comment]
+1 for what @samreid said -- methods called by a constructor should not be overridden.

Change your subclass implementation in the above example to:

```
class AnotherClass extends MyClass {

  constructor() {
    super();
    this.subclassThing = ...;
  }

  doSomethingAndMore() {
    this.doSomething();
    // do something with this.subclassThing here
   }
}
```

**Comment by jessegreenberg** [comment]
This makes a lot of sense, thanks for the recommendations and feedback.
