### ISSUE TITLE
change-label.sh fails

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#146]
I want to change the color of 2 labels as follows:

```diff
- status:blocks-publication,00FFCC
+ status:blocks-publication,FF007F
- status:blocks-sim-publication,00ff6e
+ status:blocks-sim-publication,e11d21
```

I've followed the instructions in README.md, and I have a personal access token named "repo" configured, with full repo access:  

<img width="571" alt="screenshot_463" src="https://user-images.githubusercontent.com/3046552/89927091-09ef3a00-dbc3-11ea-802c-ae9a2be3c346.png">

Following the instructions to change a label, I ran `change-label.sh` and I got nothing but 404 failures:

```
% cd phet-info/github-labels/
% ./change-label.sh status:blocks-publication status:blocks-publication FF007F
For each repo, this script should print "200 OK" to indicate success
Path: https://api.github.com/repos/phetsims/a11y-research/labels/
Data: {"name":"status:blocks-publication","color":"FF007F"}
Result:
HTTP/1.1 404 Not Found
Path: https://api.github.com/repos/phetsims/acid-base-solutions/labels/
Data: {"name":"status:blocks-publication","color":"FF007F"}
Result:
HTTP/1.1 404 Not Found
Path: https://api.github.com/repos/phetsims/aqua/labels/
Data: {"name":"status:blocks-publication","color":"FF007F"}
Result:
HTTP/1.1 404 Not Found
Path: https://api.github.com/repos/phetsims/area-builder/labels/
Data: {"name":"status:blocks-publication","color":"FF007F"}
Result:
HTTP/1.1 404 Not Found
Path: https://api.github.com/repos/phetsims/area-model-algebra/labels/
Data: {"name":"status:blocks-publication","color":"FF007F"}
...
```

I've tried this with and without VPN, same results.  What am I doing wrong?

**Comment by pixelzoom** [comment]
I'm wondering if the API changed and this script wasn't updated.  The "Update a Label" API is described at https://docs.github.com/en/rest/reference/issues#update-a-label, and the example using `curl` looks nothing like the use of `curl` in `change-label.sh.`

**Comment by mattpen** [comment]
It looks like the api updated (but should have been backwards compatible), so I changed the `name` parameter in the body to `new_name`.  I also discovered a typo in a variable usage, `old` should have been `'oldLabel`.  After these changes I ran the script using the command `./change-label.sh status:blocks-publication status:blocks-publication FF007F` and got successes for most repos.  

I'll investigate repos that returned 404 errors here: https://github.com/phetsims/phet-info/issues/147
Repos that returned 403 errors have been archived.  I'll add documentation to explain each of these results.

@pixelzoom - can you please pull phet-info and try this script for the `status:blocks-sim-publication` label change and see if it is working on your side now?

**Comment by pixelzoom** [comment]
Thanks for fixing this. It's working for me now.   

I did get errors for some repos, see below. Would you mind investigating these?

403: diagram-demo, phet-io-wrapper-sonification

404: a11y-research, beaker, circuit-construction-kit-basics, faraday, phet-office-add-in, phet-partnerships, QA, seasons, special-ops, webgl-ripples, website-docker, wilder

**Comment by mattpen** [comment]
@pixelzoom - see my previous comment regarding the errors.  The 403 errors are "correct" and the 404 errors are being investigated.

> I'll investigate repos that returned 404 errors here: #147
> Repos that returned 403 errors have been archived. I'll add documentation to explain each of these results.

I'm going to close this issue since the problems particular to this script have been corrected.
