### ISSUE TITLE
Repos missing standard labels

### ISSUE THREAD

**Issue by mattpen** [phetsims/phet-info#147]
The following repos are missing the `status:blocks-publication` label, possibly others.   

```
a11y-research
beaker
circuit-construction-kit-basics
color-vision
faraday
java-nuclear-physics
masses-and-springs-basics
phet-cordova-app
phet-io-wrapper-arithmetic
phet-office-add-in
phet-partnerships
QA
special-ops
webgl-ripples
website-docker
```

**Comment by mattpen** [comment]
```
masses-and-springs-basics
phet-io-wrapper-arithmetic
```
These two repos had a label called "status:block-publication". I edited these manually to be "status:blocks-publication".

**Comment by mattpen** [comment]
@ariel-phet - I'm assuming these repos should all have at least the standard phet set.  Should I just run the script for the standard set on all of these repos?

**Comment by ariel-phet** [comment]
@mattpen -- yes please

**Comment by mattpen** [comment]
This was completed today.
