### ISSUE TITLE
relocate .credentials

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#15]
The first step in https://github.com/phetsims/phet-info/blob/master/github-labels/README.md is:

> Create a .credentials file in this directory in the format gitHubUsername:gitHubPassword

We generally try to avoid creating files like this in our working copy, because it increases the probability of accidentally checking it in to github.  Better approaches:

(1) Create the file in $HOME/.phet/ (would require a better name)

(2) Add fields to $HOME/.phet/build-local.json

Option 2 is preferred, since this is where other credentials currently live for PhET tools.

**Comment by mattpen** [comment]
I moved the credentials to the .phet directory.  At some point this should be replaced by oAuth.
