### ISSUE TITLE
Update new sim repo instructions about phettest

### ISSUE THREAD

**Issue by samreid** [phetsims/phet-info#151]
Discovered during https://github.com/phetsims/circuit-construction-kit-common/issues/647.  The new repo checklist says:

> Navigate to phettest.colorado.edu and click the "Refresh Perennial" button. If you're off campus, CU's VPN service is required to access phettest.colorado.edu.

It is my understanding that we are moving toward using https://bayes.colorado.edu/dev/phettest/, which does not require VPN.  Is that correct?  Are we still maintaining phettest.colorado.edu?  Should the instructions say to update both?

@zepumph can you please advise?

**Comment by zepumph** [comment]
https://bayes.colorado.edu/dev/phettest/ is the future, we should just keep https://bayes.colorado.edu/dev/phettest/. My hope is that we could retire phettest.colorado.edu, though I wanted some amount of time for us to experiment with the bayes one before taking the other offline.

**Comment by samreid** [comment]
Excellent, thanks! Closing.
