### ISSUE TITLE
add no-bitwise lint rule

### ISSUE THREAD

**Issue by zepumph** [phetsims/phet-info#157]
From https://github.com/phetsims/phet-info/issues/150, it was a formatting rule, but we only saw a rare few spots that warranted it (outside of scenery).

Steps for this issue:

- [x] make sure scenery sets this rule off (https://github.com/phetsims/scenery/blob/050d7b94745fd5e7dce783f402b472fb0220f722/package.json#L34)
- [x] Convert usages of ` | 0 ` as a way of type casting to an int to something else
- [x] Add this rule to the general lint rules:

```
  // disallow use of bitwise operators
    // https://eslint.org/docs/rules/no-bitwise
    'no-bitwise': 'error',

```

- [x] eslint-disable-line in any cases that deserve to use it (like ShapePlacementBoard)

**Comment by samreid** [comment]
Fixed, this seemed straightforward (even though we haven't used Math.trunc before).  Closing.
