### ISSUE TITLE
Create "type:quarterly" label

### ISSUE THREAD

**Issue by samreid** [phetsims/phet-info#159]
From today's status meeting:

> Proposal to add: “type:quarterly” - color family from epic, a shade darker or lighter. 

I volunteered to create the label.  Epic is #4B0082, already pretty dark, so let's go with a shade lighter at #603680.

![image](https://user-images.githubusercontent.com/679486/110835217-c0032b00-825b-11eb-9cc4-c2a5b10af617.png)

**Comment by samreid** [comment]
Maybe #6d458a would be better?

![image](https://user-images.githubusercontent.com/679486/110835446-09ec1100-825c-11eb-9779-ef8fcc7d25c5.png)

**Comment by samreid** [comment]
Or how about this #735da6

![image](https://user-images.githubusercontent.com/679486/110835747-71a25c00-825c-11eb-9ee7-3bfd2f503677.png)

**Comment by samreid** [comment]
I ran the script and checked a few repos to see that it appeared as expected.  I'll notify the team on slack.  Closing.

**Comment by samreid** [comment]
@zepumph reported that this label is missing from repos such as `ratio-and-proportion` and `tasks`.  @mattpen can you please advise how to proceed?

**Comment by samreid** [comment]
@mattpen suggested running the script several times to see if it could hit the missing places.

**Comment by samreid** [comment]
There are only 30 repos in .repos, could this explain the problem?

**Comment by mattpen** [comment]
.repos should get generated automatically from a github api query.  I think it is failing due to some bad assumptions I'm making in that script about json.  I should be able to make some time for this today or tomorrow (4/9/21)

**Comment by samreid** [comment]
Thanks.  For now, I copy/pasted perennial/data/active-repos.  That should get most of them, but I don't think that list is complete.  It only has 174 repos at the moment.

**Comment by samreid** [comment]
OK that finished and seems good enough for now.  The command for future reference (if we want to run it again after .repos is corrected) is:

```
./new-label-all-repos.sh type:quarterly 735DA6
```

**Comment by mattpen** [comment]
After fixing the repo generation script I reran this and it picked up the remaining repos.
