### ISSUE TITLE
PhET Development Overview has incomplete sections

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#162]
While responding to a Google Group question about how to debug sims, I noticed that 2 sections of the [PhET Development Overview](https://github.com/phetsims/phet-info/blob/master/doc/phet-development-overview.md) are currently incomplete:

> Submit an Issue
> 
> Using Chrome dev tools to debug a simulation

The Google Group thread and my response is https://groups.google.com/g/developing-interactive-simulations-in-html5/c/h2GKy83RjwY.   Some of my response might be useful for fleshing out the latter section.

Labeling for traige at dev meeting.

**Comment by samreid** [comment]
@chrisklus volunteered to write up basic sections, he can reference https://groups.google.com/g/developing-interactive-simulations-in-html5/c/h2GKy83RjwY accordingly.  The "chrome dev tools" section should be somewhat simple/general since we will have to maintain it for the long term.

**Comment by pixelzoom** [comment]
For the  "chrome dev tools" section...  I don't think you want to flesh out this section. Trying to keep descriptions, steps, screenshots, etc. up-to-date as Chrome Dev Tools evolves would be costly at best, and would more likely not happen.   So I think it would be sufficient to say something like my reply in https://groups.google.com/g/developing-interactive-simulations-in-html5/c/h2GKy83RjwY:

> Most of the PhET team uses the Chrome browser for debugging and development. Information about Chrome DevTools can be found at https://developer.chrome.com/docs/devtools/.

**Comment by chrisklus** [comment]
>For the  "chrome dev tools" section...  I don't think you want to flesh out this section. Trying to keep descriptions, steps, screenshots, etc. up-to-date as Chrome Dev Tools evolves would be costly at best, and would more likely not happen.   So I think it would be sufficient to say something like my reply in https://groups.google.com/g/developing-interactive-simulations-in-html5/c/h2GKy83RjwY:

We decided to add this in the onboarding doc instead, over in https://github.com/phetsims/phet-info/issues/192.

For the "Submit an issue" section, we discovered that this had already been removed, and we thought it was best to leave it this way. 

We also removed a header that linked to a section that didn't exist. Closing.
