### ISSUE TITLE
Create a Quickstart Guide for alternative input.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#168]
The need for a Quickstart Guide for alternative input was discussed at 10/21/21 dev meeting.

Since I just added alternative input to Geometric Optics, I'll throw together a rough guide, while it's fresh in my mind.

**Comment by pixelzoom** [comment]
Raising priority since there's been no progress for > 30 days.

**Comment by pixelzoom** [comment]
This guide needs a section on how to add hotkeys.

**Comment by pixelzoom** [comment]
Q2 2022 planning meeting:

* @pixelzoom will add section on hotkeys (1 hour)
* @jessegreenberg will review the doc (1 hour)

**Comment by pixelzoom** [comment]
In the above commits, I added info about hotkeys and keyboard help.  I also reformatted the document - it was originally a set of "step", and that's no longer appropriate. 

@jessegreenberg ready for review. Feel free to make changes/corrections.

**Comment by jessegreenberg** [comment]
This document is excellent, thanks @pixelzoom. All looks correct. The only thing I could think of to add was a note about hotkeys and avoiding collisions with other global hotkeys (with a reference to https://github.com/phetsims/phet-info/issues/188 where we should have a registry for this).

Closing.
