### ISSUE TITLE
Questions and (hopefully) answers about Nagios

### ISSUE THREAD

**Issue by jbphet** [phetsims/phet-info#17]
I recently was working with OIT to set up the build-server to automatically be restarted if it goes down.  In the process, they sent me a link to a web-based UI for monitoring processes, turning monitoring services on and off, and such.  The link is https://monitor.colorado.edu/nagios/, and identikey credentials are used to log in.  Once logged in, click on the "Services" link on the left side to see our processes.

@samreid, @jonathanolson, @jessegreenberg, @mattpen, and I currently are authorized, others can be added if needed.

We discussed this in the 3/31/2016 developer meeting and some questions arose.  This issue is being created as a place to track such questions and answers.

Two initial questions:
+ (JB) If someone wants to work on the build server, and wants to take the the process and not have it get automatically restarted, is the "Schedule downtime for this service" the best link to use?  Will it actually take the service down?
+ (JO) Does this use init.d to start and stop processes?

**Comment by jbphet** [comment]
I asked OIT the question about scheduling down time (see the comment just above).  In a nutshell, the answer is yes.  Here is the complete response:
> Yes, using the 'schedule downtime for this service' is the best option. I discourage using the 'disable notifications' because that can override settings in the monitoring config files, which can make troubleshooting difficult. Downtime always expires and is generally much easier to deal with.

**Comment by jbphet** [comment]
I also asked OIT about @jonathanolson's question concerning whether init.d is used.  Here is their response:

> Nagios only calls external programs. These can be init scripts, or scripts that invoke init scripts, but don't have to be. The generic event handler that we use does depend on init scripts to start and stop processes, but that was a design decision for the script that we put together, not a limitation of Nagios.
 
> Let me know if that answers your question. Thanks!

@jonathanolson - I think this addresses your question, assigning to you to confirm.

**Comment by jonathanolson** [comment]
Yes, answers the questions. Thanks!
