### ISSUE TITLE
Document PhET software design patterns related to TypeScript.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#170]
TS is going to result in revisions to existing PhET design patterns (e.g. options, enumeration), and will likely result in some new patterns.   These TS patterns should eventually be documented, as has been done for JS patterns in https://github.com/phetsims/phet-info/blob/master/doc/phet-software-design-patterns.md.  It's unclear whether they should be documented in that same .md file, in a new .md file,...  In any case, keep in mind that the JS patterns will be around for a while (maybe forever).

**Comment by pixelzoom** [comment]
@zepumph please add the `dev:typescript` label to this issue after you've created it.

**Comment by samreid** [comment]
@chrisklus and I discussed the need for a "conventions" document, which is different than a "design patterns" document and possibly also different than the "code review" doc.  I added a first draft from our collaboration above.

**Comment by zepumph** [comment]
I think it would be worth noting https://github.com/phetsims/ratio-and-proportion/issues/405, as most of these felt like "conventions" as opposed to patterns or syntax/code-style questions.

**Comment by samreid** [comment]
I added a few more entries to https://github.com/phetsims/phet-info/blob/master/doc/typescript-conventions.md

**Comment by samreid** [comment]
We have improved and elaborated on our TypeScript documentation in other issues, closing.
