### ISSUE TITLE
"Multiple Exports in One Expression" section of typescript-conventions is out of sync

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#173]
In Slack typescript channel, @samreid said:
> Changes in https://github.com/phetsims/chipper/issues/1156 require types to be exported separately from values using export type.  I’ve updated existing occurrences and turned on a tsconfig flag to prevent further occurrences.

This change now contradicts the [Multiple Exports in One Expression](https://github.com/phetsims/phet-info/blob/master/doc/typescript-conventions.md#multiple-exports-in-one-expression) section of typescript-conventions.md.

**Comment by pixelzoom** [comment]
Does this affect multiple imports at all?  See https://github.com/phetsims/phet-info/blob/master/doc/typescript-conventions.md#multiple-imports-in-one-expression.

**Comment by samreid** [comment]
I updated the documentation and clarified that the new constraint does not apply to imports.  @pixelzoom would you like to review?

**Comment by pixelzoom** [comment]
Mutliple problems with https://github.com/phetsims/phet-info/commit/ea66eb8e25d1890309e4ba1eca5db1554fa9ae7f:

* The bit about isolatedModules was Greek to me, and I suspect would be to anyone else. No mention of babel. If took me 15 minutes of research to understand what I think was trying to be said here.
* The examples were frankly useless, because I couldn't tell which identifiers were types vs non-types.
* The examples referred to "values", apparently copied from the enums discussion. This has nothing to do with enum values; it's a difference between types and non-types.

I revised the entire section in the commit above. @samreid please review.

**Comment by pixelzoom** [comment]
More fixes in the above commits.

**Comment by samreid** [comment]
Looks great, thanks!  Closing.
