### ISSUE TITLE
Create a Quickstart Guide for UI Sound.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#174]
Similar to https://github.com/phetsims/phet-info/issues/168 for alt input, we need a quickstart guide for UI sounds. 

Self assigning.

**Comment by pixelzoom** [comment]
First draft is completed. I'll announce on Slack.  @jbphet please review.

**Comment by jbphet** [comment]
The content looks reasonable, and I appreciate the effort that went into creating this, but I'm not entirely clear on how it relates to the existing documentation such as https://github.com/phetsims/tambo/blob/master/doc/adding-sound-to-a-sim.md and https://github.com/phetsims/tambo/blob/master/doc/user-guide.md.  There seems to be a fair amount of overlap between this doc and the "Adding Sound to a Sim" doc.  If the intention is to create a document that can enabled developers to turn on UI sound quickly without considering other aspects of the sound design, that's fine I suppose, but there should probably be a "Next Steps" section that tells the developers where to go (i.e. the other documents) to do a more complete job of adding sound to a sim.

**Comment by pixelzoom** [comment]
> The content looks reasonable, and I appreciate the effort that went into creating this, but I'm not entirely clear on how it relates to the existing documentation  ...

The problem is that I was never referred to either of the documents in tambo, and I had no idea that they existed. In retrospect, that seems really odd, since I was asking lots of questions when adding sound to Fourier, and it was clear that this was my first experience adding UI sounds. But that's water under the bridge.

I'm going to leave this where it's at, and let the sound team decide whether any bits of ui-sound-quickstart-guide.md should be rolled into the tambo doc.  And highly-recommended to let other devs know that the tambo doc exists. It looks nice and would have saved me a lot of time, both in implementation and in creating doc that I didn't know existed.

**Comment by jbphet** [comment]
I folded the non-redundant information from this doc into the "Adding Sound to a Sim" doc at https://github.com/phetsims/tambo/blob/master/doc/adding-sound-to-a-sim.md and removed this one.  Closing.
