### ISSUE TITLE
Can not run any simulation and can not build project with grunt tool 

### ISSUE THREAD

**Issue by hongson23** [phetsims/phet-info#175]
Hello
It seems to be have breaking change, I can not run any simulation
1. When I tried to run simulation with http-server, It is required some files in chipper's dist folder but I can not find any suggestions in document related to build dist folder in chipper project
![image](https://user-images.githubusercontent.com/4011696/144571979-58fb720e-7e7b-4671-96f1-c48c1d682d87.png)

2. Grunt build is required phet-io project but i can not find this repo
![image](https://user-images.githubusercontent.com/4011696/144571759-e2c5026e-46fa-412d-b314-01194cc1dbc1.png)

Please take a look,
Thanks

**Comment by samreid** [comment]
We have recently converted our codebase to TypeScript.  To convert the TypeScript files to JavaScript which can be run in the browser, please run `npm install` in `chipper/` then :

```
cd chipper
node js/scripts/transpile.js
```

Or, for faster iteration, you can enable a watch process:

```
cd chipper
node js/scripts/transpile.js --watch
```

**Comment by hongson23** [comment]
hello @samreid 
Thank for your answers. I tested follow your suggestions and everything worked well (both http-server for running and build the simulation into a single file)
Thanks

**Comment by samreid** [comment]
Excellent, thanks @hongson23 for reporting the problem and testing the new instructions.
