### ISSUE TITLE
Error: Cannot find module 'axios'

### ISSUE THREAD

**Issue by chrisklus** [phetsims/phet-info#178]
When @samreid and I were adding labels for a new repo in https://github.com/phetsims/center-and-spread/issues/2, we got this error:

```bash
chk@voyager:~/phetsims/phet-info/github-labels$ ./new-repo-add-labels.sh phetsims/center-and-spread
phetsims/center-and-spread

internal/modules/cjs/loader.js:1032
  throw err;
  ^

Error: Cannot find module 'axios'
Require stack:
- /Users/chk/phetsims/phet-info/github-labels/update-repos-list.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/Users/chk/phetsims/phet-info/github-labels/update-repos-list.js:8:15)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/chk/phetsims/phet-info/github-labels/update-repos-list.js'
  ]
}
For each repo, this script should print "200 OK", "201 Created" or "204 No Content" to indicate success.
"422 Unprocessable Entity" indicates an attempt to duplicate a label and can be ignored.
Path: https://api.github.com/repos/phetsims/center-and-spread/labels/invalid
Result (204 expected):
HTTP/2 204 
Path: https://api.github.com/repos/phetsims/center-and-spread/labels/wontfix
Data: {
  "name": "type:wontfix",
  "color": "ffffff"
}
Result (200 expected):
HTTP/2 200 
Path: https://api.github.com/repos/phetsims/center-and-spread/labels/question
Data: {
  "name": "type:question",
  "color": "EDCB62"
}
```

The labels seemed to add normally after the error, though.

Assigning to the responsible dev @zepumph.

**Comment by zepumph** [comment]
@samreid, can you check that this is the same fix here that you did for chipper's package?

https://github.com/phetsims/phet-info/blob/91574b2d8966552d9811df901caa0bfac9e3f694/github-labels/package.json#L3


I updated to the same version, perhaps you need to npm install and try to run the same command again. Ideally all the labels will say they are already created, but I worry we missed something else.

**Comment by jessegreenberg** [comment]
I just encountered this too when deleting a label. Script ran fine but hit the axios missing error.

**Comment by zepumph** [comment]
Yes, axios is imported from perennial, so we need to make sure that you npm update in grunt update. I have never run into this personally. We could also add axios to phet-info's package.json, but that feels even more prone to error, because no one would ever npm update there until the error occurred.

I'm tempted to close this issue, will everyone please reopen if we ever run into this again.
