### ISSUE TITLE
`new-repo-add-labels.sh` fails with "Cannot find module axios"

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#180]
I'm following the steps in https://github.com/phetsims/phet-info/blob/master/github-labels/README.md to add labels to a new sim repo.  It's failing with "Cannot find module axios".

```
% cd phet-info/github-labels/
% ./new-repo-add-labels.sh phetsims/geometric-optics-basics
phetsims/geometric-optics-basics
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'axios'
Require stack:
- /Users/cmalley/PhET/GitHub/phet-info/github-labels/update-repos-list.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/cmalley/PhET/GitHub/phet-info/github-labels/update-repos-list.js:8:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/cmalley/PhET/GitHub/phet-info/github-labels/update-repos-list.js'
  ]
}
...
```

**Comment by mattpen** [comment]
@pixelzoom - Can you try `npm install` in that directory and run the command again?  
- If that works I'll add that step to the documentation
- If it fails can you 
    - (a) list your node/npm versions here (`node -v && npm -v`) and 
    - (b) confirm that `node_modules/axios` exists in phetsims/phet-info/github-labels?

**Comment by pixelzoom** [comment]
I ran `npm install` in `phet-info/github-labels/`, and `node_modules/axios` exists after that.  That would definitely be a good step to add, since package.json typically lives at the top-level of repos, not in a subdirectory. 

The script now fails with a bunch of 401 errors, 

```
% node -v
v14.16.1
% npm -v
6.14.12
% cd phet-info/github-labels/
% ./new-repo-add-labels.sh phetsims/geometric-optics-basics
phetsims/geometric-optics-basics
(node:5884) UnhandledPromiseRejectionWarning: Error: Request failed with status code 401
    at createError (/Users/cmalley/PhET/GitHub/phet-info/github-labels/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/cmalley/PhET/GitHub/phet-info/github-labels/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/cmalley/PhET/GitHub/phet-info/github-labels/node_modules/axios/lib/adapters/http.js:269:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5884) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:5884) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
For each repo, this script should print "200 OK", "201 Created" or "204 No Content" to indicate success.
"422 Unprocessable Entity" indicates an attempt to duplicate a label and can be ignored.
Path: https://api.github.com/repos/phetsims/geometric-optics-basics/labels/invalid
Result (204 expected):
HTTP/2 401 
Path: https://api.github.com/repos/phetsims/geometric-optics-basics/labels/wontfix
Data: {
  "name": "type:wontfix",
  "color": "ffffff"
}
Result (200 expected):
HTTP/2 401 
Path: https://api.github.com/repos/phetsims/geometric-optics-basics/labels/question
Data: {
  "name": "type:question",
  "color": "EDCB62"
}
...
```

.... followed by many similar 401 errors.

**Comment by mattpen** [comment]
A [401 error](https://datatracker.ietf.org/doc/html/rfc7235#section-3.1) means that you are unauthorized. A 401 indicates that this is probably a problem with your credentials, as opposed to a change in permissions due to the recent github roles/teams update.

@pixelzoom - Can you confirm that you added your github username and PAT to build-local.json (as described in the [README](https://github.com/phetsims/phet-info/tree/master/github-labels#getting-started))? You can verify build-local.json is correct by running `node printGithubAuthorization.js` in the github-labels directory.

**Comment by pixelzoom** [comment]
Thanks, I'll check credentials.  I also had a potential credentials problem in https://github.com/phetsims/perennial/issues/262.

FYI, running the script also create an unversioned file in my local working copy: `phet-info/github-labels/.repos.old`.

**Comment by pixelzoom** [comment]
`node printGithubAuthorization.js` verifies that build-local.json is "correct".  But does correct mean that the PAT is valid?  Is there a script to validate the PAT?

**Comment by pixelzoom** [comment]
OK, thanks @mattpen.  I'll take it from here.

**Comment by pixelzoom** [comment]
Reminder to self that JG ran new-repo-add-labels.sh for me, so geometric-optics-basics now has a correct set of GitHub labels.

**Comment by pixelzoom** [comment]
In addition to not doing an `npm install`...  This was indeed a problem with my GitHub PAT. After putting a valid PAT in my build-local.json, the script succeeds.

Closing.
