### ISSUE TITLE
Clarify the new "Inclusive Design" section of the sim checklist.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#181]
Noticed when I created a new sim repo today.

In https://github.com/phetsims/phet-info/commit/7a55b189d6e89106fd1a7892c6902b6bd7a8c642, @amanda-phet added section a "Inclusive Features" section to https://github.com/phetsims/phet-info/blob/master/checklists/sim_checklist.md.   

The other sections are organized by role -- Design, Development, QA -- not by features.  This tells the people involves which section they are responsible for.  For example, I'm responsible for the Development section, and I can ignore the rest.  

This new section doesn't fit with that organization, so it's not clear who is responsible for the "Inclusive Features" checklist.  Please clarify and/or reorganize.

**Comment by amanda-phet** [comment]
That section has a set of checkboxes that might be completed by a designer or developer. We could certainly split the information into two different sections, but it seemed like it bridged the two. 

Would it help to have some text in the checklist that explains the section? Or maybe a larger team discussion about it? 

For reference, this is the issue where it was discussed: https://github.com/phetsims/phet-info/issues/176

**Comment by pixelzoom** [comment]
I'm not sure what the right thing to do is. This is my first time encountering it, and I don't know what to do with it.

**Comment by pixelzoom** [comment]
I'm not sure what the right thing to do is. This is my first time encountering it, and I don't know what to do with it.

I can say that completing this checklist is something that doesn't seem to be on everyone's radar.  So adding more things to it that are not clearly someone's responsibility would seem to be a problem.

**Comment by amanda-phet** [comment]
This was resolved in status quite a while ago.
