### ISSUE TITLE
Vestigial doc in github-labels/README.md ?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#182]
Is this paragraph in https://github.com/phetsims/phet-info/blob/master/github-labels/README.md still relevant? I don't see any list of repos in phet-info/github-labels/, and it looks like new-repo-add-labels.sh generates a list.

> **Why do we need the list of repos in github-labels/, could the script just depend on perennial/data/active-repos instead?**
> We do need two lists, because there are active repos missing from "active-repos". There are some repos, like website, which are active but very large and not collaborated on by all team members. Because active-repos is shared by the clone-missing-repos script, this creates a significant inconvenience in terms of storage.

**Comment by mattpen** [comment]
That's correct.  I removed that section, and also added information about the 401 error you got in #180.
