### ISSUE TITLE
92MB of conference videos

### ISSUE THREAD

**Issue by samreid** [phetsims/phet-info#185]
While cloning this repo, I was surprised to see that it takes much longer than other repos to clone, and the clone takes 92MB:

```
phet-info
Cloning into 'phet-info'...
remote: Enumerating objects: 9085, done.
remote: Counting objects: 100% (1699/1699), done.
remote: Compressing objects: 100% (1268/1268), done.
remote: Total 9085 (delta 1188), reused 751 (delta 422), pack-reused 7386
Receiving objects: 100% (9085/9085), 92.20 MiB | 4.05 MiB/s, done.
Resolving deltas: 100% (6092/6092), done.
Reinitialized existing Git repository in C:/Users/reids/document-root/phet-info/
```
This is much larger than our ordinary repos, for instance, QA is 3MB and vegas is 2.5MB.  I found that much of the size is due to videos in the conferences/ folder.  I also had deja-vu since I noticed this same thing back in the summer of 2018: https://github.com/phetsims/phet-info/issues/77

phet-info is self-described as:

> Collection of information shared by PhET team members for the purpose of using GitHub effectively and for other process-related topics.

So it's unclear that this is the appropriate place for 92MB of conference videos.  The last video was added 3 years ago.  Do we still use these?  Do they belong here?  Do we have a better place for them now?

Labeling for discussion at dev meeting.

**Comment by zepumph** [comment]
Potentiall a duplicate of #77

**Comment by zepumph** [comment]
From today's Dev meeting: KP will take a look at these and figure out if they are needed.

Do they need to be in the code base?

No, we all think they should be in a separate repo that isn't in active-repos. We can delete them and remove them from the git history of this repo once KP moves them. Assigning to @oliver-phet and @kathy-phet to discuss.

**Comment by kathy-phet** [comment]
@KatieWoe , Please make a phet-conferences repo (private) and move these video files over there.

**Comment by KatieWoe** [comment]
Items downloaded then uploaded to https://github.com/phetsims/phet-conferences. The two non-video files I wasn't sure how to download so I copied them into new files in the new repo.

**Comment by zepumph** [comment]
Looks great to me! @samreid, ready to remove from history.

**Comment by samreid** [comment]
To accomplish this, I followed the instructions at https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository and ran:

```
git clone https://github.com/phetsims/phet-info.git phet-info-fresh-clone
cd phet-info-fresh-clone/
git filter-repo --path-glob 'conferences/*.mp4' --invert-paths
git remote add origin https://github.com/phetsims/phet-info.git
git push origin --force --all
```

The output from that last command reads:

```
~/apache-document-root/main/phet-info-fresh-clone$ git push origin --force --all
Enumerating objects: 9294, done.
Counting objects: 100% (9294/9294), done.
Delta compression using up to 8 threads
Compressing objects: 100% (2890/2890), done.
Writing objects: 100% (9294/9294), 1.73 MiB | 481.00 KiB/s, done.
Total 9294 (delta 6191), reused 9294 (delta 6191), pack-reused 0
```

And it has been hanging for 3+ minutes.  I'll keep waiting just in case.

**Comment by samreid** [comment]
I tried running the BFG instead, like so:

```
/Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java -jar -jar ~/Downloads/bfg-1.14.0.jar --delete-files *.mp4
```

But the 

```
git push --force
```

failed with 

```
~/apache-document-root/main/phet-info-fresh-clone-3$ git push --force
Enumerating objects: 7894, done.
Counting objects: 100% (7894/7894), done.
Delta compression using up to 8 threads
Compressing objects: 100% (4261/4261), done.
Writing objects: 100% (7861/7861), 1.38 MiB | 425.00 KiB/s, done.
Total 7861 (delta 5344), reused 4007 (delta 3422), pack-reused 0
remote: Resolving deltas: 100% (5344/5344), completed with 21 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Cannot force-push to this protected branch
To https://github.com/phetsims/phet-info.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/phetsims/phet-info.git'
```

I'll reach out to @jessegreenberg for help since he is more aware of the branch protection rules.

**Comment by samreid** [comment]
I allowed myself to force push, then removed that ability.  A fresh clone reports this:

```
~/apache-document-root/main$ git clone https://github.com/phetsims/phet-info.git phet-info-fresh-clone-4
Cloning into 'phet-info-fresh-clone-4'...
remote: Enumerating objects: 9305, done.
remote: Counting objects: 100% (4802/4802), done.
remote: Compressing objects: 100% (2060/2060), done.
remote: Total 9305 (delta 2750), reused 4781 (delta 2731), pack-reused 4503
Receiving objects: 100% (9305/9305), 1.74 MiB | 5.60 MiB/s, done.
Resolving deltas: 100% (6213/6213), done.
```

Note it is 1.4MB instead of 92MB.

**Comment by samreid** [comment]
The repo looks as expected and clones in a fraction of the time.  Branch protection has been restored, and I took notes on the strategies in case we need to revise history again.  I'll write to slack dev-public to notify developers to reclone phet-info  there are no history mishaps.

**Comment by samreid** [comment]
I notified our slack `@channel`:

> The history for the repo phet-info has been rewritten.  (a) You may see some email notifications for commits with your GitHub username.  and more importantly, please (b) delete that repo via something like rm -rf phet-info and re-clone it (like clone-missing-repos so we do not run into problems with variations on the history.  Please do that before making more commits on that repo.
