### ISSUE TITLE
Option types and `optionize` should not use knowledge of the class hierarchy.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#187]
Something I've noticed about the application of PhET's new TypeScript options pattern...  

This example assumes that Node inherits from PhetioObject.  PhetioObjectOptions should be NodeOptions:

```
type MyClassOptions = Pick<Required<PhetioObjectOptions>, 'tandem'>;

class MyClass extends Node {
  constructor( providedOptions: MyClassOptions ) {
```

This example assumes that ScreenView inherits from PhetioObjectOptions. PhetioObjectOptions should be ScreenViewOptions:

```
class BANScreenView extends ScreenView {
  constructor( model: BANModel, providedOptions?: BuildANucleusScreenViewOptions ) {
    const options = optionize<BuildANucleusScreenViewOptions, BuildANucleusScreenViewSelfOptions, PhetioObjectOptions>( {
```

What's common to both of these examples is that they make assumptions about the class hierarchy, and use details about the implementation of the class hierarchy.   This is to be avoided, and is something that we should look for in code reviews.

In general:
* Option types should pick properties from the superclass, not ancestors of the superclass. 
* `optionize` should refer to only the current class and its superclass., not ancestors of the superclass.  

I'm not sure where this information should reside. Suggestions?

**Comment by samreid** [comment]
Geometric Optics demonstrates a pattern where options subtypes take the minimum essential options from the parent type.  For example:

```ts
type SelfOptions = {

  // Optional alternate position of the optical object, defaults to opticalObject.positionProperty.
  // This is used for the second point-of-interest on the framed objects.
  opticalObjectPositionProperty?: IReadOnlyProperty<Vector2>
};

export type OpticalImageOptions = SelfOptions & PickRequired<PhetioObjectOptions, 'tandem' | 'phetioDocumentation'>;
```

I tried to build a type to streamline this philosophy, and it looked like this:

```ts
type SparseExtends<Child, Parent,
  required extends keyof Parent = never,
  optional extends keyof Parent = never> = Child & Required<Pick<Parent, required>> & Partial<Pick<Parent, optional>>;
```

And would be used like so:

```ts
// 'tandem' and 'phetioDocumentation' are required
export type OpticalImageOptions = SparseExtends<SelfOptions, PhetioObjectOptions, 'tandem' | 'phetioDocumentation'>;
```

Note it also supports taking optional things in the 2nd arg:

```ts
// tandem is required, phetioDocumentation is optional
export type OpticalImageOptions = SparseExtends<SelfOptions, PhetioObjectOptions, 'tandem', 'phetioDocumentation'>;
```

The idea is to mimic the "class extends ..." pattern with options, so it is clear you don't jump in the hierarchy.  This could still be misused (by specifying the wrong ancestor), but hopefully it would make it easier to get things right.

**Comment by pixelzoom** [comment]
Nice idea, but I don't think I'd use it.  I very much prefer the current pattern. Here's why:

**Picking required only**: Comparing these examples, I don't feel like this is a big win. No less verbose. I prefer the current pattern.

```js
// current
SelfOptions & PickRequired<PhetioObjectOptions, 'tandem' | 'phetioDocumentation'>;

// proposed
SparseExtends<SelfOptions, PhetioObjectOptions, 'tandem' | 'phetioDocumentation'>;
```

**Picking optional only**: Comparing these examples, I'm not really sure what to provide for the 3rd type variable - I tried a variety of things.  In any case, having to specify "no required options" actually makes this case _more_ verbose.  So I prefer the current pattern.

```ts
// current
SelfOptions & PickOptional<NodeOptions, 'visibleProperty'>

// proposed
SparseExtends<SelfOptions, NodeOptions, ????, 'visibleProperty'>;
```

**Picking required and optional**: Comparing these examples, the proposal is a little less verbose.  But I think a common error will be to do `'tandem', 'visibleProperty'` when you meant to do `'tandem' | 'visibleProperty'  -- I do this all the time.  So I still prefer the current pattern, which makes it obvious what is required vs optional, and keeps  required and "optional separated.

```ts
// current
PickRequired<NodeOptions, 'tandem'> & PickOptional<NodeOptions, 'visibleProperty'>;

// proposed
SparseExtends<SelfOptions, NodeOptions, 'tandem', 'visibleProperty'>;
```

**Comment by pixelzoom** [comment]
See https://github.com/phetsims/phet-io/issues/1843#issuecomment-1060958804 for the 4 patterns for adding an ancestor option to an Options type.  Imo only 1 of these patterns is valid, the other 3 are anti-patterns.

**Comment by zepumph** [comment]
Noting as part of https://github.com/phetsims/chipper/issues/1128

**Comment by pixelzoom** [comment]
5/5/2022 dev meeting:  I'll add this to TypeScript Conventions doc.

**Comment by chrisklus** [comment]
From 5/9 supplemental TypeScript meeting, @zepumph volunteered to review this once @pixelzoom is finished. Thanks!

**Comment by pixelzoom** [comment]
Tracking this in https://github.com/phetsims/phet-info/issues/191.
