### ISSUE TITLE
Create a list of global keyboard shortcuts.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#188]
From [code_review_checklist.md](https://github.com/phetsims/phet-info/blob/master/checklists/code_review_checklist.md), aka the CRC:

> - [ ] Does this sim use specific keyboard shortcuts that overlap with global shortcuts? This includes the use of modifier keys like in [Unintended zoom/keyboard behavior ratio-and-proportion#287](https://github.com/phetsims/ratio-and-proportion/issues/287)

There's currently no "global shortcuts" list, and it's impractical to expect code reviewers (or even the sim developer) to search the code.  So a list would be useful during development, to prevent collisions in the first place. 

In Slack, @jessegreenberg said:
> We don't have a list like that, we need to make one.

In the meantime, I'll link this issue into the CRC.

**Comment by pixelzoom** [comment]
I'm also wondering...  Is a list of sim-specific shortcuts also needed?  When someone adds a new global shortcut, how do they know if it's already used by a sim?

**Comment by zepumph** [comment]
Ideally globalKeyStateTracker would have a way of registering particular ones in code, so we could assert if there was an overlap. I'm not sure how challenging that would be, or if it is futile to think that we can have all commands go through that channel. Worth that shot though!

**Comment by jessegreenberg** [comment]
Part of https://github.com/phetsims/scenery/issues/1298.

**Comment by kathy-phet** [comment]
Related to https://github.com/phetsims/scenery/issues/1298

**Comment by jessegreenberg** [comment]
Lets pick this up in scenery, an automated registry would involve or be used by KeyStateTracker and other classes in that repo. Closing this issue. I noted this issue in https://github.com/phetsims/scenery/issues/1445 and that if there isn't a good way to automate we can fall back to documentation.
