### ISSUE TITLE
Clarify "DT" checklist bullet item in code review checklist

### ISSUE THREAD

**Issue by andrewadare** [phetsims/phet-info#19]
In https://github.com/phetsims/phet-info/blob/master/checklists/code_review_checklist.md:

> Is DT capped appropriately? Try switching applications or browser tabs, then switch back. Did the model take one big/long/awkward step forward? If so, dt may need to be capped.

Might be useful to link to an example where this is done correctly. "DT" should not be capitalized in the first mention, and wouldn't hurt to use the word "timestep" (I'll fix)

**Comment by ariel-phet** [comment]
@andrewadare pinging on this issue

**Comment by andrewadare** [comment]
@jbphet, you explained some things about animation frame rates to me a while back. Is there an exemplary snippet of code you could point me to where this "capping" mentioned in the CRC is done properly? Is it a matter of adding in a delay to regulate the animation rate?

I'm happy to clarify the docs once I see a concrete example of how this is supposed to be implemented.

**Comment by jbphet** [comment]
The exact behavior is dependent on the sim, since some models are able to handle considerable variability in the time step and others are much more constrained.  Below is a smattering of examples from various sims.

From Gravity and Orbits:
```js
step: function( dt ) {

      // limit dt to 1 so there are no large jumps
      dt = Math.min( 1, dt );

      if ( this.playButtonPressedProperty.value ) {
        this.modeProperty.get().getClock().step( dt );
      }
    },
```

From Faraday's Law:
```js
    step: function( dt ) {
      // Cap large dt values, which can occur when the tab containing the sim had been hidden and then re-shown
      dt = Math.min( 0.1, dt );

      // step the individual model elements
      this.bottomCoil.step( dt );
      if ( this.showSecondCoil ) {
        this.topCoil.step( dt );
      }
      this.voltmeterModel.step( dt );
    },
```

From John Travoltage:

```js
    // Called by the animation loop
    step: function( dt ) {

      //Clamp dt, since navigating to another tab and back gives the particles an apparent burst of energy, see #25
      if ( dt > 2 / 60 ) {
        dt = 2 / 60;
      }

      .
      .
      .
```

From Neuron:
```js
    step: function( dt ) {

      // If the step is large, it probably means that the screen was hidden for a while, so just ignore it.
      if ( dt > 0.5 ) {
        return;
      }
      .
      .
      .
```

**Comment by andrewadare** [comment]
@jbphet this is great. Even just linking to this in the checklist would be a nice improvement. This issue is already tagged for the dev meeting, so we can discuss how best to convey this info.

**Comment by pixelzoom** [comment]
5/19/16 dev meeting:
I added an example to the check list. Closing.
