### ISSUE TITLE
Prefer `type` to `interface` in typescript-conventions.md.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#200]
In https://github.com/phetsims/chipper/issues/1280, we concluded that PhET should prefer `type` over `interface`.  That decision should probably be noted in https://github.com/phetsims/phet-info/blob/master/doc/typescript-conventions.md.

@samreid do you agree?

**Comment by samreid** [comment]
In https://github.com/phetsims/chipper/issues/1280 we enabled a lint rule that prevents `interface`, and I believe that rules we enforce via lint do not need to be repeated elsewhere.  What do you think?

**Comment by pixelzoom** [comment]
Oh right, I forgot that this was enforced by the lint rule.  And we don't add things that are enforced by lint rules to typescript-conventions.md, because that would be redundant.  So nothing to do, closing.
