### ISSUE TITLE
Should filenames use underscore or hyphen?

### ISSUE THREAD

**Issue by samreid** [phetsims/phet-info#201]
For instance, phet-info has:

checklists/
code_review_checklist.md
delete_repo_checklist.md
employee_leaving_checklist.md
external_library_checklist.md
new_repo_checklist.md
new_student_worker_checklist.md
postmortem_process.md
S2015R_checklist.md
sim_checklist.md
updating_metadata.md
youtube_upload_checklist.md

doc/
alternative-input-quickstart-guide.md
coding-conventions.md
devs-onboarding-pm-q4-2021.md
interactive-description-technical-guide.md
interactive-highlights-quickstart-guide.md
new-dev-onboarding.md
phet-dev-excercises.md
phet-development-overview.md
phet-software-design-patterns.md
supported-browsers.md
typescript-conventions.md
typescript-quick-start.md
typescript-webstorm-file-watcher.md

My instinctive, reflexive habit is to search for hyphenated filenames and it is frustrating that we have a subset of files that don't match this convention.

Raising for discussion at dev meeting.

**Comment by matthew-blackman** [comment]
We can use spaces in a file search, which will pull up files with either a hyphen or an underscore.

**Comment by veillette** [comment]
I have converted the filenames in phet-info to use hyphenated filenames.  I also searched for links in our common-code but I didn't get any hits.  All links appear to be internal to phet-info.

Work is done.   Closing
