### ISSUE TITLE
Dynamic Locales conversion documentation

### ISSUE THREAD

**Issue by marlitas** [phetsims/phet-info#202]
To track the creation of a quickstart guide for converting a sim to dynamic strings.

**Comment by marlitas** [comment]
I believe this document is done and is ready for review. It seems like @jonathanolson would be the best to review.

**Comment by jonathanolson** [comment]
Updated a few bits with the commit above, thoughts on the changes?

> Run with `?locales=*` to enable the locale-testing button (globe) in the navigation bar.

Is that currently needed? I tested, and it is not needed to be able to test (at the moment), due to how we load generated development strings.

Looks good, thanks!

**Comment by marlitas** [comment]
That looks vestigial. I went ahead and removed it. I think it looks good! Ready to close.
