### ISSUE TITLE
Create documentation for used hotkeys

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/phet-info#211]
From https://github.com/phetsims/scenery/issues/1445, we hoped to make an automated registry for global hotkeys. But that won't be worked on any time soon and may even be more trouble than it is worth. We should document key commands used in each sim/repo so it easy to make sure there are no overlaps.

Maybe the keys could be encoded in a machine readable way so that the data can be used for things like the Keyboard Help dialog. Otherwise we should manually document.

**Comment by terracoda** [comment]
This resource should be part of the documentation:
- This article on Medium, [J, K, or How to choose keyboard shortcuts for web applications](https://sashika.medium.com/j-k-or-how-to-choose-keyboard-shortcuts-for-web-applications-a7c3b7b408ee) is the article that helped me decide on the shortcuts we designed to jump the balloons to different locations in _Balloons and Static Electricity_.

**Comment by jessegreenberg** [comment]
A global "registry" for Hotkeys was implemented in https://github.com/phetsims/scenery/issues/1621. It catches Hotkey overlap at runtime. I am not sure yet how that relates to this issue.

**Comment by jessegreenberg** [comment]
Binder is now generating a list of used hotkeys in PhET sims through HotkeyData. Most of the work was done in https://github.com/phetsims/scenery/issues/1266. Closing.
