### ISSUE TITLE
Create documentation for making Preferences Menu screen reader accessible

### ISSUE THREAD

**Issue by terracoda** [phetsims/phet-info#213]
From https://github.com/phetsims/quadrilateral/issues/441

@jessegreenberg and I met to discuss a more general strategy for the on-boarding the team to making screen reader accessible a Preferences Menu.

- [x] @jessegreenberg will open a mark down file in phet-info repo, a quick start guide of some kind.
- [x] A link to that doc will be added to the Alternative Input documentation
- [x] @jessegreenberg will sketch out what is needed for devs
- [x] @terracoda will sketch out what is needed for designers, e.g. tips for designing the words that a voicing compatible and screen reader accessible.
- [x] Regarding the Localization Tab, first steps are to add names to the language buttons. Effort on making the UI for the Localization tab better (e.g. a giant combobox?)will need to be discussed further. JG & TS though just making sure that the buttons are associated with a language was a first good step.
- [ ] Add details about this to the QA testing documentation.
This comment might need to move to a new issue.

_Originally posted by @terracoda in https://github.com/phetsims/quadrilateral/issues/441#issuecomment-1587695561_

**Comment by jessegreenberg** [comment]
OK! I think dev related contents are pretty well in place at this point. @KatieWoe and @Nancy-Salpepi are aware and helped to add information to the QA book. Removing my assignment for now.

**Comment by terracoda** [comment]
The documentation does include tips for both devs and designers. The code examples don't look complete to me.

I can provide content for the examples, if this is deemed important.

**Comment by terracoda** [comment]
Oh, I just realized that Jesse and I determined the context responses for the provided examples were optional. 

The documentation is complete.
