### ISSUE TITLE
Update alternative-input-quickstart-guide.md to require Play Area and Control Area categories

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/phet-info#221]
During design meeting today we decided that the process for adding alt input to a sim will be to categorize components into play area and control area.

Lets update the documentation to reflect this. 
- [x] Create a Alternative Input Design Template (extracted from Description Design doc), similar to Sound Design Doc Template.
- [x] Update the alternative-input-quickstart-guide.md.
- [x] Add to an appropriate checklist to make sure this work is done.
- ~~Add to the QA process to make sure that components are correctly categorized into Play Area and Control Area.~~
- [x] Notify the entire team of this process change.

**Comment by jessegreenberg** [comment]
> Add to the QA process to make sure that components are correctly categorized into Play Area and Control Area.

On second thought, I don't really think this is necessary. This change is mostly a design process change but won't have any impact on alt input. QA tests alt input very well and we can avoid extra QA cost by not changing this.

**Comment by terracoda** [comment]
Agreed, as the only way to tell if it is implemented correctly is to use a screen reader, and that's not required for Alternative Input testing.

It is up to the designers and devs to ensure the Play Area / Control Area decisions get made.

**Comment by terracoda** [comment]
I created a sample Alternative Input Design document in the PhET Accessibility template folder. Sample place as other design doc templates.
