### ISSUE TITLE
Change the code review checklist details regarding dispose{{CLASS_NAME}}

### ISSUE THREAD

**Issue by samreid** [phetsims/phet-info#224]
Discovered during https://github.com/phetsims/density-buoyancy-common/issues/123

The code review checklist says:

> - [ ] All classes that require a `dispose` function should have one. This should expose a public `dispose` function that
  calls `this.dispose{{CLASS_NAME}}()`, where `dispose{{CLASS_NAME}}` is a private function declared in the
  constructor.  `{{CLASS_NAME}}` should exactly match the class name.

However, we no longer need to use `this.dispose{{CLASS_NAME}}()` and do not use this pattern any more. See for instance:
https://github.com/phetsims/models-of-the-hydrogen-atom/blob/f51bf6af4b2bfb07a7061815db49e40e72f5555a/js/common/model/Particle.ts#L83-L88
https://github.com/phetsims/density-buoyancy-common/blob/9b9e253515fc277e665e13f289525dbb5bf03e60/js/common/model/Mass.ts#L576-L594

Assigning to @pixelzoom since he authored that part of the code review checklist.

**Comment by pixelzoom** [comment]
> However, we no longer need to use this.dispose{{CLASS_NAME}}() and do not use this pattern any more.

I don't believe that to be true -- there are multiple valid patterns. You may not be using the `.dispose{{CLASS_NAME}}` pattern, but I prefer it when there are a lot of things to dispose (and encapsulate), rather than mutiple calls to `disposeEmitter.addListener`.   It's also fine to do what's shown in https://github.com/phetsims/models-of-the-hydrogen-atom/blob/f51bf6af4b2bfb07a7061815db49e40e72f5555a/js/common/model/Particle.ts#L83-L88. 

I'm fine with changing the checklist item to reflect the valid patterns.

**Comment by pixelzoom** [comment]
Feel free to revise, and I'll be happy to review.

**Comment by samreid** [comment]
Maybe something like this?

<details>

```diff
Subject: [PATCH] test
---
Index: checklists/code-review-checklist.md
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/checklists/code-review-checklist.md b/checklists/code-review-checklist.md
--- a/checklists/code-review-checklist.md	(revision 9397cdec33f3af2147a5b1e223f23ceaba301afd)
+++ b/checklists/code-review-checklist.md	(date 1722293421882)
@@ -86,9 +86,10 @@
     by `ObservableArrayDef.element*Emitter.removeListener`
   * SCENERY: `Node.addInputListener` is accompanied by `removeInputListener`
   * TANDEM: Creation of an instrumented `PhetioObject` is accompanied by `dispose`.
-- [ ] All classes that require a `dispose` function should have one. This should expose a public `dispose` function that
-  calls `this.dispose{{CLASS_NAME}}()`, where `dispose{{CLASS_NAME}}` is a private function declared in the
-  constructor.  `{{CLASS_NAME}}` should exactly match the class name.
+- [ ] All classes that require a `dispose` function should have one. There are many reasonable ways to implement 
+`dispose`, including but not limited to: (a) declaring a private function like `this.dispose{{CLASS_NAME}}()` in 
+the constructor, where `{{CLASS_NAME}}` should exactly match the class name. (b) Using Disposable.ts/disposeEmitter,
+(c) calling `super.dispose()` and `myChild.dispose()` etc.
 - [ ] All classes that do not properly override `dispose` should either (a) use `isDisposable: false`, or (b) implement
   a `dispose` method that calls `Disposable.assertNotDisposable`. Use (a) for classes that inherit a `dispose` method
   from Disposable. Use (b) for classes that inherit a `dispose` method from something other than Disposable. The goal

**Comment by pixelzoom** [comment]
That looks like a reasonable, concise summary.  If devs need more detailed examples, they can ask or search the code base.

**Comment by samreid** [comment]
I pushed the patch, closing.
