### ISSUE TITLE
should disabled UI components also be unpickable?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#24]
Noted during function-builder code review, phetsims/function-builder#55.

[code_review_checklist.md](https://github.com/phetsims/phet-info/blob/master/checklists/code_review_checklist.md) has this item:

> - [ ]  User interface components with enabled:false should also have pickable:false

A couple of potential problems with this...

(1) Does this correspond to what we want to do for a11y?
 
(2) If we indeed want to do this... In most cases, it should be handled by the common-code UI component, not by the client code.  I.e., enabling/disabling a UI component should automatically set pickable appropriately.

Labeling for discussion at developer meeting.

**Comment by pixelzoom** [comment]
@jessegreenberg Could you weigh in on question (1) above?

**Comment by jessegreenberg** [comment]
Good point @pixelzoom, for accessibility we will want enabled:false elements to still have pickable:true.  If an element is disabled, we will still want it to receive input events so that it can be found with whatever navigation strategy is used.

**Comment by pixelzoom** [comment]
Then perhaps https://github.com/phetsims/sun/issues/227 (Disabled components should not be pickable) is bogus?

**Comment by jessegreenberg** [comment]
Indeed, phetsims/sun#227 has been closed and we are going to proceed with making sure that common code components that can changed enabled state should still be pickable.

For now, I will remove "User interface components with enabled:false should also have pickable:false" from the checklist.

**Comment by jessegreenberg** [comment]
Removed and closing.
