### ISSUE TITLE
Tandem.validateOptions checklist item

### ISSUE THREAD

**Issue by andrewadare** [phetsims/phet-info#25]
This issue is about this checklist item:

> Does each new common code user interface component that was developed for this sim call Tandem.validateOptions immediately after the options are extended in the constructor? See https://github.com/phetsims/phet-io/issues/77

and, to some extent, the referenced PhET-iO issue.

It is not so clear to the code reviewer exactly how to systematically go about ensuring that all common code referenced in the sim has been outfitted with the check. If the sim happens to be one of the half-dozen that have a PhET-iO wrapper, the check is easy--just open the wrapper page with assertions enabled. In absence of that, though, checking all common code used in a sim is potentially a very big, tedious job.

Reading through https://github.com/phetsims/phet-io/issues/77 again, it seems to imply that this is most relevant for new common code developed for the sim. For example Drawer.js was added to scenery-phet in support of Function Builder.

Could we clarify the checklist with something to this effect, i.e. that *new* common code should be the focus? Otherwise, it's quite inefficient if everyone's effectively required to check the same common code over and over again.

@samreid what do you think? cc @pixelzoom

**Comment by andrewadare** [comment]
I just read the word new, right at the top. My apologies!

**Comment by andrewadare** [comment]
I'm going to make the word **new** nice and bold, and close this issue. Feel pretty dumb right now!

**Comment by andrewadare** [comment]
The CRC now says this:

> Does each new common code user interface component that was developed to support this sim call Tandem.validateOptions immediately after the options are extended in the constructor? See https://github.com/phetsims/phet-io/issues/77. If it is unclear which, if any, new common code components have been introduced for this sim, please contact the sim author(s).

**Comment by samreid** [comment]
Looks good @andrewadare, thanks!
