### ISSUE TITLE
move screenshot item from code review 

### ISSUE THREAD

**Issue by jbphet** [phetsims/phet-info#3]
@ariel-phet and I were discussing the code review checklist, and there is an item that says:

> Is the format of assets/*-screenshot.png correct? (2048x1344, PNG, 32-bit color) Has the browser chrome been stripped off of the screenshot?

Since the screenshots are generally not generated until the final stages of the project, often well after the code review, this item should probably go into the release checklist document.  @ariel-phet is apparently working on such a doc, so this issue is to remind him to move this checklist item when there exists somewhere else for it to go.

**Comment by ariel-phet** [comment]
Done, closing
