### ISSUE TITLE
Clean up sim_deploy docs.

### ISSUE THREAD

**Issue by samreid** [phetsims/phet-info#33]
See https://github.com/phetsims/phet-io/issues/673#issuecomment-253859543

Do we still need this section?

Variables to replace in the instructions below:

```
$SIM = the name of your sim's repo
$VERSION = the identifier of your sim, eg "1.0.0-rc.2"
$USERNAME = your username on spot, figaro, and phet-server
$HOME = your home directory
```

It looks like some docs don't use the majority of these.

**Comment by andrewadare** [comment]
I removed `$USERNAME` because it is no longer needed. The others are being used.

**Comment by zepumph** [comment]
@samreid and @andrewadare can this be closed then? Recognizing that most of the cleanup still to do will be done in #34.

**Comment by samreid** [comment]
The first lines of https://github.com/phetsims/phet-info/blob/master/deployment-info/doc/deploy-dev-phet.md are

Variables to replace in the instructions below:

```
$SIM = the name of your sim's repo
$VERSION = the identifier of your sim, eg "1.0.0-rc.2"
$HOME = your home directory
```

However, in that file, $SIM and $VERSION are not used at all, and $HOME is rather obvious in context: ``Your default build configuration is specified in `$HOME/.phet/build-local.json`.``  Can this be cleaned up any?

**Comment by pixelzoom** [comment]
@ariel-phet This has stalled, needs to be assigned to someone.

**Comment by zepumph** [comment]
I don't mind doing it.

**Comment by ariel-phet** [comment]
@zepumph have at it 🥇

**Comment by pixelzoom** [comment]
https://github.com/phetsims/phet-info/issues/40 may make this unnecessary.

**Comment by zepumph** [comment]
Closing, to be worked on in #40
