### ISSUE TITLE
Duplication in sim_deployment.md sourcefiles

### ISSUE THREAD

**Issue by samreid** [phetsims/phet-info#34]
There is a lot of duplicated information in the sim_deployment/src files.  For instance:

![image](https://cloud.githubusercontent.com/assets/679486/19614143/1562b01c-97af-11e6-8311-dc24fd466434.png)

and

![image](https://cloud.githubusercontent.com/assets/679486/19614151/2fcce1ac-97af-11e6-8868-8179e98a944c.png)

This creates a maintenance burden for updating the documentation and opportunities for them getting out of sync.  One idea I had to address this duplication would be to annotate lines with which brand they apply to:

```
Some step that applies to all brands.
[phet] Some step that only applies to the phet brand
[phet-io] Do some phet-io specific step
```

then a script can generate the phet or phet-io instructions by stripping out lines.

This duplication was introduced when @andrewadare and @zepumph worked on https://github.com/phetsims/phet-io/issues/673 so I'll assign this to them for comment.

**Comment by zepumph** [comment]
Unassigned myself to give time for people to see if it is worth spending more time on.

**Comment by samreid** [comment]
It would be nice if @pixelzoom can take a look and see if he has any recommendations, when he has time.

**Comment by pixelzoom** [comment]
I won't have time to look at this until Monday, 10/31.

**Comment by pixelzoom** [comment]
I don't get it.  What does all of this work do other than factor out preamble.md and build-process-configuration.md?   It seems like having a single .md document with section links at the top would be a whole lot simpler and just as effective.

**Comment by andrewadare** [comment]
> I don't get it. What does all of this work do other than factor out preamble.md and build-process-

It's for readability. Instead of clicking and scrolling through a single large file that covers every build case, you pick your doc and read the relevant instructions from top to bottom, with no noise.

**Comment by pixelzoom** [comment]
How many tasks are there? Even if there are 10, you could put 10 links at the top of the document that navigate immediately to the task that you're interested in.

**Comment by zepumph** [comment]
@pixelzoom the thought is that 90% of all 10 of those tasks are the same, with just a bit of difference here and there. So if we change something to the main build process, we have to change it 10 times. Does that make sense?

**Comment by ariel-phet** [comment]
@pixelzoom echoing @zepumph the thought was for better maintainability, just change things in one place and not skip it somewhere.

**Comment by andrewadare** [comment]
> How many tasks are there?

6.

> Even if there are 10, you could put 10 links at the top of the document that navigate immediately to the task that you're interested in.

This is exactly what we already have at [sim_deployment.md](https://github.com/phetsims/phet-info/blob/master/deployment-info/sim_deployment.md) - the links are just in their own file.

**Comment by pixelzoom** [comment]
Got it.

Recommended to replace 'release' with 'production' in file names. And we speak of 'dev' and 'production' releases, and the grunt tasks are `deploy-dev` and `deploy-production` respectively, not `deploy-release`.  Also consider replacing "public" with "production" in the text of those same files, for similar reason.

**Comment by andrewadare** [comment]
Renaming was carried out as suggested. As an aside, the original basis for this issue is less of a concern now - the disparity between the phet brand and phet-io brand is wider now. (I though it would be fun to compute the Levenshtein distance between the pairs as a function of history, but I should do that on my own time.)

Is there anything left to do for this issue?

**Comment by pixelzoom** [comment]
@samreid I realize that we're reevaluating the doc structure in https://github.com/phetsims/phet-info/issues/40.  But can this issue be closed?

**Comment by zepumph** [comment]
Sounds good to me. Let's carry on the sim_deployment conversation there.
