### ISSUE TITLE
Add warning to rc-phet in deployment info about fully tested shas 

### ISSUE THREAD

**Issue by zepumph** [phetsims/phet-info#35]
Working with @samreid on phetsims/phet-io#724 we noticed that fully tested shas may only have some of the common code libraries in it. Perhaps there needs to be a better way that just a published sim, to keep track of all of the fully vetted shas.

**Comment by pixelzoom** [comment]
In light of https://github.com/phetsims/phet-info/issues/39... This needs to be assigned, rather than wait for someone to hit it.

@zepumph we'll start with you. Assign to someone else as appropriate.

**Comment by zepumph** [comment]
This has been added to the new deploy docs:

>Keep in mind these SHAs may not include all of the repos for your sim, but you can still overwrite your dependencies with them, and the rest will be filled in with master during the build.

@pixelzoom do you think that more needs to be said?

**Comment by pixelzoom** [comment]
Looks good to me, closing.
