### ISSUE TITLE
Refine code_review_checklist.md

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/phet-info#36]
Since we are likely going to be adding items to this checklist in the near future, it might be good to review and trim a bit, and perhaps turn some things into lint rules.

**Comment by pixelzoom** [comment]
Since we're going to revisit and refine this over the course of (potentially) several developer meetings...

Here's a link to the checklist:
https://github.com/phetsims/phet-info/blob/master/checklists/code_review_checklist.md

And I'm changing the title of this issue, because it hurts my brain :)

**Comment by samreid** [comment]
We got through **Repository structure** today, join us again next time for "Coding Conventions".

**Comment by samreid** [comment]
Question: should "code style guidelines" be check-list-ified?

**Comment by andrewadare** [comment]
We got through the Coding Conventions, Math, and Doc sections. Next up: Organization, Readability,  Maintainability.

**Comment by samreid** [comment]
> Question: should "code style guidelines" be checklist-ified?

We decided to keep it separate.

**Comment by samreid** [comment]
At the end of the previous meeting, it was suggested that reviewing this as a group may not be an effective use of time.  I don't remember what alternate plan was decided upon.  (Perhaps splitting into a subgroup to work on this, or just refining it each time it is used).

**Comment by ariel-phet** [comment]
We decided to just keep refining each time is is used. Closing.
