### ISSUE TITLE
Add documentation here for generate-coverage

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/phet-info#38]

**Comment by jonathanolson** [comment]
@samreid, I don't see an obvious place in phet-info. What path were you expecting would contain this documentation?

**Comment by samreid** [comment]
How about: phet-info/docs/code-coverage.md

**Comment by jonathanolson** [comment]
Added documentation, does that look good?

**Comment by samreid** [comment]
Skimming through, it looks great.  I'd like to take it for a test drive, so I'll leave this assigned to me.

**Comment by samreid** [comment]
Works great @jonathanolson!  My test showed me that I neglected to tap the reset all button:

![image](https://cloud.githubusercontent.com/assets/679486/21000819/1383bade-bcda-11e6-973a-b7cdcf1ad219.png)

Docs are good, closing.
