### ISSUE TITLE
Remove any mentions to version.js in code_review_checklist.md

### ISSUE THREAD

**Issue by bereaphysics** [phetsims/phet-info#4]
There are three mentions of version.js in https://github.com/phetsims/phet-info/blob/master/code_review_checklist.md

version.js has been eliminated

**Comment by pixelzoom** [comment]
I'll take care of this.

**Comment by pixelzoom** [comment]
I removed references to version.js from the check list. I also fixed the location of the English strings file, since that has changed.

Closing.
