### ISSUE TITLE
new label for sonification

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/phet-info#41]
Future work with Georgia Tech will create issues related to sonification, and there are several issues in john-travoltage related to the sonification work that has been done already.

@mattpen would you mind creating a new label and applying it to all repos called ```dev:sonification```?  I noticed that ```meeting:sonification``` was already added.

**Comment by mattpen** [comment]
@jessegreenberg - What is the hexcode for the color that you would like to use?

**Comment by jessegreenberg** [comment]
@mattpen would #005C5F be acceptable?  Its bluish, similar to a11y but a bit darker?

**Comment by mattpen** [comment]
@jessegreenberg - It should be up now.  I checked a couple of repos to confirm, please reopen if you see it missing anywhere its needed.

**Comment by jessegreenberg** [comment]
Thanks @mattpen, it is in the repos!  But it looks like the label might be mispelled, in balloons-and-static-electricity, it is ```label:sonificaion```(missing the 't' in 'tion').

**Comment by mattpen** [comment]
I'll get that corrected, sorry.

**Comment by mattpen** [comment]
@jessegreenberg - It should be fixed now.  Can you check and confirm?

**Comment by jessegreenberg** [comment]
Looks great @mattpen, it is correct now, even for the labels I have already applied (Yay!) Thanks!
