### ISSUE TITLE
memory leak testing must be done with PhET-iO enabled

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#43]
Instrumenting a sim for PhET-iO involves adding tandems that are registered, and must be deregistered for anything that doesn't exist for the lifetime of the sim.  Any sim that has been instrumented must therefore be tested for memory leaks with PhET-iO enabled.  The code-review checklist should be modified to indicate this.

**Comment by jonathanolson** [comment]
Continuous testing should potentially be able to fuzz sims in phet-io mode, testing for memory leak patterns (presumably query parameter enables monitoring on Chrome, fires off a postMessage after a certain amount of time with pass/fail).

**Comment by samreid** [comment]
@zepumph and I wrote a QUnit phet-io test harness that tests sims and wrapper functionality.  Would be good to get this in the central test suite.

**Comment by samreid** [comment]
I added notes to the checklists, @pixelzoom would you like to review the 3 preceding commits and comment?

**Comment by pixelzoom** [comment]
Looks ok.  But I'm starting to drown in checklists and "how to" documents, so I won't know for sure until I need to go through the process again.
