### ISSUE TITLE
Create a setup markdown for IDEA Intellij

### ISSUE THREAD

**Issue by zepumph** [phetsims/phet-info#45]
From a skype conversation and @andrea-phet wanting to set it up for herself. It would be good to have a resource to point people to.

Place to live and call it:
`/phet-info/ide/idea/setup.md`?

Content (thanks @pixelzoom):
+ If you already have a directory where your repos are cloned...  Create an IDEA project in the same directory.  Then under Preferences > Version Control, add each of the repo directories.
+ File > Project Structure > Modules lets you exclude directories from your search path.  You typically want to exclude build/ and node_modules/ for each repository, and all of sherpa.
+ You'll also need to install the phet-info/ide/idea/phet-idea-codestyle.xml (the PhET code style).
+ Set up eslint: 
   * File > Settings . . . 
   * Then navigate to Language & Frameworks > JavaScript > Code Quality Tools > ESLint. 
   * Find your node.exe file (probably set up through the project).
   * Fill out ESLint package location (unless global, chipper/node_modules/eslint)
   * Configuration file should be `chipper/eslint/.eslintrc ` 
   * Additional Rules Dir should be `chipper/eslint/rules`
   * A picture for mac: 
![image](https://cloud.githubusercontent.com/assets/6856943/26806694/876bdad6-4a0f-11e7-9096-e734bf70be6e.png)

**Comment by zepumph** [comment]
@pixelzoom on skype:
Chris Malley
On Mac, phet-idea-codestyle.xml must be manually copied to $HOME/Library/Preferences/IntelliJIdea2016.3/codestyles/.  Restart IDEA, then you can choose it from Preferences > Editor > Code Style.
(if you have a different version of IDEA, then IntelliJIdea2016.3/ subdirectory will be different)

**Comment by veillette** [comment]
-Fill out your github credentials under 

File > Settings> Version Control > GitHub
and test your github credentials wit the test button

-Set the the right margin to appear after 120 characters

File> Settings> Editor > CodeStyle
Set Default Options to 120

**Comment by veillette** [comment]
Also for point 6. 

Configure node. File > Settings > Language & Frameworks > JavaScript Make sure you are using ECMAScript 5.1 is Selected, 
Select Prefer Strict mode.

**Comment by zepumph** [comment]
Thanks, those are all good suggestions.
