### ISSUE TITLE
Add conditional short circuiting to code review and style guidelines

### ISSUE THREAD

**Issue by zepumph** [phetsims/phet-info#46]
@samreid  @pixelzoom and @jonathanolson like this cool way of doing simple conditionals. This is idiomatic to the project, although not much of a saver on space (3 lines to 1).

Some examples: 
```
( expression ) && statement;
      ( expression ) ? statement1 : statement2;
( screen && screen.model.step && dt ) && screen.model.step( dt );
if ( screen && screen.model.step && dt ) { screen.model.step( dt ); }
( foo && bar ) ? this.fill = 'red' : this.fill = 'blue';
this.fill = ( foo && bar ) ? 'red' : 'blue';
```

**Comment by pixelzoom** [comment]
To clarify....  I seldom do this, except for `assert && assert( ... )`.   And @jonathanolson said he rarely uses this style.   So this seems to be a preference of @samreid.   I'm OK with it, but I don't think it's a good reason to change existing code.

**Comment by samreid** [comment]
Also, @pixelzoom pointed out that parentheses are only necessary if there is a compound expression.  For instance:

```js
// single-term expression doesn't require parentheses
foo ? bar: baz;
foo && bar();

// multiple-term expression requires parentheses
(foo && zoo) ? bar: baz;
(foo && zoo) && bar();
```

**Comment by zepumph** [comment]
I added a section to the development overview:

```
It is not uncommon to use conditional shorthand and short circuiting for invocation. 
 
( expression ) && statement;
( expression ) ? statement1 : statement2;
( foo && bar ) ? fooBar() : fooCat();
( foo && bar ) && fooBar();
( foo && !(bar && fooBar)) && nowIAmConfused();
this.fill = ( foo && bar ) ? ‘red’ : ‘blue’; 
 
 
If the expression is only one item, the parentheses can be omitted. This is the most common use case.
 
assert && assert( happy, ‘Why aren\’t you happy?’ );
happy && smile();
var thoughts = happy ? ‘I am happy’ : ‘I am not happy :(’;

**Comment by zepumph** [comment]
One of the bullets in the code review checklist under "Coding Conventions" is
- [ ] Does the code meet PhET's code-style guidelines, as described in the [“Coding Style Guidelines” section of the "PhET Development Overview"]()

I think it is enough to just have the section in the code-style guidelines? That seems like the best place for it.

**Comment by zepumph** [comment]
The above two comments are now in the code review checklist. Closing
