### ISSUE TITLE
keeping responsible_dev.md up to date

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#51]
@ariel-phet created [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md), a list of published sims and their primary developers.  Expression Exchange was published recently, and the list was not updated.  [sim_new_checklist.md](https://github.com/phetsims/phet-info/blob/master/checklists/sim_new_checklist.md) needs to be updated with an item something like:

> - [ ] Add the simulation to [sim_new_checklist.md](https://github.com/phetsims/phet-info/blob/master/checklists/sim_new_checklist.md).

Two possibilities:

(1) Add this under "Implementation" items, immediately after "README.md updated ..." 

(2) Make this a list of _all_ sims (published and unpublished) and add to "Implementation" items under "Repository created" subheading.

I have a slight preference for (2), since it will account for all sims, including those that may get shelved before publication.

**Comment by jonathanolson** [comment]
> Make this a list of all sims (published and unpublished)

Sounds good to me. How else would anyone know about Build a Molecule!

**Comment by pixelzoom** [comment]
Perhaps we should also add info about the lead designer?  

Skype discussion:
[7/3/17, 1:50:15 PM] Michael Kauzmann: How do I find out the designer of a sim?
[7/3/17, 1:50:38 PM] Chris Malley: Ha! I was going to suggest that be added to the doc that AP created.
[7/3/17, 1:51:00 PM] Chris Malley: your current method (or function:) is to look at credits.
[7/3/17, 1:51:22 PM] Michael Kauzmann: lol, ok will do. Perhaps I will also ping him to see if we want to update that list.
[7/3/17, 1:52:10 PM] Jonathan Olson: Presumably we'd have "active designer in charge"?

**Comment by zepumph** [comment]
@ariel-phet for example, I want to run a color change by someone for RIAW in https://github.com/phetsims/resistance-in-a-wire/issues/88. I updated the thumb color.

**Comment by zepumph** [comment]
@ariel-phet and I figured it out. I don't think that we need this column in the design doc anymore.

**Comment by ariel-phet** [comment]
Added to checklists, need to amend all open master checklists

**Comment by pixelzoom** [comment]
Open master checklists:
https://github.com/search?utf8=✓&q=is%3Aissue+user%3Aphetsims+sort%3Acreated-asc+is%3Aopen+%22master+checklist%22&type=Issues

**Comment by ariel-phet** [comment]
Relevant master checklists updated, some others need to be brought up to the modern checklist. Closing
