### ISSUE TITLE
redundant bullet item in "Step 6. Test the deployed version" 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#53]
From [sim_deployment.md](https://github.com/phetsims/phet-info/blob/master/deployment-info/sim_deployment.md):

>• **PHET_IO**:
Test using the index wrapper, located at {{SIM}}/{{VERSION}}/wrappers/index.
You will need a password. Verify that your password works.
Run Step 4, but for the published version. NOTE: A username and password are required to test deployed wrappers for phet-io versions. Ask a PhET developer for credentials.
> • Run Step 4, but for the published version. NOTE: A username and password are required to test deployed wrappers for phet-io versions. Ask a PhET developer for credentials.

The second bullet item seems redundant. Isn't it effectively identical to the bullet item before it?

Assigning to @samreid and @zepumph, since this is related to PhET-iO.

**Comment by zepumph** [comment]
This issue is stale, since chipper 2.0 I think this can be closed.
