### ISSUE TITLE
'grunt report-third-party' step is in the wrong place

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#54]
From [sim_deployment.md](https://github.com/phetsims/phet-info/blob/master/deployment-info/sim_deployment.md):

> **Step 7. Post-publication steps**
> ...
> • After the new simulation is available from the website, the 3rd party contributions page must be updated. Directions for how to do this are in chipper/js/grunt/reportThirdParty.js.

There's a problem with where this step currently lives.  It occurs before the "Restore your working copy" section.  So if you follow the instructions, you'll be attempting to push the modified `third-party-report.md` to a detached HEAD of sherpa.  

So this step probably needs to move to _after_ restoring your working copy.

**Comment by samreid** [comment]
Agreed this step should run after restoring working copy.

**Comment by pixelzoom** [comment]
Relocated the step. Closing.
