### ISSUE TITLE
"memory testing" in checklists?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#55]
Two questions related to memory testing for new sims:

(1) Should a “memory testing” issue be added to [sim_new_checklist.md](https://github.com/phetsims/phet-info/blob/master/checklists/sim_new_checklist.md), to be completed before code review? This would provide history of how memory was tested, identify/document the footprint of the sim, and ensure that no major code changes are needed after code review. E.g. https://github.com/phetsims/molecule-polarity/issues/33

(2) In [code_review_checklist.md](https://github.com/phetsims/phet-info/blob/master/checklists/code_review_checklist.md), "Memory Leaks" is the penultimate section in the checklist.  Since fixing memory leaks can often result in significant code (or even architectural) changes, perhaps this section should be moved towards the top of the checklist.

**Comment by pixelzoom** [comment]
This issue was motivated by https://github.com/phetsims/projectile-motion/issues/105. I'm about to start a code review, and there's no record of whether one has been done, and what the results were.

**Comment by jbphet** [comment]
I would vote yes for adding an item for memory testing prior to code review.  I think at two specific tests should be run:
- run controlled tests that likely to cause allocations, press reset, examine the heap snapshot to verify that the allocated references were garbage collected.  This should be done for each screen.
- run fuzz testing, take a sample after some initial fixed time to establish a base line (~1min), then take another snapshot later (~5min) and verify that memory usage stabilizes and doesn't continue to increase

...or something like that.

**Comment by samreid** [comment]
Can Bayes automatically collect memory usage statistics?

**Comment by pixelzoom** [comment]
Bayes (if it's even possible) might be useful for keeping memory issues from creeping into published sims.  But I'm not convinced that memory testing is appropriate for unpublished sims that are under development.

**Comment by samreid** [comment]
> But I'm not convinced that memory testing is appropriate for unpublished sims that are under development.

Maybe it's better to not create memory leaks as you go, since they are somewhat more difficult to track later on?  Also, Bayes wouldn't have to fail sims with large memory use.  Maybe we could just track memory usage as a function of sim version.  Also I'm not sure whether it's possible.  Is it using Chrome headless?

**Comment by phet-steele** [comment]
> Is it using Chrome headless?

Indeed.

**Comment by jonathanolson** [comment]
> Can Bayes automatically collect memory usage statistics?

Should technically be possible I believe.

> But I'm not convinced that memory testing is appropriate for unpublished sims that are under development.

> Maybe it's better to not create memory leaks as you go

To me, in-development sims should be linted, fuzzed, checked for memory leaks, and other tests should be run, so that things are caught and fixed early (instead of seeing a "finished" product and trying to find what broke things).

**Comment by pixelzoom** [comment]
@jonathanolson said:
> To me, in-development sims should be linted, fuzzed, checked for memory leaks, and other tests should be run, 

So I should never push anything that has a known memory leak, that I intend to fix?  If that's the case, you'll be getting a push from me once a day instead of 10-100 times per day.

**Comment by jonathanolson** [comment]
> So I should never push anything that has a known memory leak, that I intend to fix? If that's the case, you'll be getting a push from me once a day instead of 10-100 times per day.

I never meant for continuous testing to make warnings "unacceptable", but more of a reminder of "hey, something's broken". Presumably if you are aware of that in an in-development sim, it would be a case of "that warning will go away when I fully properly fix this code".

I'd recommend committing as you see appropriate.

**Comment by pixelzoom** [comment]
7/27/17 dev meeting:
Memory testing was moved towards the beginning of the code-review checklist, and this item was modified as follows:

> - [ ] Does a heap comparison using Chrome Developer Tools indicate a memory leak? (Describing this process is beyond the scope of this document.) There should be a GitHub issue showing the results of testing done by the primary developer.
