### ISSUE TITLE
fix version ids in master

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#56]
The majority of sims have incorrect version id's in master (package.json). This step in [sim_deployment.md](https://github.com/phetsims/phet-info/blob/master/deployment-info/sim_deployment.md) is apparently being skipped:

> • Update and commit the new correct version in package.json for master.  Basically, master should be set up for what would be the next release branch name.  So if you just created release branch 1.3, then the version should be 1.4.0-dev.0 in master.

For example, area-builder has a 1.1 branch, and package.json in master shows "1.1.0-dev.1", when it should be "1.2.0-dev.0".

These sims have a version id in master that corresponds to a release branch number, so they risk deploying something out of master that should be deployed out of the release branch.
- [x] area-builder @jbphet
- [x] bending-light @samreid 
- [x] charges-and-fields @jonathanolson 
- [x] energy-skate-park-basics @samreid 
- [x] faradays-law @jbphet 
- [x] forces-and-motion-basics @jessegreenberg 
- [x] fraction-matcher @samreid 
- [x] friction @jbphet 
- [x] gravity-and-orbits @jessegreenberg 
- [x] gravity-force-lab @jessegreenberg 
- [x] molecules-and-light @jessegreenberg 
- [x] molecule-shapes @jonathanolson 
- [x] neuron @jbphet 
- [x] projectile-motion @andrea-phet 
- [x] proportion-playground @jonathanolson 
- [x] trig-tour @jessegreenberg 
- [x] under-pressure @samreid 
- [x] wave-on-a-string @jonathanolson 

These sims look like they were reset to have a dev number of '1' in master (e.g. "1.2.0-dev.1") , so `grunt bump-version` may not do the right thing.  The dev number should be reset to '0' (e.g. "1.2.0-dev.0").
[EDIT: All of these handled by @pixelzoom.]
- [x] arithmetic @jbphet 
- [x] balancing-act @jbphet 
- [x] least-squares-regression @jonathanolson 
- [x] states-of-matter @jbphet 
- [x] states-of-matter-basic @jbphet 

Developers, please fix the sims for which you are responsible. See names next to sims in the above checklists.

**Comment by pixelzoom** [comment]
I updated the step in sim_deployment.md to read:

> Update the version id in package.json for master. Master should be set up for what would be the next release branch name. So if you just created release branch 1.3, then the version should be "1.4.0-dev.0" in master. (Note the "0" for the dev number, so that grunt bump-version works properly.)

... and moved it to the section where the release branch is created.

**Comment by pixelzoom** [comment]
@samreid yes, that's correct for bending-light.

**Comment by pixelzoom** [comment]
I fixed the ones that has a non-zero dev id, see above commits.   I decided which ones to fix by looking at the dev/html/ directory on spot.

**Comment by pixelzoom** [comment]
I fixed the ones that had a non-zero dev id, see above commits.   I decided which ones to fix by looking at the dev/html/ directory on spot. @jbphet @jonathanolson you may wish to review, since these were your sims.

**Comment by pixelzoom** [comment]
Developers, please fix the sims for which you are responsible.  See names next to sims in the above checklist.

**Comment by jessegreenberg** [comment]
Thanks, updated mine, removing assignment.

**Comment by jbphet** [comment]
I updated all the ones with my name above and checked them off the list, with the exception of faradays-law.  That sim has a 1.3-phetio branch, but that branch is way behind master, and there are a bunch of recent publications of dev versions with 1.3.x version IDs, so I'm not sure what's going on there.  My guess is that the version ID on master wasn't updated, so now new versions are coming out with misleading IDs.  Exactly the sort of thing that motivated @pixelzoom to log this issue, I suppose.  At any rate, I'm going to assign @zepumph  to investigate and fix things up for faradays-law, since he is the one that has been doing the recent releases.

I also updated projectile-motion, since @andrea-phet is pretty much out for potentially quite a while.

The changes by @pixelzoom for states-of-matter and states-of-matter-basics look good.

Finally, I also updated arithmetic and balancing-act.  I'd like @pixelzoom to check this, since he had said above that he had were updated them, but I didn't see the commits and they didn't appear to be correct.

**Comment by pixelzoom** [comment]
@jbphet said:
> Finally, I also updated arithmetic and balancing-act. I'd like @pixelzoom to check this, since he had said above that he had updated them, but I didn't see the commits and they didn't appear to be correct.

I said that those sims _may_ need updating. I decided which ones needed updating by looking at spot. arithmetic and balancing-act already had dev versions deployed (1.1.0-dev.1 and 1.2.0-dev.2) for the version id in package.json, so they did _not_ need to be updated.   @jbphet I've revert your changes in the above commits.

**Comment by pixelzoom** [comment]
I fixed @jonathanolson's sims. I figured that would be less expensive than having to discuss this at developer meeting.

**Comment by pixelzoom** [comment]
@jbphet said:
> I updated all the ones with my name above and checked them off the list, with the exception of faradays-law. That sim has a 1.3-phetio branch, but that branch is way behind master, and there are a bunch of recent publications of dev versions with 1.3.x version IDs, so I'm not sure what's going on there. My guess is that the version ID on master wasn't updated, so now new versions are coming out with misleading IDs. Exactly the sort of thing that motivated @pixelzoom to log this issue, I suppose. At any rate, I'm going to assign @zepumph to investigate and fix things up for faradays-law, since he is the one that has been doing the recent releases.

Yes, it looks like there have been 1.3.x deploys that should have been 1.4.x.  Not sure what to do about that  - probably nothing.  To prevent more of the same, I've bumped master to "1.4.0-dev.0".

Assigned to @zepumph to decide whether to do anything about the bogus 1.3.x deploys.  When you're done, feel free to close.

**Comment by zepumph** [comment]
>Yes, it looks like there have been 1.3.x deploys that should have been 1.4.x. Not sure what to do about that - probably nothing. To prevent more of the same, I've bumped master to "1.4.0-dev.0".

I'm sorry if I have confused the situation. I have used FL as a guinea pig in the recent past to test some build tool changes. None of them are worth much, nor do I think that it matters that they don't bare resemblance to the published version of the same minor version. I plan on not doing anything with these dev versions. I will be more cognizant in the future. Please reopen if anyone feels differently and I'm happy to take care of it in whatever way is fit. Thanks all.
