### ISSUE TITLE
add all sims to responsible_dev.md ?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#57]
I suggested this awhile back, but @ariel-phet had a strong preference (I don't recall specifics) that [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md) should include only published sims.  

Including only published sims creates a problem that has come up multiple times.  When we make changes to common code, that often requires fixes to many sims (both published and _unpublished_), to be handled by the responsible developer. 

The most recent example is https://github.com/phetsims/axon/issues/132#issuecomment-323404090.  I've been assigned to fix curve-fitting, which is an unpublished sim.  While I'm listed in the credits, I've made only minor changes/fixes in the past, and I'm not really familiar with this sim.  MLL and MV were the primary developers, both of whom are unavailable.  So there is confusion about who is the responsible developer. 

So I'm going to ask again... Why don't we include _all_ sims in responsible_dev.md?

If we decide to do this, then the [sim_new_checklist.md](https://github.com/phetsims/phet-info/blob/master/checklists/sim_new_checklist.md) should be modified.  Instead of adding a sim to responsible_dev.md after publication, it should be added after its repository is created.

**Comment by samreid** [comment]
I think it would be good to choose a responsible dev for published sims and sims that are planned to be published (or to clearly annotate that the responsible dev is TBD).  Abandoned sims do not need a responsible dev.

**Comment by jonathanolson** [comment]
I'd like to see every sim have a responsible developer, since sometimes we need to apply fixes across sims where each developer fixes "their sims". Having gaps for abandoned sims would hurt that.

**Comment by pixelzoom** [comment]
@jonathanolson said:
> Having gaps for abandoned sims would hurt that.

A note on abandoned or unassigned sims...  Having them listed in responsible_dev.md would be an advantage -- it would be clear which sims are in that state.  That's not at all clear currently.

**Comment by pixelzoom** [comment]
So to clarify... If a sim is in active-repos, it should be in responsible_dev.md.

**Comment by jonathanolson** [comment]
> So to clarify... If a sim is in active-repos, it should be in responsible_dev.md.

Yes, sounds good to me.

**Comment by jessegreenberg** [comment]
> If a sim is in active-repos, it should be in responsible_dev.md.

+1, would help clarify issue assignment or things like https://github.com/phetsims/axon/issues/132 and https://github.com/phetsims/axon/issues/102.

**Comment by samreid** [comment]
> So to clarify... If a sim is in active-repos, it should be in responsible_dev.md.

I was originally thinking active-runnables, but active-repos sounds even better.

**Comment by pixelzoom** [comment]
We have a quorum, so I've added all sims to [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md), and I've modified [sim_new_checklist.md](https://github.com/phetsims/phet-info/blob/master/checklists/sim_new_checklist.md) to add an entry when the sim's repo is created.

There are 9 sims that currently have no responsible developer, so I'll leave this open for review at dev meeting.  The sims to address are:

- [ ] Calculus Grapher
- [ ] Coulomb's Law
- [ ] Curve Fitting
- [ ] Fluid Pressure and Flow
- [ ] Function Finder
- [ ] Graphing Quadratics
- [ ] Gravity Force Lab: Basics
- [ ] Optics Lab
- [ ] Sugar and Salt Solutions

I suspect that some of the above will remain "unassigned", since they are currently skeletons.

**Comment by pixelzoom** [comment]
I also added a "Published" column, to indicate which sims have been published.

**Comment by pixelzoom** [comment]
8/24/17 dev meeting consensus:
Remaining sims in the above checklist don't have an associated developer. Recommendation was to have @ariel-phet assign a developer to each one, for the purposes of fixing breaking changes like https://github.com/phetsims/axon/issues/132#issuecomment-323404090.

**Comment by pixelzoom** [comment]
8/31/17 dev meeting:
@ariel-phet will finish this off, assigning developers to the remaining sims.

**Comment by ariel-phet** [comment]
responsible_dev reviewed and updated. Closing
