### ISSUE TITLE
Incorrect instructions in sim_deployment.md

### ISSUE THREAD

**Issue by samreid** [phetsims/phet-info#58]
https://github.com/phetsims/phet-info/edit/master/deployment-info/sim_deployment.md has 

Step 1 "RC First":

> Update the version id in package.json for master. Master should be set up for what would be the next release branch name. So if you just created release branch 1.3, then the version should be "1.4.0-dev.0" in master. (Note the "0" for the dev number, so that grunt bump-version works properly.)

But then there is a subsequent step "Step 2"

> Step 2. Update the version number in package.json

So can the first part be deleted?

**Comment by pixelzoom** [comment]
No, both are relevant. Step 1 deals with updating package.json in master when you are creating a release branch.  Step 2 deals with updating package.json in the branch that you're publishing from.

**Comment by samreid** [comment]
I see, thanks for explaining that they are different branches.
