### ISSUE TITLE
Create web-dev intern setup document

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/phet-info#6]
I've spent quite a bit of time setting up the 3 web-dev interns that have worked at PhET in the last year. I think it would be a good idea to create a document that goes through all the steps of getting the PhET code checked out, setting up IntelliJ, and setting up the website VM.

Do you think this is a good idea @ariel-phet? Would this repo be the place for that document? If so, go ahead and assign this to @phetsims/matt-p.

**Comment by ariel-phet** [comment]
@aaronsamuel137 - I think that is a very good idea. And yes, this seems like the correct repo for that document.

**Comment by mattpen** [comment]
Here is an initial draft.  I'll finish it up this week.  https://github.com/phetsims/phet-info/blob/master/web-dev-intern-setup.md

**Comment by mattpen** [comment]
@aaronsamuel137 I think this document is basically finished.  Can you think of anything else to add?

**Comment by aaronsamuel137** [comment]
Can you add the info I sent you in the email about setting up and ssh key and syncing the database with figaro?

**Comment by mattpen** [comment]
@aaronsamuel137 I added the db sync info today.

**Comment by aaronsamuel137** [comment]
Looks great, thanks for doing this! I would just check the markdown output by viewing the file on github. There are some newlines that aren't showing up properly.

**Comment by mattpen** [comment]
Oops.  I used single quotes instead of back-ticks.  It should look better now.

**Comment by aaronsamuel137** [comment]
Look great, thanks! Closing
