### ISSUE TITLE
use chipper or perennial versions of grunt task? 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#60]
In https://github.com/phetsims/unit-rates/issues/203, I ran into problems with deploying unit-rates.  @samreid pointed out that I was using the perennial version of `checkout-shas`, while [sim-deployment.md](https://github.com/phetsims/phet-info/blob/master/deployment-info/sim_deployment.md) says to use the chipper version. My understanding (from past discussions at dev meetings) is that we should be using the perennial versions, since they are supposed to handle `npm prune` and `npm update` - which has been the case in my past experience.  I ended up using the perennial version, but still had to manually do `npm prune` and `npm update`.

Labeling for developer meeting to clarify what we should be doing, and make sure we're all doing the same thing.  And we should update  [sim-deployment.md](https://github.com/phetsims/phet-info/blob/master/deployment-info/sim_deployment.md).

**Comment by jonathanolson** [comment]
The perennial version currently doesn't npm prune/update. Ideally the command-line version WOULD do this, but we'll need to check dependencies to make sure that doesn't affect the build-server.

**Comment by pixelzoom** [comment]
> The perennial version currently doesn't npm prune/update

Then remind me why we want to use the perennial version.

**Comment by pixelzoom** [comment]
10/19/17 dev meeting notes:
• perennial version was recommended because older versions of chipper may not work correctly.
• For now, use the chipper version, since it does npm install/update.  If you run into problems, use perennial version and do manual npm install/update.
• This will be handled automatically in chipper 2.0 under the "automate steps" directive.

**Comment by jonathanolson** [comment]
Chipper 2.0 now has the main checkout-shas logic in perennial, but forwards `grunt checkout-shas` requests made in the sim directory to perennial.

I'll detail the steps required to do so in https://github.com/phetsims/chipper/issues/616 for this.
