### ISSUE TITLE
 create a GitHub issue for each maintenance release 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#61]
The last several maintenance releases that I've had to do have not gone well.  Most recently, see https://github.com/phetsims/unit-rates/issues/203.  I invariably find that another developer has done a prior maintenance release for the sim. Determining why the prior maintenance was done, and what files were affected, becomes a time sink. 

Proposal: Going forward, track maintenance releases via a _sim-specific_ GitHub issue. The issue will identify what related issues the maintenance release is addressing.  Any and all manual changes to release-related files (package.json, dependencies.json,…) will be linked to the maintenance release issue.  Yes, this will be a pain for batch maintenance releases.  Add this as a step to [sim-deployment.md](https://github.com/phetsims/phet-info/blob/master/deployment-info/sim_deployment.md).

**Comment by jonathanolson** [comment]
> Yes, this will be a pain for batch maintenance releases.

So either we automate creating issues and tagging them (why would we need sim-specific issues in batch cases?), or the cost of batch maintenance releases goes way up.

**Comment by pixelzoom** [comment]
@jonathanolson asked:
> why would we need sim-specific issues in batch cases?

I'd be OK with a single batch-specific issue, as long as that issue and the associated version id are  identified in a commit message. I see commit messages with this general form in unit-rates 1.0:

> Bumping version to ${{VERISON_ID}} for ${{URLS_FOR_RELATED_GIT_HUB_ISSUES}}

Is this commit message automated, or is it up to the developer?

**Comment by pixelzoom** [comment]
10/19/17 dev meeting notes:

We'll do nothing for now, and hope things improve with chipper 2.0.  In the meantime, look at GitHub commits and/or Network view.

**Comment by Denz1994** [comment]
Perhaps we can use Milestones in the Git api to group issues for specific maintenance releases.
