### ISSUE TITLE
spaces before/after parentheses

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#62]
Question about https://github.com/phetsims/axon/commit/56c45e585f456b1237597c0346f0bf5bb94204f4#diff-5cb97461fb42ca69367a592653c72c9c ...

The sole change in that commit was to remove spaces before/after parentheses surrounding an expression.  I'm using phet-codestyle.xml with WebStorm 2017.2.5, and applying formatting does _not_ remove those spaces.   Why did your formatting remove them?   I also prefer having the spaces, since it's consistent with other "space before/after parentheses" usages in the PhET code style.

**Comment by samreid** [comment]
It appears that IDEA 2017.3 EAP introduced changes to the formatting rules.  In the settings, I checked spaces within "grouping parentheses"
![image](https://user-images.githubusercontent.com/679486/31922837-92a19f74-b834-11e7-8c7c-20c3305c5c11.png)
and it seemed to restore the whitespaces.

**Comment by samreid** [comment]
When I apply that rule in Bending Light (still with IDEA 2107.3 EAP), I see lots of changes like these:

![image](https://user-images.githubusercontent.com/679486/31922886-e258cbe6-b834-11e7-8f97-255d1d72a039.png)

Are those parens supposed to have spaces or not?

**Comment by pixelzoom** [comment]
> When I apply that rule in Bending Light ...

Sure looks like those are "grouping parentheses" and should have spaces.

**Comment by pixelzoom** [comment]
I don't see "Grouping parentheses" in WebStorm's code style preferences (looking under JavaScript). WebStorm appears to just ignore grouping parens and doesn't apply formatting, leaves them as they are, with or without spaces. I have the latest WebStorm.

**Comment by samreid** [comment]
I switched to WebStorm 2017.2.5, anything else to do for this issue?

**Comment by zepumph** [comment]
I am in this 2017.3 EAP and I'm having the same problem.

**Comment by pixelzoom** [comment]
WebStorm 2017.3 introduced code style changes, see https://confluence.jetbrains.com/display/IDEADEV/New+project+code+style+settings+format+in+2017.3.   Navigating to Preferences > Editor > Code Style > JavaScript > Spaces, I now see "Grouping parentheses", and it's unchecked for phet-idea-codestyle.

**Comment by pixelzoom** [comment]
I verified that checking "Grouping parenthesis" provides the desired behavior - spaces before/after parents in expression like `( x > 0 && y > 0 )`.

If I make this change to the PhET code style, I'll also be changing the format of the phet-idea-codestyle.xml, likely making it unusable by anyone using older versions of WebStorm (and IntelliJ).

@samreid @zepumph how to proceed?

**Comment by pixelzoom** [comment]
Hmmm....  `.idea/codeStyles/codeStyleConfig.xml` (new file) is apparently pointing to `phet-idea-codestyle.xml`.  So perhaps I can just update `phet-idea-codestyle.xml` ?

**Comment by pixelzoom** [comment]
On Mac, PhET codestyle lives at:
`${HOME}/Library/Preferences/WebStorm2017.3/codestyles/phet-idea-codestyle.xml`

**Comment by pixelzoom** [comment]
I changed only the "Grouping parentheses" check box, but a diff shows other changes:

```
% git diff phet-idea-codestyle.xml 
diff --git a/ide/idea/phet-idea-codestyle.xml b/ide/idea/phet-idea-codestyle.xml
index c53500b..97d600f 100644
--- a/ide/idea/phet-idea-codestyle.xml
+++ b/ide/idea/phet-idea-codestyle.xml
@@ -1,4 +1,4 @@
-<code_scheme name="phet-idea-codestyle">
+<code_scheme name="phet-idea-codestyle" version="173">
   <option name="CLASS_COUNT_TO_USE_IMPORT_ON_DEMAND" value="30" />
   <option name="NAMES_COUNT_TO_USE_IMPORT_ON_DEMAND" value="10" />
   <option name="IMPORT_LAYOUT_TABLE">
@@ -18,7 +18,6 @@
       <package name="" withSubpackages="true" static="true" />
     </value>
   </option>
-  <option name="RIGHT_MARGIN" value="150" />
   <option name="HTML_DO_NOT_ALIGN_CHILDREN_OF_MIN_LINES" value="200000" />
   <option name="ELSE_ON_NEW_LINE" value="true" />
   <option name="CATCH_ON_NEW_LINE" value="true" />
@@ -47,8 +46,10 @@
   <option name="DOWHILE_BRACE_FORCE" value="3" />
   <option name="WHILE_BRACE_FORCE" value="3" />
   <option name="FOR_BRACE_FORCE" value="3" />
+  <HTMLCodeStyleSettings>
```

**Comment by zepumph** [comment]
I too have other changes, that doesn't surprise me because changing things like margins will show up in this document. I think I tracked the XML line to be

`    <option name="SPACE_WITHIN_PARENTHESES" value="true" />`

In the `  <codeStyleSettings language="JavaScript">` tag. Can you confirm?

**Comment by zepumph** [comment]
To test I exported my settings with the Grouping Parenthesis checkbox checked, and then I exported again with it not checked. This line had changed.

**Comment by pixelzoom** [comment]
> I think I tracked the XML line to be
> 
> `    <option name="SPACE_WITHIN_PARENTHESES" value="true" />`
> 
> In the `  <codeStyleSettings language="JavaScript">` tag. Can you confirm?

yep.

**Comment by pixelzoom** [comment]
While `<option name="RIGHT_MARGIN" value="150" />`, I still see right margin set at 120, as described in `phet-info/ide/idea/setup.md`.   So I'm going to go ahead and commit the new `phet-idea-codestyle.xml`.

**Comment by zepumph** [comment]
I think that we should be able to add that line, but we should make sure it doesn't break an old version.

I happen to have 2017.2.5 sitting around, I tried importing a codestyle that included SPACE_WITHIN_PARETHESES into the old version, and things worked just fine. @pixelzoom I think you are good to commit that added auto formatting rule.

**Comment by pixelzoom** [comment]
@zepumph could you install the latest `phet-idea-codestyle.xml` and verify that it works for you?

**Comment by pixelzoom** [comment]
@zepumph said:
> I think that we should be able to add that line, but we should make sure it doesn't break an old version.

I'm not concerned with breaking old versions. There's no reason everyone can't update to latest.

**Comment by zepumph** [comment]
@pixelzoom please confirm that these autoformatting commits are correct and what PhET wants to go with.

**Comment by pixelzoom** [comment]
Based on what we decided on Slack, yes that looks correct - spaces before/after parens that surround expressions.

Eg, this:

`showHomeScreen: ( screens.length > 1 ) && homeScreen && ( initialScreen === 0 )`

not this:

`showHomeScreen: (screens.length > 1) && homeScreen && (initialScreen === 0)`

**Comment by pixelzoom** [comment]
Labeling for developer meeting to inform all WebStorm and IntelliJ users that they should move to latest version and install latest phet-idea-codestyle.xml.

**Comment by zepumph** [comment]
Mentioned in the dev meeting today. @jbphet wanted to make sure this doesn't affect JSON, I found that it doesn't. @jonathanolson hasn't been a part of this issue, but he uses Sublime and should be aware of this convention. Closing.
