### ISSUE TITLE
Document PhET String key conventions

### ISSUE THREAD

**Issue by zepumph** [phetsims/phet-info#63]
I was curious about our conventions for i18n string keys today, mainly because of .

After talking with devs it seems like @pixelzoom summed it up nicely:
```
Chris Malley [13:14] 
To summarize string key conventions:

(1) Key is generally camelcased value. Example: “Hello World” -> “helloWorld”

(2) Sim title is “{{REPO}}.title”. Example: “equality-explorer.title”

(3) Screen name keys have “screen.” prefix. Example: “screen.beersLawLab”

(4) Ignore myriad other “false” conventions, especially those that appear for sims ported from Java/Flash.


[13:14] 
And yes, this is written down somewhere. See comment immediately preceding this one :)
```

I think that these should go in a file somewhere in this repo, or maybe in the development overview; marking as low priority.

**Comment by pixelzoom** [comment]
Looks to me like these conventions are already documented.

Two of the three convention for string keys are mentioned in the [code review checklist](https://github.com/phetsims/phet-info/blob/master/checklists/code_review_checklist.md):

> - [ ] Make sure the string keys are all perfect - they are difficult to change after 1.0.0 is published. Strings keys should generally match their values, such as "binaryProbability": { "value": "Binary Probability" }.
> - [ ] String keys for screen names should have the general form "screen.{{screenName}}", e.g. "screen.lab".

The 3rd convention (sim title) is enforced by `grunt build` task. If you don't have "{{REPO}}.title", the task will fail with an error like this:

> Fatal error: Missing string: EQUALITY_EXPLORER/equality-explorer.title in equality-explorer for fallback locale: en

**Comment by zepumph** [comment]
@pixelzoom is it worth adding anything about ports in the first bullet you mentioned.

Do you have to keep old string keys from ports in order for the autoport translations to work? 

Do you think there is any more work to be done with this?

**Comment by pixelzoom** [comment]
@zepumph asked:
> @pixelzoom is it worth adding anything about ports in the first bullet you mentioned.

If we mention ports, it would be a new checklist item specific to ports.  Something that incorporates the information in the answer to your next question.

> Do you have to keep old string keys from ports in order for the autoport translations to work?

If you want to take advantage of ported string files, then you should leave the string keys in the ported string files unchanged.   Whether to use ported string files is a decision that we left up to individual developers (decision made in a developer meeting sometime in 2017).  I've generally chosen to ignore the ported string files, and require a fresh translation.

It's also worth noting that files in babel/autoport/{{REPO}} are supposed to be deleted after {{REPO}} is first published.   Unclear whether that's been happening.

> Do you think there is any more work to be done with this?

I don't feel the need for more documentation about this, but others might.

**Comment by pixelzoom** [comment]
I said:
> It's also worth noting that files in babel/autoport/{{REPO}} are supposed to be manually deleted after {{REPO}} is first published. Unclear whether that's been happening.

There are at least 3 cases where this has not happened.  See https://github.com/phetsims/pendulum-lab/issues/200, https://github.com/phetsims/faradays-law/issues/97, https://github.com/phetsims/circuit-construction-kit-dc/issues/170.

**Comment by zepumph** [comment]
Alright sounds good thanks, closing
