### ISSUE TITLE
scope of 'use strict' in WebStorm 2017.3

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#64]
After updating to WebStorm 2017.3, every .js file that I open warns "File is not in strict mode". For example:

![screenshot_429](https://user-images.githubusercontent.com/3046552/33403301-1930085a-d51d-11e7-96c6-a998ba7ea8ad.png)

Apparent the scope of `'use strict'` is now expected to be script (not function).  If I select "fix" from the menu, it adds `"use strict"` at the top of the file.  For example:

![screenshot_430](https://user-images.githubusercontent.com/3046552/33403370-628eece6-d51d-11e7-8ec6-3d1b5d4a2828.png)

Suggestions anyone? Should I just disable inspection?

**Comment by pixelzoom** [comment]
Should I just disable inspection?

**Comment by zepumph** [comment]
>Apparent the scope of 'use strict' is now expected to be script (not function).

Currently in my Webstorm 2018.5 and for many versions before this hasn't been a problem for me, it expects it at the function level. @pixelzoom is this still a problem for you? If not did you take steps to fix it?

**Comment by pixelzoom** [comment]
Seems to have been fixed in recent versions of WebStorm.  Closing.
