### ISSUE TITLE
modify IDEA setup instructions for chipper:2.0

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#66]
https://github.com/phetsims/phet-info/blob/master/ide/idea/setup.md says:

> 1. Make sure that you have cloned all of the repos into a directory. First clone `chipper/`, and then use `chipper/bin/clone-missing-repos.sh`.

Since data files `clone-missing-repos.sh` have moved to perennial, I believe this should change to  "First clone `perennial/`.

**Comment by pixelzoom** [comment]
I modified setup.md.  @jonathanolson can you think of any other instructions or checklists that might need a similar change?

**Comment by pixelzoom** [comment]
Ah... Looks like more stuff may need to change in setup.md.  E.g. "you may have to `npm install` in chipper

**Comment by jonathanolson** [comment]
Clarified a bit about npm install/prune/update in the above commit (had to renumber, so it looks like all lines changed).

@pixelzoom's changes look good, thanks!
