### ISSUE TITLE
modify "PhET Development Overview" for chipper 2.0

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#68]
[PhET Development Overview](https://docs.google.com/document/d/1Ys1EiwnqQGYuzGOcQSr4uXDes35mF1v1XhMZIl10nk8/edit#heading=h.otez332l59q9) appears to contain instructions that need to change, as the result of some things (shell scripts? grunt tasks?) moving from chipper to perennial. 

@ariel-phet I'm not certain about what needs to change (or when), so assigning to you to delegate.

**Comment by ariel-phet** [comment]
@pixelzoom I think the when is probably after our planned merge on Jan 16. Marking for dev meeting just to do a check in with relevant parties.

**Comment by samreid** [comment]
@ariel-phet asked if @Denz1994 could take a look through the PhET development overview, please update what you can and raise questions here if there are any parts you aren't sure how to update.

**Comment by samreid** [comment]
@oliver-phet will make sure @Denz1994 has write privileges on the doc

**Comment by pixelzoom** [comment]
I think the changes will mainly be where things have moved from chipper to perennial.

**Comment by Denz1994** [comment]
While following the steps in the "PhET Development Overview" I ran into a few errors along the way. Specifically, the `npm install -g grunt-cli` command seems to not globally install grunt as expected. I've run into this problem before and my workaround includes running `npm install` in the specific repo I am working in along with chipper and perennial. I've also included the `npm prune` and `npm update` as a part of the fix in accord with @samreid comment on slack:

 (01/17/18: 6:05pm EST) 

> I think we determined “npm prune” then “npm update” is safest (though “npm install” will often work)


@samreid I would suggest removing this `npm install -g grunt-cli` beacuse it hasn't worked for me, unless that isn't everyone's experience. Thoughts?

Also, some documentation explaining the chipper and perennial repos was added. A more detailed report is listed below.

ERROR:
```
denzells-mbp:simula-rasa denz1994$ grunt create-sim --name=GRUBHUB --author=DENZELL
grunt-cli: The grunt command line interface (v1.2.0)

Fatal error: Unable to find local grunt.

If you're seeing this message, grunt hasn't been installed locally to
your project. For more information about installing and configuring grunt,
please see the Getting Started guide:

http://gruntjs.com/getting-started
```

_Note:_ At step 6 of “Creating A New Sim” grunt seems not to be installed 

_Fix:_ In step 2 of “Getting Started (on OS X)” run this command: `git clone https://github.com/phetsims/perennial.git`
	
In step 3 of “Creating a New Sim” run:
```
cd ../perennial
npm install
npm prune
npm update
```
ERROR:
```
denzells-mbp:example-sim denz1994$ grunt
grunt-cli: The grunt command line interface (v1.2.0)

Fatal error: Unable to find local grunt.

If you're seeing this message, grunt hasn't been installed locally to
your project. For more information about installing and configuring grunt,
please see the Getting Started guide:

http://gruntjs.com/getting-started
```
Note: At step 8 of “Building + Testing (Windows and OS X)” grunt seems not to be installed.

Fix:
 In step 8 of “Building + Testing (Windows and OS X)” run
```
npm install
npm prune
npm update
grunt
```

DOCUMENTATION UPDATES:

Added documentation to Source Code and Dependencies
> Chipper: Tools for developing and building simulations.
> Perennial: Maintenance tools that won't change with different versions of chipper checked out

**Comment by pixelzoom** [comment]
@Denz1994 asked:
> @samreid I would suggest removing this `npm install -g grunt-cli` beacuse it hasn't worked for me, unless that isn't everyone's experience. Thoughts?

`npm install -g grunt-cli` globally installs the grunt CLI, /usr/local/bin/grunt, which you can confirm by typing `which grunt` in a bash shell.  It does _not_ install the grunt task runner, which it expects to be installed locally (using npm). See https://gruntjs.com/getting-started. 

If you're running `grunt` in perennial and seeing "Fatal error: Unable to find local grunt", then grunt is not installed locally for perennial.  I'd start by doing `rm -rf node_modules; npm install` to see if that fixes the problem. 

I agree that the `npm install -g grunt-cli` should be removed from the "Creating a New Sim" and "Building & Testing" sections of this document.  It doesn't belong there -- it needs to be run once, not for each new sim created, or each time you do a build.  But it should be included somewhere else, maybe in "Getting Started".

**Comment by samreid** [comment]
@Denz1994 I think @pixelzoom covered the main point, can you please specify and reassign to me if there's more for me to do in this issue?

**Comment by Denz1994** [comment]
Thanks, @samreid and @pixelzoom for the input. I reviewed the changes with @jonathanolson and corrected the documentation to reference Perennial where needed and added the above fixes to avoid potential errors as described above. Closing this issue as the changes have been approved by @jonathanolson.
