### ISSUE TITLE
Investigating if OIT has an enterprise solution for Slack

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/phet-info#70]
I wrote to OIT and was directed ot Eric Galyon (Associate Director: Messaging and Collaboration)

> Hi Eric,
> 
> Quite curious to hear if OIT is using slack, and if you have investigated the paid version at all.
> 
> Thanks!
> 
> Ariel

He replied:

> Hello Ariel,
> 
> Yes, on both 
> 
> Pockets of OIT do indeed use Slack.  We have also looked into what it would mean to deploy Slack as a more formal, campus wide service.  Unfortunately, it is currently cost and effort prohibitive.  Slack has known accessibility issues (though I haven't checked in about 3 months; they might have fixed them), becomes significantly expensive at scale (meaning we would need to create a funding and/or charge back model along with the oversight of that), and would require creating provisioning and maintenance processes.  Considering we have other very similar service offerings available, we are not currently planning any larger scale Slack efforts.
> 
> We are, however, working on deploying Microsoft Teams to campus.  It is similar to Slack but with several added benefits.  Microsoft Teams is already licenses as part of our Office 365 tenant.  We already have all 100,000+ CU Boulder accounts provisioned.  We have a very close relationship with Microsoft and are actively working with the Microsoft Teams developers to improve their own accessibility issues.  Plus, Microsoft Teams has nearly all the functionality of Slack with added integrations and features of other Microsoft Office products.  We are actively working on a project to deploy Teams to all of CU Boulder by the end of the Spring 2018 term.
> 
> If you would be interested in Microsoft Teams, we could provide a demonstration and discuss if your use would be suitable for our early adopters/beta type release, granting access prior to broad campus availability.
> 
> Let me know if you're interested.
> 
> Thanks,

Still curious about Slack, I replied

> Hi Eric,
> 
> Does anyone in OIT use the paid version of Slack?
>  At this point I don't think we have interest in MS teams. 

To which he said:

> Not that I am aware of.  As best I am aware, any group/team within OIT who has interest in paid Slack is being directed to either stay on the free version or move to Microsoft Teams.

**Comment by ariel-phet** [comment]
Marking for dev meeting just to see if anyone has interest in MS teams (I am guessing not)

**Comment by pixelzoom** [comment]
Besides the fact the Microsoft _still_ can't seem to do that anything that involves original ideas or not ripping off (or purchasing) the competition (["The first thing you'll notice about Microsoft Teams .... is that it looks and feels just like Slack."](https://www.pcmag.com/article/349274/microsoft-teams-vs-slack-whats-the-difference)) ...  The main advantage to Teams is integration with Office 365, which PhET (thankfully) goes not use. It's video services are built on Skype, and (if I recall correctly) problems with Skype were part of the motivation for moving to Slack.  The only advantage I can see would be access to full message history, assuming that CU gets some sort of site license.

**Comment by pixelzoom** [comment]
Also relevant:

(1) Microsoft Teams is a feature in Office 365, not a standalone product.  So you'll need to also commit to using (or at least installing) Office 365. See https://docs.microsoft.com/en-us/microsoftteams/teams-overview#microsoft-teams-and-office-365

> Teams is built on existing Microsoft technologies, woven together by Office 365 Groups. ... Out of the box, a team created in Teams will create an Office 365 Group, a SharePoint Online site (complete with a document library), and an Exchange Online group mailbox, which will be used by Teams to store information such as meeting invites. A team can be created using existing Office 365 Groups, allowing existing group memberships, and contents stored in SharePoint Online and Exchange Online to be ported to Teams.

(2) If you don't have an Office 365 license, you can't participate in a team. CU vendors (like PixelZoom) and outside organizations (like PhET-iO clients) don't qualify to use CU's Office 365 site license, so we won't be able to participate in PhET's teams. See http://www.zdnet.com/article/slack-versus-microsoft-teams-its-really-no-contest/:

> Slack customers aren't likely to switch to Microsoft Teams, because the Office 365 solution doesn't have any way of allowing people outside an organization to participate in a team. That feature is on the roadmap, but without it this is a product for internal teams only. ... As an Office 365 feature, Microsoft Teams is designed to keep its 85 million commercial customers in the family.

**Comment by ariel-phet** [comment]
Moving discussion to a separate issue and closing
