### ISSUE TITLE
Instructions for one-off creation possibly not quite correct

### ISSUE THREAD

**Issue by jbphet** [phetsims/phet-info#73]
I am working through the instructions in https://github.com/phetsims/phet-info/blob/master/deployment-info/chipper-2.0.md to deploy a one-off version of a sim.  There is a portion in the "One-off deployments" section that says:

> To deploy a one-off version:
> `grunt one-off --brands={{BRANDS}}`

I did this but got the error:

```
Fatal error: Perennial task failed:
AssertionError [ERR_ASSERTION]: Requires specifying a branch (one-off name) with --branch={{BRANCH}}
  at grunt.registerTask.wrapTask (C:\git-dev\perennial\js\grunt\Gruntfile.js:320:7)
  at Object.<anonymous> (C:\git-dev\perennial\js\grunt\Gruntfile.js:82:13)
  at Object.thisTask.fn (C:\git-dev\perennial\node_modules\grunt\lib\grunt\task.js:73:16)
  at Object.<anonymous> (C:\git-dev\perennial\node_modules\grunt\lib\util\task.js:294:30)
  at Task.runTaskFn (C:\git-dev\perennial\node_modules\grunt\lib\util\task.js:244:24)
  .
  .
  .
```

I added the branch spec, and it worked after that, so I suspect that the docs need updating.  I would make the modifications myself, but I thought it would be good to check with @jonathanolson that what I experienced is the desired behavior.

**Comment by jonathanolson** [comment]
Sorry about that! I just implemented branch detection (it looks at what you have checked out, if you don't specify `--branch`), so that the instructions should work (also noticed in https://github.com/phetsims/perennial/issues/75).

Let me know if that works?

**Comment by jbphet** [comment]
Sounds like a good idea.  I'm not likely to need to do this again for a long time, and the changes look reasonable, so I'm going to go ahead and close this.
