### ISSUE TITLE
Remove redundant github labels

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/phet-info#75]
At a May 30th developer meeting, we decided to remove some redundant labels. From the meeting notes:

 - keep “status:ready-for-review” 
 - remove “status:in-progress”, “status:ready-to-test”, and “fixed-pending-testing”
 - AP suggested having QA change the labels on existing issues for labels that will be removed.

@zepumph said that label removal isn't in the current API so this will probably be a manual task. We will need to change the ones that are being removed to "status:ready-for-review", then delete the ones that are being removed.

@ariel-phet can you please assign next steps from here?

**Comment by jessegreenberg** [comment]
Related to https://github.com/phetsims/phet-info/issues/74.

**Comment by mattpen** [comment]
@jjohnson5253 created a script to delete a label from all repos. We successfully ran the script for `status:ready-to-test` which had no remaining issues.  There are still 8 outstanding issues for the other 2 abels.

Remaining issues under `status:fixed-pending-testing` (5): https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+archived%3Afalse+user%3Aphetsims+label%3Astatus%3Afixed-pending-testing

Remaining issues under `status:in-progress` (3): https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+archived%3Afalse+user%3Aphetsims+label%3Astatus%3Ain-progress

@ariel-phet - who should be changing these labels?

**Comment by ariel-phet** [comment]
superseded by #312 - closing
