### ISSUE TITLE
phettest "build" should be updated for chipper 2.0

### ISSUE THREAD

**Issue by zepumph** [phetsims/phet-info#76]
Right now I see two problems:
1. It is only building adapted-from-phet brand. I don't think that we want to be building that, I would think instead the build button should build all supported brands, (maybe even adapted-from-phet last). 
2.  We also find that the link to the built sim pointing to http://phettest.colorado.edu/area-model-algebra/build/area-model-algebra_en.html, clearly a relic of chipper 1.0, as it should have `_phet` in it.

This isn't a high priority, but I do find myself wanting to build a sim on phettest.colorado.edu to show non devs what master is like every now and then.

**Comment by pixelzoom** [comment]
@zepumph is this issue still relevant?  And I'm not sure what changes you're asking for above.

**Comment by zepumph** [comment]
This was fixed by https://github.com/phetsims/phetmarks/issues/25. Thanks @pixelzoom.
