### ISSUE TITLE
Clarify comment punctuation recommendations

### ISSUE THREAD

**Issue by jbphet** [phetsims/phet-info#78]
I was reviewing some recent commits for blackbody-spectrum, and had a question about our comment punctuation policy.  The following Slack dialog ensued:

------

@jbphet [4:01 PM]
Code style question (because I'm reviewing @SaurabhTotey's comments to Blackbody): I thought a while ago we decided to not use caps and periods on single line comments.  I just looked at some of @pixelzoom's code from Equality Explorer, and he is mostly doing this.  Here is an example:

```js
moveTo: function( location ) {
  
  // cancel any pending callbacks
  this.animationStepCallback = null;
  this.animationCompletedCallback = null;
   
  // move immediately to the location
  this.destination = location;
  this.locationProperty.set( location );
}
```

But the code review checklist has the following example:

```js
  // Randomly choose an existing crystal to possibly bond to
  var crystal = this.crystals.get( _.random( this.crystals.length - 1 ) );

  // Find a good configuration to have the particles move toward
  var targetConfiguration = this.getTargetConfiguration( crystal );
```

Which is our policy, or do we care?  I've personally been using the former style.

@zepumph [4:03 PM]
I have always thought our policy is to capitalize and period if it is a sentence, and don't if it is a fragment.
"Randomly choose an existing crystal to possibly bond to" seems like it is a sentence so it needs a period?

@jessegreenberg [4:04 PM]
Same, I tend to use a fragment, but use capitals and periods when I need a sentence or more.

@jbphet [4:06 PM]
I would say all of the examples above qualify as full sentences in English, so are they not correctly adhering to what you've just said?

@zepumph [4:06 PM]
Seems so

>we decided to not use caps and periods on single line comments

I don't remember anything based on single/multi line comments.

------

It seems there is some confusion.  We should clarify, or decide that it doesn't matter, and update the code review checklist based on what we decide.

**Comment by jonathanolson** [comment]
I don't feel strongly either way, but I'm not excited about having to check all comments for this during a code review.

**Comment by pixelzoom** [comment]
I don't see any need for standardizing these aspects of comments.

**Comment by samreid** [comment]
It seems natural that sometimes we would use sentences and sometimes sentence fragments.  Each should be punctuated/capitalized accordingly.

**Comment by pixelzoom** [comment]
7/12/18 dev meeting:
What @samreid said in https://github.com/phetsims/phet-info/issues/78#issuecomment-404337066.
