### ISSUE TITLE
summary of grunt and build-local.json options needed

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#8]
After @phetsims/bereaphysics ran into some problems using the build tools, @ariel-phet suggested (via email) that we update https://github.com/phetsims/phet-info/blob/master/sim_deployment.md to include options for the grunt command line and build-local.json.   I replied:

“brand” and "buildServerAuthorizationCode” are just the tip of the iceberg.  There are many more options that can be specified on the command line and/or in $HOME/.phet/build-local.json.  And I don’t see any of them mentioned in sim_deployment.md.  Nor do I think that’s a good place to document them, since they’re liable to get out of sync with reality.  Ideally, sim_deployment.md should refer the reader to a source code file where options are enumerated.  But there currently is no single source file that enumerates all options — they are spread out across chipper (where build process lives) and perennial (where build-server lives).   And from a quick read of related source files, it’s unclear which options are command-line only, which ones are build-local.json only, and which can be specified in either place.

I don't have time to address this.

**Comment by pixelzoom** [comment]
1/12/16 dev meeting:
Add a line at the top, something like "read 'grunt --help' and ask another PhET developer how to set up build-local.son".

**Comment by pixelzoom** [comment]
I added the "Build process configuration" section in https://github.com/phetsims/phet-info/blob/master/sim_deployment.md, and cleaned up a few other things.

@ariel-phet If this is sufficient, please close. Otherwise provide additional instructions.

**Comment by ariel-phet** [comment]
Excellent thanks. Closing
