### ISSUE TITLE
problems with 'grunt rc'

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#80]
I encountered these problems when trying to deploy equality-explorer 1.0.0-rc.1, using the instructions in [chipper-2.0.md](https://github.com/phetsims/phet-info/blob/2adcd8f1fa5381ef459637bc7e4d1e52b96ef979/deployment-info/chipper-2.0.md#if-the-release-branch-does-not-yet-exist).

(1)  Instructions say "If you do not want to deploy an RC when creating the release branch", but give no instructions or prerequisites for when you already have a branch. (What does "version" need to be in package.json?  etc.) My 1.0 branch already existed, and I ran into problem after problem. (I finally bailed, deleted my 1.0 release branch, and let `grunt rc` create it.)  Either require that release branches be created via `grunt rc`, or describe what needs to be done when the branch already exists.  

(2)The instructions say "First, make sure you have checked out all of the repo SHAs that you intend to use for the release branch." But when I tried to use an existing 1.0 branch, it also used the dependencies.json that was there, _not_ what I had checked out in my working copy.  I (luckily) discovered this by running `status.sh`.  

(3) Failure messages from `grunt rc` are almost worthless.  (I have the same problem with `grunt dev` and `grunt production`, btw.) Examples:

`On branch master\nYour branch is up-to-date with 'origin/master'.\nnothing to commit, working tree clean\n` meant that I needed to revert package.json in master, because it couldn't increment the minor version number.

`at devSsh.then.catch.reason (/Users/cmalley/PhET/GitHub/perennial/js/common/devDirectoryExists.js:36:11)` meant that I didn't have VPN running.

(4) 1.0.0-rc.0 ???
When `grunt rc` creates the release branch, it really confusing to see it doing a bunch of stuff related to `1.0.0-rc.0` when you're expecting to be building `1.0.0-rc.1`.   Please put something in the documentation, or a message explaining what is going on in the output of `grunt rc`.

(5) Misleading message when `grunt rc` completes.
When `grunt rc` completes, it says:

```
Deployed: https://phet-dev.colorado.edu/html/equality-explorer/1.0.0-rc.1/phet/equality-explorer_en_phet.html
Please test!

Done.
```

... but it's not done, and can't be tested yet.  It's not done until the build server completes.

**Comment by pixelzoom** [comment]
Assigning to @ariel-phet to prioritize and assign.

**Comment by ariel-phet** [comment]
Since we will have a few more RC's coming up soon on new sims, it would be good to address these concerns in a timely fashion. Seems like most of these are documentation problems, and can be addressed fairly easily.

I imagine @jonathanolson is probably the most familiar to take care of this, but also assigning @mattpen if he has thoughts since he is also pretty familiar with build server (I believe)

**Comment by mattpen** [comment]
Removing assignment as these are all related to local grunt tasks (the artist formerly known as chipper), not the build-server.

**Comment by pixelzoom** [comment]
Assigning to @ariel-phet. He assigned this high priority on 7/13, and it's still open.

**Comment by jonathanolson** [comment]
I'm checking through what I need to change further.

**Comment by jonathanolson** [comment]
> (1) Instructions say "If you do not want to deploy an RC when creating the release branch", but give no instructions or prerequisites for when you already have a branch.

Updated documentation says:

> If you do not want to deploy an RC when creating the release branch, instead directly do `grunt create-release --branch=1.7` (which will handle all of the steps to create the new branch). Release branches should be created using either `grunt rc` or `grunt create-release`, as this sets them up with the correct package.json version and dependencies.json content.

> (2) The instructions say "First, make sure you have checked out all of the repo SHAs that you intend to use for the release branch." But when I tried to use an existing 1.0 branch, it also used the dependencies.json that was there, not what I had checked out in my working copy. I (luckily) discovered this by running status.sh.

If following from the (newer) directions, this would be avoided.

> at devSsh.then.catch.reason (/Users/cmalley/PhET/GitHub/perennial/js/common/devDirectoryExists.js:36:11) meant that I didn't have VPN running.

There is now an improved check for VPN that should fail out with a better message first.

> `On branch master\nYour branch is up-to-date with 'origin/master'.\nnothing to commit, working tree clean\n` meant that I needed to revert package.json in master, because it couldn't increment the minor version number.

I'm not sure how that works, if you have an unclean package.json then it should fail out with these initial checks:

```js
if ( !( await vpnCheck() ) ) {
  grunt.fail.fatal( 'VPN or being on campus is required for this build. Ensure VPN is enabled, or that you have access to phet-server.int.colorado.edu' );
}

const isClean = await gitIsClean( repo );
if ( !isClean ) {
  throw new Error( `Unclean status in ${repo}, cannot create release branch` );
}
```

> (4) 1.0.0-rc.0 ???

I've added the following documentation:

> NOTE: It will initialize the branch to a version of 1.0.0-rc.0, and then increment/deploy to 1.0.0-rc.1.

I believe that's best, as I don't particularly want to suppress information that could help for debugging. I wouldn't expect developers doing deploys to read through all of it.

> (5) Misleading message when grunt rc completes.

I believe the process now says:

> Please wait for the build-server to complete the deployment, and then test!

Is there anything else that should be fixed or improved here?

**Comment by pixelzoom** [comment]
Looks good, I think you've addressed everything.  Closing.
