### ISSUE TITLE
update code review checklist for ES6

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#81]
While doing code review of graphing-quadratics (see https://github.com/phetsims/graphing-quadratics/issues/7), I noted that there are things in the code review checklist that no longer make sense for ES6.  E.g. `@constructor` annotations for all constructor functions.  And there are undoubtedly additional items that we'll need to add for ES6.  So... The check list should (at some point) be reviewed and revised. 

Assigning to @ariel-phet to prioritize and assign.

**Comment by pixelzoom** [comment]
I don't mind doing this.  But other than reviewing Graphing Quadratics, I have zero experience with the ES6+ features that PhET has cleared for use.  I'm sure that I'll form an opinion about what should be in the checklist.  But that's going to happen later than sooner.

**Comment by pixelzoom** [comment]
Labeled for developer meeting, to discuss priority.

**Comment by jonathanolson** [comment]
It would be good sometime to nail down what our best practices are going forward with ES6 (both with Node.js code and sim code). Having devs who have worked with ES6+ a lot make recommendations would be nice.

**Comment by ariel-phet** [comment]
Closing issue, first we will have a discussion about best practices in ES6 and use that as a jump off point for improving/modifying code review checklist
