### ISSUE TITLE
Improve manual maintenance release instructions

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/phet-info#83]

**Comment by jonathanolson** [comment]
Updated the instructions since it was noted in Slack that they were insufficient. Can you check the above commit (new version at https://github.com/phetsims/phet-info/blob/master/deployment-info/chipper-2.0.md) and see if it looks better, or if there is anything to add?

**Comment by pixelzoom** [comment]
Much better, thanks for doing that.

I'm also finding it useful to note the steps that I used to create an RC in the issue, like https://github.com/phetsims/QA/issues/169#issuecomment-412681206.  I'll probably continue to do that until I no longer find it to be useful.
