### ISSUE TITLE
add an "s" to "block-publication" label

### ISSUE THREAD

**Issue by zepumph** [phetsims/phet-info#84]
In dev meeting today it was decided that we want to rename the label to be `status:blocks-publication`

I think the way to achieve this is to add the new one, add that label to all the issues that currently have the old one, and then remove the previous label

Assigning to myself and @mattpen. Whoever gets to it first is fair game.

I see that there is a "delete" script, but it isn't documented how to use it in the README. I'll make another issue for that.

**Comment by mattpen** [comment]
I think there is a change-label script for this purpose, but I'm not 100% sure. I can look at this when I return on Monday.

**Comment by zepumph** [comment]
Sounds good. I also didn't see a readme entry for that one, and looking into the file wasn't immediately obvious if just running that file was enough (I don't know about updating the master JSON and whatnot.

**Comment by mattpen** [comment]
I updated the script and the labels today.
