### ISSUE TITLE
Annotation for re-parentable Nodes

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/phet-info#87]
From https://github.com/phetsims/griddle/issues/32, we were deciding if griddle should be changed so that composite types were re-layerable, which was required (among other things) for use in energy-skate-park. I decided it wasn't worth it in that case, but @jonathanolson suggested

>We could potentially have certain components support re-parenting of certain children? For example, you'd document something as // @public {Node} (re-parentable), and that would make the guarantee that, as long as the parents for the main node (and all re-parentable children) were the same, that it would look correct.

>This is more general, assigning to the dev meeting to see if this idea is too crazy in general.

**Comment by samreid** [comment]
Reparenting seems like a workaround that has a "code smell"--we should try to avoid this pattern (which I understand to already be rare).  When this pattern is unavoidable it should be documented with more than an annotation.

**Comment by jessegreenberg** [comment]
Discussed during 12/27/18 -

Agreed that we should generally avoid this pattern. There are things like HeaterCoolerNode that do similar things already. HeaterCoolerNode assembles a HeaterCoolerFront and a HeaterCoolerBack, but if it needs to be re-layered the client can add a HeaterCoolerFront and a HeaterCoolerBack as they see fit without supporting a "re-layerable" feature.
