### ISSUE TITLE
flesh out phet-software-design-patterns.md

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#88]
Related to https://github.com/phetsims/tasks/issues/969#issuecomment-451265925

At 1/3/19 dev meeting, @ariel-phet suggested that we should spend the next couple weeks of "core hours" reviewing PhET-specific design patterns. @zepumph suggested that someone should evaluate the state of [phet-software-design-patterns.md](https://github.com/phetsims/phet-info/blob/master/doc/phet-software-design-patterns.md), and @ariel-phet asked me to do that.

**Comment by pixelzoom** [comment]
[phet-software-design-patterns.md](https://github.com/phetsims/phet-info/blob/master/doc/phet-software-design-patterns.md) is currently just a sketch of what might be covered in the document. 

Some options:
(1) Have someone make a pass at fleshing out the document (not something that I have time for or interest in doing), then discuss/refine in discussions.
(2) Discuss patterns one at a time, and assign someone to flesh out the documentation for that pattern based on the discussion. Probably the more expensive of the 2 approaches.

@ariel-phet How do you want to proceed for next Monday's "core hours" discussion, and longterm?

**Comment by ariel-phet** [comment]
@pixelzoom Lets do a compromise.

Can you flesh out 1 pattern? and then that can be discussed at core hours. Perhaps after that, we can do a round robin. Each week a developer takes on a pattern to flesh out, and then it gets discussed at core hours. Seems like it would be a good learning experience.

**Comment by pixelzoom** [comment]
That sounds OK, and I'll be happy to flesh out one of the patterns.  But I won't get to it before next Monday's core hours.

**Comment by zepumph** [comment]
I'll take a stab at one for Monday if you would like.

**Comment by pixelzoom** [comment]
1/7/19 dev meeting on Zoom during core hours:

We put "interested developers" next to each pattern, developers self-identified who would benefits from having the pattern description fleshed out.

@pixelzoom will flesh out "Enumeration" for 1/14/19, for discussion at core hours.

@zepumph will flesh out "Dispose" for 1/14/19 (in case there's time to discuss), but we might not get to discuss until 1/28/19.

**Comment by pixelzoom** [comment]
> @pixelzoom will flesh out "Enumeration" for 1/14/19, for discussion at core hours.

On hold until we resolve phetsims/phet-core#53 (Enumeration conventions).

**Comment by zepumph** [comment]
Dispose design pattern added above.

**Comment by zepumph** [comment]
Discussed dispose today. I will update the docs and we will review next week. I would like to note here that we discussed the 4 implementation patterns seen in the code, but we didn't discuss the general pattern or when it is appropriate to dispose (and conversely when we shouldn't be disposing/when there is no need).

I would like to make sure we do that before moving on from this pattern.

**Comment by pixelzoom** [comment]
4/8/19 meeting notes:

@mbarlow12 did Dependency Injection.

Next up:

@jonathanolson Namespace
@jbphet State Machine
@pixelzoom Observer

I added a Table of Contents, and Author annotations for each section.

**Comment by pixelzoom** [comment]
5/6/19 - skip
5/13/19 - Module @Denz1994 
5/20/19 - Observer @pixelzoom

**Comment by pixelzoom** [comment]
> 5/20/19 - Observer @pixelzoom

Due to other higher priority work, I am not going to have the “Observer” pattern fleshed out in time for 5/20 dev meeting.  5/27 is a holiday.   So I’m going to push this out to 6/3.

**Comment by pixelzoom** [comment]
I'm still too busy to get to the "Observer" pattern, and will be for the foreseeable future. So I'm going to un-volunteer.  If anyone else would like to volunteer for that item, please do.  Or @ariel-phet feel free to assign someone.

**Comment by zepumph** [comment]
It may be good to note https://github.com/phetsims/axon/issues/249 when discussing the Observer pattern (as it pertains to reentrancy, error on add/remove while emit, and listener scrambling).

**Comment by samreid** [comment]
@Denz1994 said he will present regarding options/config some time after Strategy pattern.

**Comment by pixelzoom** [comment]
10/17/19 dev meeting:  We'll continue with options/config (starting with issues #115, #116, and #117) during 10/28/19 core hours.

**Comment by pixelzoom** [comment]
10/31/19 core hours meeting was rescheduled to 11/4/19.

**Comment by samreid** [comment]
At today's meeting, we agreed to take a look at the remaining sections and see who wants to volunteer for remaining ones.

**Comment by pixelzoom** [comment]
We decided to delete "Prototypal Inheritance" from the list.  It's a general topic, and PhET's usage was limited to the (now deprecated) `inherit`.

**Comment by Denz1994** [comment]
As discussed in dev meeting on 12/05/19:

@Denz1994 will follow up with option/config related issues for next Monday.

@chrisklus Has volunteered for Model-View Controller

**Comment by Denz1994** [comment]
From Core Hours on 12/09/19:

@chrisklus send out an invitation for 01/06/20 for Model-View Transform.

**Comment by chrisklus** [comment]
On 2/17/20 we had a discussion about Model-View Transform, see https://github.com/phetsims/phet-info/blob/master/doc/phet-software-design-patterns.md#model-view-transform

This issue is ready for another dev to sign up for an empty section.

**Comment by Denz1994** [comment]
As discussed in dev-meeting on 02/20/20:
@jessegreenberg would like to handle the MVC section. We should detail what is specific to PhET about this section.

**Comment by jessegreenberg** [comment]
We discussed the Model-View-Controller pattern today, I updated the section with things that came up during discussion.

I also added a section on "Scenes" with information on how they should be considered/implemented in a sim, which was suggested during the discussion today.

Removing my assignment, next dev meeting we can decide which topic is next.

**Comment by jessegreenberg** [comment]
Discussed on 3/12/20, but we are going to defer a week and check in next time.

**Comment by jessegreenberg** [comment]
Discussed again 5/21/20 - We are going to defer again until we have some more time.

**Comment by mattpen** [comment]
The next priorities are Observer and Composition/Inheritance.

@ariel-phet asked @brandonLi8 to start work on the Observer Pattern, with potentially presenting on Monday Jun 8.

@pixelzoom suggested that Composition/Inheritance isn't appropriate in this document because there isn't anything particular to PhET that needs to be documented.

We'll revisit after the Observer Pattern discussion!

**Comment by brandonLi8** [comment]
I worked through the [observer pattern](https://github.com/phetsims/phet-info/blob/master/doc/phet-software-design-patterns.md#observer) in the commit above. I'll update with things that come up during discussion.

**Comment by pixelzoom** [comment]
We decided (via Slack poll) to delete the "Composition and Inheritance" section.  I'll do that, and add an item to the CRC.   If we identify PhET-specific issues related to composition/inheritance in the future, we can add that section.

**Comment by pixelzoom** [comment]
Here's how the CRS addresses Composition and Inheritance.  The first items was already in the CRC, I added the second item:

> - [ ] Is inheritance used where appropriate? Does the type hierarchy make sense?
> - [ ] Is composition favored over inheritance where appropriate? See https://en.wikipedia.org/wiki/Composition_over_inheritance.

**Comment by pixelzoom** [comment]
All section of phet-software-design-patterns.md have now been fleshed out.  So closing this issue.
