### ISSUE TITLE
Discuss the Creator/Toolbox pattern

### ISSUE THREAD

**Issue by samreid** [phetsims/phet-info#93]
From https://github.com/phetsims/phet-info/issues/88, we would like to schedule a Monday developer meeting to discuss the Toolbox pattern, which is currently listed as "the creator pattern".

**Comment by samreid** [comment]
I created a minimal example of the pattern here:
http://localhost/scenery/examples/creator-pattern.html

@pixelzoom pointed out https://github.com/phetsims/equality-explorer/blob/daf78c43437991ed53adb487ea4eb2265cb6087d/doc/implementation-notes.md#L97-L113 is also a good write up about this pattern.

**Comment by samreid** [comment]
Here's a patch that uses the model as the map to the view:

<details>

```

Index: examples/creator-pattern.html
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- examples/creator-pattern.html	(revision 7bef4fc7e5ebc1f0fb4fa4115504a04ae5533b4f)
+++ examples/creator-pattern.html	(date 1551126757000)
@@ -67,7 +67,13 @@
   view.addChild( toolbox );
 
   // MODEL
-  class ModelElement {}
+  class ModelElement {
+    constructor() {
+
+      // @public - the view node that depicts this model, if any
+      this.view = null;
+    }
+  }
 
   const model = {
     modelElements: new ObservableArray() // Contains ModelElement instances
@@ -79,7 +85,7 @@
   toolbox.addInputListener( DragListener.createForwardingListener( event => {
     const modelElement = new ModelElement();
     model.modelElements.push( modelElement );
-    const modelElementNode = view.children.find( child => child.modelElement === modelElement );
+    const modelElementNode = modelElement.view;
     modelElementNode.center = event.pointer.point;
     modelElementNode.dragListener.press( event, modelElementNode );
   } ) );
@@ -88,8 +94,7 @@
     constructor( modelElement ) {
       super( 50, { fill: 'red' } );
 
-      // @public (read-only) - so we can look up the view from a model
-      this.modelElement = modelElement;
+      modelElement.view = this;
 
       // @public (read-only) - so we can forward the drag events from the toolbox.
       this.dragListener = new DragListener( {
@@ -108,7 +113,7 @@
 
   // VIEW
   model.modelElements.addItemAddedListener( modelElement => view.addChild( new ModelElementNode( modelElement ) ) );
-  model.modelElements.addItemRemovedListener( modelElement => view.removeChild( view.children.find( child => child.modelElement === modelElement ) ) );
+  model.modelElements.addItemRemovedListener( modelElement => view.removeChild( modelElement.view ) );
 </script>
 
 </body>

```

</details>

**Comment by samreid** [comment]
Here's a patch that uses a `Map`:

<details>

```

Index: examples/creator-pattern.html
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- examples/creator-pattern.html	(revision 7bef4fc7e5ebc1f0fb4fa4115504a04ae5533b4f)
+++ examples/creator-pattern.html	(date 1551127062000)
@@ -75,11 +75,13 @@
 
   // VIEW
 
+  const map = new Map();
+
   // When the icon is dragged, create a new model element, look up the view and forward the drag events.¬
   toolbox.addInputListener( DragListener.createForwardingListener( event => {
     const modelElement = new ModelElement();
     model.modelElements.push( modelElement );
-    const modelElementNode = view.children.find( child => child.modelElement === modelElement );
+    const modelElementNode = map.get( modelElement );
     modelElementNode.center = event.pointer.point;
     modelElementNode.dragListener.press( event, modelElementNode );
   } ) );
@@ -88,9 +90,6 @@
     constructor( modelElement ) {
       super( 50, { fill: 'red' } );
 
-      // @public (read-only) - so we can look up the view from a model
-      this.modelElement = modelElement;
-
       // @public (read-only) - so we can forward the drag events from the toolbox.
       this.dragListener = new DragListener( {
         translateNode: true,
@@ -106,9 +105,15 @@
     }
   }
 
-  // VIEW
-  model.modelElements.addItemAddedListener( modelElement => view.addChild( new ModelElementNode( modelElement ) ) );
-  model.modelElements.addItemRemovedListener( modelElement => view.removeChild( view.children.find( child => child.modelElement === modelElement ) ) );
+  model.modelElements.addItemAddedListener( modelElement => {
+    const modelElementNode = new ModelElementNode( modelElement );
+    view.addChild( modelElementNode );
+    map.set( modelElement, modelElementNode );
+  } );
+  model.modelElements.addItemRemovedListener( modelElement => {
+    view.removeChild( map.get( modelElement ) );
+    map.delete( modelElement );
+  } );
 </script>
 
 </body>

```

</details>

**Comment by samreid** [comment]
Notes from discussion:

@jbphet recommends to elaborate on coordinate transform, and introduce MVT so it will match more realistic usage.  Something like:
```js
    const globalPoint = toolbox.localToGlobalPoint(event.pointer.point);
    const modelPoint = modelViewTransform.viewToModel(globalPoint);
    
    const modelElement = new ModelElement(modelPoint);
```

What patterns are used by Charges and Fields/Balancing Act?

We discussed that MDN indicates cross-platform support for Map, though @jbphet pointed out https://github.com/phetsims/expression-exchange/issues/102

If desired, we could create a small example with Map and cross platform test, see if that works well.  However, after further revisions this doesn't seem critical to the creator pattern, and we revised the example so no lookup is necessary.  This pattern is also in use in TermCreatorNode and its related files.

No pattern meeting on Monday March 11, next meeting will be #95

**Comment by samreid** [comment]
> @jbphet recommends to elaborate on coordinate transform, and introduce MVT so it will match more realistic usage. 

I'm on the fence about this, because many simulations (such as math sims or even Circuit Construction Kit) do not require model view transforms.  I've seen Model View Transform used more in simulations where spatial measurement is important, and there is usually measuring tape, etc.  So I'm not sure whether the example should be burdened by this transform.

**Comment by samreid** [comment]
I asked on slack:

> Do we still want QA to test Map cross platform, after realizing it is not critical to the creator pattern?

Leaving self-assigned until I know whether this warrants a new issue.

**Comment by samreid** [comment]
From slack:

Jesse Greenberg [1:31 PM]
> Do we still want QA to test Map cross platform, after realizing it is not critical to the creator pattern?

Maybe not critical, but I vote yes!


Chris Malley [1:32 PM]
+1.  I’ve had many non-Creator needs for Map.

Sam Reid [1:32 PM]
OK I’ll open an issue

**Comment by pixelzoom** [comment]
Re adding MVT to this example...  I don't think that's necessary.   MVT is not essential to the general pattern, and a barebones example is best.  Perhaps MVT deserves its own pattern description, with a note in Creator pattern that "real world" implementation of the pattern may involve MVT.

**Comment by zepumph** [comment]
@samreid, this section of the design patterns doc looks incomplete, we still have a "for discussion" section at the end, can you explain what should be done here?


```

For discussion:
* phet-io (these listeners should be instrumented and these interactions should appear in the data stream),
  Newly created items could be assigned tandems with tandem.createGroupTandem().createNextTandem() (if they are enumerated
  like `resistor42`).
  or preassigned tandems (if they are uniquely identified, like `voltmeterA` and `voltmeterB`).
* accessibility (hasn't been designed yet)
* improving/fixing the "lookup" phase: CHECK!
* adding entries to other "Deprecated" and "Alternate" sections

```

**Comment by samreid** [comment]
Good find, thanks!  I think those parts can be removed and I'll commit shortly.
