### ISSUE TITLE
convert “PhET Development Overview” to .md file in phet-info?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#94]
“PhET Development Overview” is the intro document that PhET refers people to in the Google Group. It's also a good starting place for new PhET team members.  The document is currently a Google document.  Should it be converted to .md format, and live in the phet-info repo?

This issue was spawned by this Slack discussion with @samreid and @zepumph:

Sam Reid [1:26 PM]
Now that our “PhET Development Overview” has settled down, should it be converted to a MD file in phet-info?

Michael Kauzmann [1:26 PM]
Was the reason for making it a doc the ease of editing?

Chris Malley [1:27 PM]
It might be a Google doc because it was for sharing in the Google group.  I don’t recall exactly.

Sam Reid [1:27 PM]
not sure
I think we began writing the google doc before we started using MD files much

Chris Malley [1:29 PM]
The only reason I see for spending the time to pull it into phet-info is if that would increase the probability that it’s kept up-to-date when processes change.  It’s been broken a few times, and that has caused trouble for 3rd-parties following the instructions.  Not a great first experience with PhET.
(@samreid @zepumph 👍)

Chris Malley [1:29 PM]
If we move it… We’ll need to update all README.md files, and we’ll need to redirect people who have it bookmarked.

**Comment by pixelzoom** [comment]
"PhET Development Overview" currently lives at:
https://docs.google.com/document/d/1Ys1EiwnqQGYuzGOcQSr4uXDes35mF1v1XhMZIl10nk8/edit

bit.ly link used in README.md for all published sims:
http://bit.ly/phet-html5-development-overview

**Comment by pixelzoom** [comment]
I'll also note that editing a Google documents is (by default) easier than editing a .md file. Google's editor is WYSIWIG.  Editing md files requires an md-aware editor, an IDE plug-in, or an iterative edit-preview approach.  For the toolset that I currently use, that makes editing md files more time consuming than Google Docs.

**Comment by samreid** [comment]
I think it would be a nice step to move the PhET Development Overview to an MD file in the phet-info repo.  Then it will be closer to other relevant docs, more integrated with the rest of our GitHub ecosystem, users will be able to look around at other nearby docs, etc.  This file has mostly stabilized.

The main costs would be:
* Initial cost to rewrite in MD
* Cost to update links to point to this new location.

**Comment by Denz1994** [comment]
Dev Meeting: 02/14/19

It would be worth updating and rewriting in .md. This doc typically becomes outdated and it would help to keep our docs in one place. @ariel-phet thought @phet-steele would be a good candidate for this work. @phet-steele reassign to @ariel-phet if there are any concerns.

**Comment by ariel-phet** [comment]
This appears to be done https://github.com/phetsims/phet-info/blob/master/doc/phet-development-overview.md
