### ISSUE TITLE
best practices for options and config

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#96]
We're using `options` quite a bit, and it would be good to have some "best practices" and standardization.  This is something that we should discuss in developer meeting, and should be covered in [phet-software-design-patterns.md](https://github.com/phetsims/phet-info/blob/master/doc/phet-software-design-patterns.md) (see #88).

Notes from Zoom call with @samreid and @zepumph.

Some best practices:

* Do not mutate the `options` argument value. Always assume that the value you are passed might be used elsewhere.
* If you're passing `options` to a superclass, separate the options into client settable and not client settable.  Clients should not be able to set superclass options that the subclass controls. 
* Verify via `assert` that clients can't set superclass options that they should not be able to set.
* For options that are liable to be buggy, validate values by using `assert` or `validate`.
* To check for existence of an option, use `!options.field`, `options.field === undefined` or `hasOwnProperty( 'field' )` as appropriate.  Be sure to avoid gotchas related to falsy values, such as `assert( !someNumber,... )`. 

Here's an example done a couple of ways. `YellowRectangle` is a subclass of `Rectangle`. Clients can provide any `Rectangle` option except `fill`, because `fill: 'yellow'` is what makes it a yellow rectangle. 

`//CON` comments indicate things that are less desirable for an example.

Example 1:

```js
  class YellowRectangle extends Rectangle {

    constructor( x, y, width, height, options ) {

      // defaults that the client can override
      options = _.extend( {
        stroke: 'black',
        cornerRadius: 3
      }, options );

      // validate option values using assert or validate

      // superclass options that the client cannot set
      assert && assert( !options.hasOwnProperty( 'fill' ), 'YellowRectangle sets fill' );
      //CON requires a 2nd extend call
      options = _.extend( {
        fill: 'yellow'
      }, options );

      // bunch of other init ...

      super( x, y, width, height, options );
    }
  }
```

Example 2:

```js
  class YellowRectangle extends Rectangle {

    constructor( x, y, width, height, options ) {

      //CON !options needed
      //CON lack of proximity to 'superclass options that the client cannot set'
      assert && assert( !options || !options.hasOwnProperty( 'fill' ), 'YellowRectangle sets fill' );

      //CON complicated extend call
      options = _.extend( {

        // defaults that the client can override
        stroke: 'black',
        cornerRadius: 3
      }, options, {

        // superclass options that the client cannot set
        fill: 'yellow'
      } );

      // validate option values using assert or validate

      // bunch of other init...

      super( x, y, width, height, options );
    }
  }
```

**Comment by zepumph** [comment]
Related to https://github.com/phetsims/phet-info/issues/88

**Comment by samreid** [comment]
See also the validator pattern used in wave interference's Scene.js:

```js
      // @public (read-only) {number} - width of the visible part of the lattice in the scene's units
      this.waveAreaWidth = validate( config.waveAreaWidth, POSITIVE_NUMBER );
```

**Comment by pixelzoom** [comment]
Neither of the above examples deals with the specifics of validating or unpacking options, and the comment `// validate option values using assert or validate` was intended to cover the pattern used in wave-interference for combining assignment and validation.

**Comment by pixelzoom** [comment]
3/14/19 dev meeting:

@pixelzoom will add a note in [phet-software-design-patterns.md](https://github.com/phetsims/phet-info/blob/master/doc/phet-software-design-patterns.md) that best practices should be incorporated.

**Comment by pixelzoom** [comment]
Hmmm... @samreid originally had something like:

`merge( {...}, NUMBER_CONTROL_OPTIONS ) );`

... and reported that `NUMBER_CONTROL_OPTIONS` was being modified. Do I have that right? If so, there are bigger problems here.

**Comment by pixelzoom** [comment]
Best practices for checking for existence of an option were updated based on https://github.com/phetsims/phet-info/issues/99#issuecomment-480026200.

**Comment by zepumph** [comment]
I'm not seeing where the above was commented. I don't see it in the code review checklist or design patterns doc. Furthermore, I feel like the piece of this issue I really wanted documented was about how to extend in default options and options set by that component at the same time, the ladder should be asserted that it isn't passed in. Note that for https://github.com/phetsims/scenery-phet/issues/451 right now, I'm just going to use a second extend call (so example 1) because the of short timeline there.

**Comment by zepumph** [comment]
Note https://github.com/phetsims/scenery-phet/commit/8302c084b3569b06a71ccff4180d6d10aa16413b#diff-22cf8008e26ed989c8977040d76d6913R171, and that it may be changed depending on this issue.

**Comment by zepumph** [comment]
If there was just one option that the component sets itself, I kinda like just using assignment instead of a second extend call, like so:
```js

    assert && assert( !options.hasOwnProperty( 'children' ),
      'NumberControl sets its own children via options.layoutFunction' );
    options.children = [
      options.layoutFunction( titleNode, numberDisplay, slider, leftArrowButton, rightArrowButton )
    ];

    Node.call( this, options );

```

**Comment by pixelzoom** [comment]
@zepumph Your example in https://github.com/phetsims/phet-info/issues/96#issuecomment-506522956 is impossible to evaluate.  If the`options` Object that was passed into the constructor, that is a problem, since that Object could be used elsewhere.   

Example:

```
class MyNode extends Node {
  constructor( options ) {
     options.children = ... // DANGEROUS, options Object may be used elsewhere
  }
}

class MyNode extends Node {
  constructor( options ) {
     options = _.extend( {...}, options );
     options.children = ... // OK, options is a new Object, private to constructor
  }
}
```

And that is about the only thing that you really need to be concerned with wrt options: Be careful not to modify an options Object that you do not own.

**Comment by pixelzoom** [comment]
@zepumph said:
> I'm not seeing where the above was commented. I don't see it in the code review checklist or design patterns doc.

See https://github.com/phetsims/phet-info/blob/master/doc/phet-software-design-patterns.md#options-and-config:
> TODO Incorporate best practices from https://github.com/phetsims/phet-info/issues/96.

**Comment by pixelzoom** [comment]
Looking through the above comments and what is done in practice, I think that "best practices" can be condensed to the 3 points below.  TODO add examples.

(1) Don't modify an `options` object that you don't own.   If you own the `options` object, then direct assignment to an `options` field is OK.  If you don't own the `options` object, use `_.extend`, to assign a field value, which creates a new object that you then own.

(2) Before setting a value in an `options` object (with either assignment or `_.extends`), verify that the client did not provide a value. Use an assertion to verify. Don't silently override what the client provided.

(3) To test whether a field value exists in an `options` object, the expressions that you have available are:

`!option.someField`
`options.someField === undefined`
`!options.hasOwnProperty( 'someField' )`

TODO Describe when to use these.

**Comment by zepumph** [comment]
(4) Options as an `Object` should never have an extra prototype. We may be able to check this in `merge` since we own that code.

**Comment by jonathanolson** [comment]
We'll discuss at next developer meeting to discuss who could put this into the patterns doc.

**Comment by pixelzoom** [comment]
Everything herein presumably also applied to config.  So I'll change the title of this issue to reflect that.

**Comment by Denz1994** [comment]
From dev meeting: 08/29/19

@Denz1994 will handle the discussion of the phet-software pattern for this topic and will flesh out the doc.

Potentially 09/23/19 will be the date for discussion. Look at issue  https://github.com/phetsims/phet-info/issues/88 for more details.

**Comment by zepumph** [comment]
I'm unsure if this is the appropriate place for this, but I wanted to mention a pattern that I really like.

Using three objects in a merge/extend where the first are overwritable defaults, the second are passed in options, and the third are required non overridable options set by the class itself.

`somePanelOptions = merge( {}, MyConstants.DEFAULT_PANEL_OPTIONS, { /* a few options specific to somePanel */ } );`


 I think we nixed this back around example 2 of https://github.com/phetsims/phet-info/issues/96#issue-418531655, with a con of "complicated extend call".  I really like this while extending constants options above, but I also see value in it for our options practice:

```
      //CON complicated extend call
      options = _.extend( {

        // defaults that the client can override
        stroke: 'black',
        cornerRadius: 3
      }, options, {

        // superclass options that the client cannot set
        fill: 'yellow'
      } );
```
This would eliminate the need for assertions about `fill`, and to me it is important that devs understand the merge/extend algorithm enough to know that everything on the last arg will be in, and the it will be filled in from right to left. If you assume all know that, then to me this is a simpler pattern than having an extra `merge`.

Can we discuss the potential for using this pattern in an upcoming meeting?

**Comment by pixelzoom** [comment]
There's no problem with this, I do it all the time:

`somePanelOptions = merge( {}, MyConstants.DEFAULT_PANEL_OPTIONS, { /* a few options specific to somePanel */ } );`

The second example is the anti-pattern, because it has another significant "con".  It silently overwrites values ('fill', in the example) provided by the client. The options (or config) arg provided by the client should always be the last arg to `merge`, i.e.  

`options = merge( ..., options );`

**Comment by Denz1994** [comment]
From Core hours on 12/09/19:

> somePanelOptions = merge( {}, MyConstants.DEFAULT_PANEL_OPTIONS, { /* a few options specific to somePanel */ } );

The pattern mentioned above is acceptable for certain cases, but we should be careful to not silently override options we don't own.

@samreid Asked about when to use config vs required param. We thought this is a bigger problem in common code repos and should be investigated. The thought here is that we should figure out if these cases where config is being used, should be converted to required parameters. Look at `AnimationTarget` for a good example of how config can fit into common code.

**Comment by Denz1994** [comment]
@pixelzoom Mentioned TWIXT/Transition would be a good candidate for conversion. @samreid Will convert TWIXT/Animation to use `assertMutuallyExclusiveOptions.js`

**Comment by pixelzoom** [comment]
I looked through twixt.  Animation, AnimationTarget, and Transition have `config` constructor parameter.  Transition looked easy to convert to use `required`, and I did so in the above commit. The other 2 don't look appropriate to convert -- the "requiredness" of their config fields depends on mutual exclusivity.  @samreid will look at using `assertMutuallyExclusiveOptions` there.

**Comment by samreid** [comment]
`assertMutuallyExclusiveOptions` doesn't work out of the box for `AnimationTarget` because it uses `null` default values instead of `undefined`.  I'm not sure of the best approach for this case.  @pixelzoom what do you recommend?

**Comment by pixelzoom** [comment]
I recommend leaving AnimationTarget as is.

**Comment by samreid** [comment]
Sounds good, thanks!  Anything else before this issue can be closed?
