### ISSUE TITLE
chipper-two-point-0-list.md is stale

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#97]
I just discovered (chipper-two-point-0-list.md)[https://github.com/phetsims/phet-info/blob/master/sim-info/chipper-two-point-0-list.md], and it appears to be stale.  Some new sims are missing, some sims that have been republished from master are missing,...  And this document isn't mentioned in any checklist. 

@ariel-phet who is maintaining this? Do we still need it?

**Comment by ariel-phet** [comment]
@pixelzoom at some point, I had thought it might be nice to get more sims on chipper 2.0, but it does not seem to have been a big priority or caused massive problems to be on chipper 1.0, and rolling releases are getting done for many sims for other reasons anyhow (like Epub) support. I think we can go ahead and delete this list.

**Comment by ariel-phet** [comment]
deleted, closing
