### ISSUE TITLE
missing GitHub labels in gas-properties

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-info#98]
I'm not sure why, but gas-properties is missing some of the standard labels.  I noticed this when I tried to label an issue  with "status:blocks-sim-publication". 

@Matthew-phet could you please run the labels script?  I've had no luck when I've tried to run it.

**Comment by mattpen** [comment]
@pixelzoom - gas-properties should be good to go now.  

 I made several improvements for #71, have you had a chance to try the script since then?

**Comment by pixelzoom** [comment]
Thanks @mattpen,  gas-properties looks good.

I have not tried the script recently.  Now that I know that it's been improved, I'll give it a go next time.
